//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../pdfreporter-extensions/src/org/oss/pdfreporter/uses/org/apache/digester/RuleSetBase.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgOssPdfreporterUsesOrgApacheDigesterRuleSetBase")
#ifdef RESTRICT_OrgOssPdfreporterUsesOrgApacheDigesterRuleSetBase
#define INCLUDE_ALL_OrgOssPdfreporterUsesOrgApacheDigesterRuleSetBase 0
#else
#define INCLUDE_ALL_OrgOssPdfreporterUsesOrgApacheDigesterRuleSetBase 1
#endif
#undef RESTRICT_OrgOssPdfreporterUsesOrgApacheDigesterRuleSetBase

#if !defined (OrgOssPdfreporterUsesOrgApacheDigesterRuleSetBase_) && (INCLUDE_ALL_OrgOssPdfreporterUsesOrgApacheDigesterRuleSetBase || defined(INCLUDE_OrgOssPdfreporterUsesOrgApacheDigesterRuleSetBase))
#define OrgOssPdfreporterUsesOrgApacheDigesterRuleSetBase_

#define RESTRICT_OrgOssPdfreporterUsesOrgApacheDigesterIRuleSet 1
#define INCLUDE_OrgOssPdfreporterUsesOrgApacheDigesterIRuleSet 1
#include "org/oss/pdfreporter/uses/org/apache/digester/IRuleSet.h"

@protocol OrgOssPdfreporterUsesOrgApacheDigesterIDigester;

@interface OrgOssPdfreporterUsesOrgApacheDigesterRuleSetBase : NSObject < OrgOssPdfreporterUsesOrgApacheDigesterIRuleSet > {
 @public
  NSString *namespaceURI_;
}

#pragma mark Public

- (instancetype)init;

- (void)addRuleInstancesWithOrgOssPdfreporterUsesOrgApacheDigesterIDigester:(id<OrgOssPdfreporterUsesOrgApacheDigesterIDigester>)digester;

- (NSString *)getNamespaceURI;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgOssPdfreporterUsesOrgApacheDigesterRuleSetBase)

J2OBJC_FIELD_SETTER(OrgOssPdfreporterUsesOrgApacheDigesterRuleSetBase, namespaceURI_, NSString *)

FOUNDATION_EXPORT void OrgOssPdfreporterUsesOrgApacheDigesterRuleSetBase_init(OrgOssPdfreporterUsesOrgApacheDigesterRuleSetBase *self);

J2OBJC_TYPE_LITERAL_HEADER(OrgOssPdfreporterUsesOrgApacheDigesterRuleSetBase)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgOssPdfreporterUsesOrgApacheDigesterRuleSetBase")
