//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../pdfreporter-ios/src/org/oss/pdfreporter/compilers/javascript/interpreter/JavaScriptValue.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgOssPdfreporterCompilersJavascriptInterpreterJavaScriptValue")
#ifdef RESTRICT_OrgOssPdfreporterCompilersJavascriptInterpreterJavaScriptValue
#define INCLUDE_ALL_OrgOssPdfreporterCompilersJavascriptInterpreterJavaScriptValue 0
#else
#define INCLUDE_ALL_OrgOssPdfreporterCompilersJavascriptInterpreterJavaScriptValue 1
#endif
#undef RESTRICT_OrgOssPdfreporterCompilersJavascriptInterpreterJavaScriptValue

#if !defined (OrgOssPdfreporterCompilersJavascriptInterpreterJavaScriptValue_) && (INCLUDE_ALL_OrgOssPdfreporterCompilersJavascriptInterpreterJavaScriptValue || defined(INCLUDE_OrgOssPdfreporterCompilersJavascriptInterpreterJavaScriptValue))
#define OrgOssPdfreporterCompilersJavascriptInterpreterJavaScriptValue_

#define RESTRICT_OrgOssPdfreporterCompilersJavascriptInterpreterIScriptValue 1
#define INCLUDE_OrgOssPdfreporterCompilersJavascriptInterpreterIScriptValue 1
#include "org/oss/pdfreporter/compilers/javascript/interpreter/IScriptValue.h"

@class IOSObjectArray;
@class JavaLangDouble;
@class JavaLangInteger;

@interface OrgOssPdfreporterCompilersJavascriptInterpreterJavaScriptValue : NSObject < OrgOssPdfreporterCompilersJavascriptInterpreterIScriptValue >

#pragma mark Public

- (id<OrgOssPdfreporterCompilersJavascriptInterpreterIScriptValue>)callWithOrgOssPdfreporterCompilersJavascriptInterpreterIScriptValueArray:(IOSObjectArray *)args;

- (id<OrgOssPdfreporterCompilersJavascriptInterpreterIScriptValue>)constructWithOrgOssPdfreporterCompilersJavascriptInterpreterIScriptValueArray:(IOSObjectArray *)args;

- (id)getNativeValue;

- (id<OrgOssPdfreporterCompilersJavascriptInterpreterIScriptValue>)invokeWithNSString:(NSString *)method
                 withOrgOssPdfreporterCompilersJavascriptInterpreterIScriptValueArray:(IOSObjectArray *)args;

- (jboolean)isBoolean;

- (jboolean)isEqualToWithId:(id)other;

- (jboolean)isInstanceOfWithId:(id)other;

- (jboolean)isNull;

- (jboolean)isNumber;

- (jboolean)isObject;

- (jboolean)isString;

- (jboolean)isUndefined;

- (void)setNativeValueWithId:(id)nativeValue;

- (jboolean)toBooleanValue;

- (JavaLangDouble *)toDoubleValue;

- (JavaLangInteger *)toIntegerValue;

- (id)toObjectValue;

- (NSString *)description;

- (NSString *)toStringValue;

#pragma mark Package-Private

- (instancetype)initWithId:(id)nativeValue;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgOssPdfreporterCompilersJavascriptInterpreterJavaScriptValue)

FOUNDATION_EXPORT void OrgOssPdfreporterCompilersJavascriptInterpreterJavaScriptValue_initWithId_(OrgOssPdfreporterCompilersJavascriptInterpreterJavaScriptValue *self, id nativeValue);

FOUNDATION_EXPORT OrgOssPdfreporterCompilersJavascriptInterpreterJavaScriptValue *new_OrgOssPdfreporterCompilersJavascriptInterpreterJavaScriptValue_initWithId_(id nativeValue) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgOssPdfreporterCompilersJavascriptInterpreterJavaScriptValue *create_OrgOssPdfreporterCompilersJavascriptInterpreterJavaScriptValue_initWithId_(id nativeValue);

J2OBJC_TYPE_LITERAL_HEADER(OrgOssPdfreporterCompilersJavascriptInterpreterJavaScriptValue)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgOssPdfreporterCompilersJavascriptInterpreterJavaScriptValue")
