//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../pdfreporter-core/src/org/oss/pdfreporter/compilers/javascript/JavaScriptFunctionsObject.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/lang/UnsupportedOperationException.h"
#include "java/lang/reflect/Method.h"
#include "java/util/HashMap.h"
#include "java/util/Map.h"
#include "java/util/logging/Level.h"
#include "java/util/logging/Logger.h"
#include "org/oss/pdfreporter/compilers/javascript/JavaScriptCallableThisDecorator.h"
#include "org/oss/pdfreporter/compilers/javascript/JavaScriptFunctionsObject.h"
#include "org/oss/pdfreporter/compilers/javascript/factory/ICallable.h"
#include "org/oss/pdfreporter/compilers/javascript/factory/IContext.h"
#include "org/oss/pdfreporter/compilers/javascript/factory/IScriptable.h"
#include "org/oss/pdfreporter/compilers/javascript/factory/IWrapFactory.h"
#include "org/oss/pdfreporter/engine/fill/JREvaluator.h"
#include "org/oss/pdfreporter/functions/FunctionSupport.h"
#include "org/oss/pdfreporter/functions/FunctionsUtil.h"

@interface OrgOssPdfreporterCompilersJavascriptJavaScriptFunctionsObject () {
 @public
  id<OrgOssPdfreporterCompilersJavascriptFactoryIContext> context_;
  OrgOssPdfreporterFunctionsFunctionsUtil *functionsUtil_;
  OrgOssPdfreporterEngineFillJREvaluator *evaluator_;
  id<JavaUtilMap> functions_;
  id<OrgOssPdfreporterCompilersJavascriptFactoryIScriptable> prototype_;
  id<OrgOssPdfreporterCompilersJavascriptFactoryIScriptable> parentScope_;
}

@end

J2OBJC_FIELD_SETTER(OrgOssPdfreporterCompilersJavascriptJavaScriptFunctionsObject, context_, id<OrgOssPdfreporterCompilersJavascriptFactoryIContext>)
J2OBJC_FIELD_SETTER(OrgOssPdfreporterCompilersJavascriptJavaScriptFunctionsObject, functionsUtil_, OrgOssPdfreporterFunctionsFunctionsUtil *)
J2OBJC_FIELD_SETTER(OrgOssPdfreporterCompilersJavascriptJavaScriptFunctionsObject, evaluator_, OrgOssPdfreporterEngineFillJREvaluator *)
J2OBJC_FIELD_SETTER(OrgOssPdfreporterCompilersJavascriptJavaScriptFunctionsObject, functions_, id<JavaUtilMap>)
J2OBJC_FIELD_SETTER(OrgOssPdfreporterCompilersJavascriptJavaScriptFunctionsObject, prototype_, id<OrgOssPdfreporterCompilersJavascriptFactoryIScriptable>)
J2OBJC_FIELD_SETTER(OrgOssPdfreporterCompilersJavascriptJavaScriptFunctionsObject, parentScope_, id<OrgOssPdfreporterCompilersJavascriptFactoryIScriptable>)

inline JavaUtilLoggingLogger *OrgOssPdfreporterCompilersJavascriptJavaScriptFunctionsObject_get_logger();
static JavaUtilLoggingLogger *OrgOssPdfreporterCompilersJavascriptJavaScriptFunctionsObject_logger;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterCompilersJavascriptJavaScriptFunctionsObject, logger, JavaUtilLoggingLogger *)

J2OBJC_INITIALIZED_DEFN(OrgOssPdfreporterCompilersJavascriptJavaScriptFunctionsObject)

@implementation OrgOssPdfreporterCompilersJavascriptJavaScriptFunctionsObject

- (instancetype)initWithOrgOssPdfreporterCompilersJavascriptFactoryIContext:(id<OrgOssPdfreporterCompilersJavascriptFactoryIContext>)context
                                withOrgOssPdfreporterFunctionsFunctionsUtil:(OrgOssPdfreporterFunctionsFunctionsUtil *)functionsUtil
                                 withOrgOssPdfreporterEngineFillJREvaluator:(OrgOssPdfreporterEngineFillJREvaluator *)evaluator {
  OrgOssPdfreporterCompilersJavascriptJavaScriptFunctionsObject_initWithOrgOssPdfreporterCompilersJavascriptFactoryIContext_withOrgOssPdfreporterFunctionsFunctionsUtil_withOrgOssPdfreporterEngineFillJREvaluator_(self, context, functionsUtil, evaluator);
  return self;
}

- (NSString *)getClassName {
  return @"JRFunctions";
}

- (id)getWithNSString:(NSString *)name
withOrgOssPdfreporterCompilersJavascriptFactoryIScriptable:(id<OrgOssPdfreporterCompilersJavascriptFactoryIScriptable>)start {
  id function = [self resolveFunctionWithNSString:name withOrgOssPdfreporterCompilersJavascriptFactoryIScriptable:start];
  return function;
}

- (id)resolveFunctionWithNSString:(NSString *)name
withOrgOssPdfreporterCompilersJavascriptFactoryIScriptable:(id<OrgOssPdfreporterCompilersJavascriptFactoryIScriptable>)start {
  id function = [((id<JavaUtilMap>) nil_chk(functions_)) getWithId:name];
  if (function != nil) {
    return function;
  }
  function = JreLoadStatic(OrgOssPdfreporterCompilersJavascriptFactoryIScriptable, NOT_FOUND);
  JavaLangReflectMethod *method = [((OrgOssPdfreporterFunctionsFunctionsUtil *) nil_chk(functionsUtil_)) getMethod4FunctionWithNSString:name];
  if (method != nil) {
    IOSClass *functionClass = [method getDeclaringClass];
    if ([OrgOssPdfreporterFunctionsFunctionSupport_class_() isAssignableFrom:functionClass]) {
      id<OrgOssPdfreporterFunctionsFunctionSupport> functionSupport = [((OrgOssPdfreporterEngineFillJREvaluator *) nil_chk(evaluator_)) getFunctionSupportWithIOSClass:functionClass];
      id<OrgOssPdfreporterCompilersJavascriptFactoryIScriptable> functionScriptable = [((id<OrgOssPdfreporterCompilersJavascriptFactoryIWrapFactory>) nil_chk([((id<OrgOssPdfreporterCompilersJavascriptFactoryIContext>) nil_chk(context_)) getWrapFactory])) wrapAsJavaObjectWithOrgOssPdfreporterCompilersJavascriptFactoryIContext:context_ withOrgOssPdfreporterCompilersJavascriptFactoryIScriptable:start withId:functionSupport withIOSClass:functionClass];
      id functionCall = [((id<OrgOssPdfreporterCompilersJavascriptFactoryIScriptable>) nil_chk(functionScriptable)) getWithNSString:name withOrgOssPdfreporterCompilersJavascriptFactoryIScriptable:start];
      if ([OrgOssPdfreporterCompilersJavascriptFactoryICallable_class_() isInstance:functionCall]) {
        id<OrgOssPdfreporterCompilersJavascriptFactoryICallable> functionCallable = (id<OrgOssPdfreporterCompilersJavascriptFactoryICallable>) cast_check(functionCall, OrgOssPdfreporterCompilersJavascriptFactoryICallable_class_());
        function = new_OrgOssPdfreporterCompilersJavascriptJavaScriptCallableThisDecorator_initWithOrgOssPdfreporterCompilersJavascriptFactoryICallable_withOrgOssPdfreporterCompilersJavascriptFactoryIScriptable_(functionCallable, functionScriptable);
      }
    }
    else {
      id<OrgOssPdfreporterCompilersJavascriptFactoryIScriptable> functionScriptable = [((id<OrgOssPdfreporterCompilersJavascriptFactoryIWrapFactory>) nil_chk([((id<OrgOssPdfreporterCompilersJavascriptFactoryIContext>) nil_chk(context_)) getWrapFactory])) wrapJavaClassWithOrgOssPdfreporterCompilersJavascriptFactoryIContext:context_ withOrgOssPdfreporterCompilersJavascriptFactoryIScriptable:start withIOSClass:functionClass];
      id functionCall = [((id<OrgOssPdfreporterCompilersJavascriptFactoryIScriptable>) nil_chk(functionScriptable)) getWithNSString:name withOrgOssPdfreporterCompilersJavascriptFactoryIScriptable:start];
      if ([OrgOssPdfreporterCompilersJavascriptFactoryICallable_class_() isInstance:functionCall]) {
        function = functionCall;
      }
    }
    if (function == JreLoadStatic(OrgOssPdfreporterCompilersJavascriptFactoryIScriptable, NOT_FOUND) && [((JavaUtilLoggingLogger *) nil_chk(OrgOssPdfreporterCompilersJavascriptJavaScriptFunctionsObject_logger)) isLoggableWithJavaUtilLoggingLevel:JreLoadStatic(JavaUtilLoggingLevel, FINER)]) {
      [((JavaUtilLoggingLogger *) nil_chk(OrgOssPdfreporterCompilersJavascriptJavaScriptFunctionsObject_logger)) finerWithNSString:JreStrcat("$$$$", @"did not find JavaScript function ", name, @" in class ", [((IOSClass *) nil_chk(functionClass)) getName])];
    }
  }
  (void) [functions_ putWithId:name withId:function];
  return function;
}

- (id)getWithInt:(jint)index
withOrgOssPdfreporterCompilersJavascriptFactoryIScriptable:(id<OrgOssPdfreporterCompilersJavascriptFactoryIScriptable>)start {
  return JreLoadStatic(OrgOssPdfreporterCompilersJavascriptFactoryIScriptable, NOT_FOUND);
}

- (jboolean)hasWithNSString:(NSString *)name
withOrgOssPdfreporterCompilersJavascriptFactoryIScriptable:(id<OrgOssPdfreporterCompilersJavascriptFactoryIScriptable>)start {
  id function = [self resolveFunctionWithNSString:name withOrgOssPdfreporterCompilersJavascriptFactoryIScriptable:start];
  return function != JreLoadStatic(OrgOssPdfreporterCompilersJavascriptFactoryIScriptable, NOT_FOUND);
}

- (jboolean)hasWithInt:(jint)index
withOrgOssPdfreporterCompilersJavascriptFactoryIScriptable:(id<OrgOssPdfreporterCompilersJavascriptFactoryIScriptable>)start {
  return false;
}

- (void)putWithNSString:(NSString *)name
withOrgOssPdfreporterCompilersJavascriptFactoryIScriptable:(id<OrgOssPdfreporterCompilersJavascriptFactoryIScriptable>)start
                 withId:(id)value {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (void)putWithInt:(jint)index
withOrgOssPdfreporterCompilersJavascriptFactoryIScriptable:(id<OrgOssPdfreporterCompilersJavascriptFactoryIScriptable>)start
            withId:(id)value {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (void)delete__WithNSString:(NSString *)name {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (void)delete__WithInt:(jint)index {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (id<OrgOssPdfreporterCompilersJavascriptFactoryIScriptable>)getPrototype {
  return prototype_;
}

- (void)setPrototypeWithOrgOssPdfreporterCompilersJavascriptFactoryIScriptable:(id<OrgOssPdfreporterCompilersJavascriptFactoryIScriptable>)prototype {
  self->prototype_ = prototype;
}

- (id<OrgOssPdfreporterCompilersJavascriptFactoryIScriptable>)getParentScope {
  return parentScope_;
}

- (void)setParentScopeWithOrgOssPdfreporterCompilersJavascriptFactoryIScriptable:(id<OrgOssPdfreporterCompilersJavascriptFactoryIScriptable>)parent {
  self->parentScope_ = parent;
}

- (IOSObjectArray *)getIds {
  return [IOSObjectArray newArrayWithLength:0 type:NSObject_class_()];
}

- (id)getDefaultValueWithIOSClass:(IOSClass *)hint {
  return @"[object JRFunctions]";
}

- (jboolean)hasInstanceWithOrgOssPdfreporterCompilersJavascriptFactoryIScriptable:(id<OrgOssPdfreporterCompilersJavascriptFactoryIScriptable>)instance {
  return false;
}

+ (void)initialize {
  if (self == [OrgOssPdfreporterCompilersJavascriptJavaScriptFunctionsObject class]) {
    OrgOssPdfreporterCompilersJavascriptJavaScriptFunctionsObject_logger = JavaUtilLoggingLogger_getLoggerWithNSString_([OrgOssPdfreporterCompilersJavascriptJavaScriptFunctionsObject_class_() getName]);
    J2OBJC_SET_INITIALIZED(OrgOssPdfreporterCompilersJavascriptJavaScriptFunctionsObject)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithOrgOssPdfreporterCompilersJavascriptFactoryIContext:withOrgOssPdfreporterFunctionsFunctionsUtil:withOrgOssPdfreporterEngineFillJREvaluator:", "JavaScriptFunctionsObject", NULL, 0x1, NULL, NULL },
    { "getClassName", NULL, "Ljava.lang.String;", 0x1, NULL, NULL },
    { "getWithNSString:withOrgOssPdfreporterCompilersJavascriptFactoryIScriptable:", "get", "Ljava.lang.Object;", 0x1, NULL, NULL },
    { "resolveFunctionWithNSString:withOrgOssPdfreporterCompilersJavascriptFactoryIScriptable:", "resolveFunction", "Ljava.lang.Object;", 0x4, NULL, NULL },
    { "getWithInt:withOrgOssPdfreporterCompilersJavascriptFactoryIScriptable:", "get", "Ljava.lang.Object;", 0x1, NULL, NULL },
    { "hasWithNSString:withOrgOssPdfreporterCompilersJavascriptFactoryIScriptable:", "has", "Z", 0x1, NULL, NULL },
    { "hasWithInt:withOrgOssPdfreporterCompilersJavascriptFactoryIScriptable:", "has", "Z", 0x1, NULL, NULL },
    { "putWithNSString:withOrgOssPdfreporterCompilersJavascriptFactoryIScriptable:withId:", "put", "V", 0x1, NULL, NULL },
    { "putWithInt:withOrgOssPdfreporterCompilersJavascriptFactoryIScriptable:withId:", "put", "V", 0x1, NULL, NULL },
    { "delete__WithNSString:", "delete", "V", 0x1, NULL, NULL },
    { "delete__WithInt:", "delete", "V", 0x1, NULL, NULL },
    { "getPrototype", NULL, "Lorg.oss.pdfreporter.compilers.javascript.factory.IScriptable;", 0x1, NULL, NULL },
    { "setPrototypeWithOrgOssPdfreporterCompilersJavascriptFactoryIScriptable:", "setPrototype", "V", 0x1, NULL, NULL },
    { "getParentScope", NULL, "Lorg.oss.pdfreporter.compilers.javascript.factory.IScriptable;", 0x1, NULL, NULL },
    { "setParentScopeWithOrgOssPdfreporterCompilersJavascriptFactoryIScriptable:", "setParentScope", "V", 0x1, NULL, NULL },
    { "getIds", NULL, "[Ljava.lang.Object;", 0x1, NULL, NULL },
    { "getDefaultValueWithIOSClass:", "getDefaultValue", "Ljava.lang.Object;", 0x1, NULL, "(Ljava/lang/Class<*>;)Ljava/lang/Object;" },
    { "hasInstanceWithOrgOssPdfreporterCompilersJavascriptFactoryIScriptable:", "hasInstance", "Z", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "logger", "logger", 0x1a, "Ljava.util.logging.Logger;", &OrgOssPdfreporterCompilersJavascriptJavaScriptFunctionsObject_logger, NULL, .constantValue.asLong = 0 },
    { "context_", NULL, 0x12, "Lorg.oss.pdfreporter.compilers.javascript.factory.IContext;", NULL, NULL, .constantValue.asLong = 0 },
    { "functionsUtil_", NULL, 0x12, "Lorg.oss.pdfreporter.functions.FunctionsUtil;", NULL, NULL, .constantValue.asLong = 0 },
    { "evaluator_", NULL, 0x12, "Lorg.oss.pdfreporter.engine.fill.JREvaluator;", NULL, NULL, .constantValue.asLong = 0 },
    { "functions_", NULL, 0x12, "Ljava.util.Map;", NULL, "Ljava/util/Map<Ljava/lang/String;Ljava/lang/Object;>;", .constantValue.asLong = 0 },
    { "prototype_", NULL, 0x2, "Lorg.oss.pdfreporter.compilers.javascript.factory.IScriptable;", NULL, NULL, .constantValue.asLong = 0 },
    { "parentScope_", NULL, 0x2, "Lorg.oss.pdfreporter.compilers.javascript.factory.IScriptable;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _OrgOssPdfreporterCompilersJavascriptJavaScriptFunctionsObject = { 2, "JavaScriptFunctionsObject", "org.oss.pdfreporter.compilers.javascript", NULL, 0x1, 18, methods, 7, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgOssPdfreporterCompilersJavascriptJavaScriptFunctionsObject;
}

@end

void OrgOssPdfreporterCompilersJavascriptJavaScriptFunctionsObject_initWithOrgOssPdfreporterCompilersJavascriptFactoryIContext_withOrgOssPdfreporterFunctionsFunctionsUtil_withOrgOssPdfreporterEngineFillJREvaluator_(OrgOssPdfreporterCompilersJavascriptJavaScriptFunctionsObject *self, id<OrgOssPdfreporterCompilersJavascriptFactoryIContext> context, OrgOssPdfreporterFunctionsFunctionsUtil *functionsUtil, OrgOssPdfreporterEngineFillJREvaluator *evaluator) {
  NSObject_init(self);
  self->context_ = context;
  self->functionsUtil_ = functionsUtil;
  self->evaluator_ = evaluator;
  self->functions_ = new_JavaUtilHashMap_init();
}

OrgOssPdfreporterCompilersJavascriptJavaScriptFunctionsObject *new_OrgOssPdfreporterCompilersJavascriptJavaScriptFunctionsObject_initWithOrgOssPdfreporterCompilersJavascriptFactoryIContext_withOrgOssPdfreporterFunctionsFunctionsUtil_withOrgOssPdfreporterEngineFillJREvaluator_(id<OrgOssPdfreporterCompilersJavascriptFactoryIContext> context, OrgOssPdfreporterFunctionsFunctionsUtil *functionsUtil, OrgOssPdfreporterEngineFillJREvaluator *evaluator) {
  J2OBJC_NEW_IMPL(OrgOssPdfreporterCompilersJavascriptJavaScriptFunctionsObject, initWithOrgOssPdfreporterCompilersJavascriptFactoryIContext_withOrgOssPdfreporterFunctionsFunctionsUtil_withOrgOssPdfreporterEngineFillJREvaluator_, context, functionsUtil, evaluator)
}

OrgOssPdfreporterCompilersJavascriptJavaScriptFunctionsObject *create_OrgOssPdfreporterCompilersJavascriptJavaScriptFunctionsObject_initWithOrgOssPdfreporterCompilersJavascriptFactoryIContext_withOrgOssPdfreporterFunctionsFunctionsUtil_withOrgOssPdfreporterEngineFillJREvaluator_(id<OrgOssPdfreporterCompilersJavascriptFactoryIContext> context, OrgOssPdfreporterFunctionsFunctionsUtil *functionsUtil, OrgOssPdfreporterEngineFillJREvaluator *evaluator) {
  J2OBJC_CREATE_IMPL(OrgOssPdfreporterCompilersJavascriptJavaScriptFunctionsObject, initWithOrgOssPdfreporterCompilersJavascriptFactoryIContext_withOrgOssPdfreporterFunctionsFunctionsUtil_withOrgOssPdfreporterEngineFillJREvaluator_, context, functionsUtil, evaluator)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgOssPdfreporterCompilersJavascriptJavaScriptFunctionsObject)
