//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../pdfreporter-core/src/org/oss/pdfreporter/registry/ISessionObject.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgOssPdfreporterRegistryISessionObject")
#ifdef RESTRICT_OrgOssPdfreporterRegistryISessionObject
#define INCLUDE_ALL_OrgOssPdfreporterRegistryISessionObject 0
#else
#define INCLUDE_ALL_OrgOssPdfreporterRegistryISessionObject 1
#endif
#undef RESTRICT_OrgOssPdfreporterRegistryISessionObject

#if !defined (OrgOssPdfreporterRegistryISessionObject_) && (INCLUDE_ALL_OrgOssPdfreporterRegistryISessionObject || defined(INCLUDE_OrgOssPdfreporterRegistryISessionObject))
#define OrgOssPdfreporterRegistryISessionObject_

@protocol OrgOssPdfreporterRegistryISessionObject < NSObject, JavaObject >

- (void)dispose;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgOssPdfreporterRegistryISessionObject)

J2OBJC_TYPE_LITERAL_HEADER(OrgOssPdfreporterRegistryISessionObject)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgOssPdfreporterRegistryISessionObject")
