//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../pdfreporter-core/src/org/w3c/tools/codec/Base64FormatException.java
//

#include "J2ObjC_source.h"
#include "java/lang/Exception.h"
#include "org/w3c/tools/codec/Base64FormatException.h"

@implementation OrgW3cToolsCodecBase64FormatException

- (instancetype)initWithNSString:(NSString *)msg {
  OrgW3cToolsCodecBase64FormatException_initWithNSString_(self, msg);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithNSString:", "Base64FormatException", NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcClassInfo _OrgW3cToolsCodecBase64FormatException = { 2, "Base64FormatException", "org.w3c.tools.codec", NULL, 0x1, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgW3cToolsCodecBase64FormatException;
}

@end

void OrgW3cToolsCodecBase64FormatException_initWithNSString_(OrgW3cToolsCodecBase64FormatException *self, NSString *msg) {
  JavaLangException_initWithNSString_(self, msg);
}

OrgW3cToolsCodecBase64FormatException *new_OrgW3cToolsCodecBase64FormatException_initWithNSString_(NSString *msg) {
  J2OBJC_NEW_IMPL(OrgW3cToolsCodecBase64FormatException, initWithNSString_, msg)
}

OrgW3cToolsCodecBase64FormatException *create_OrgW3cToolsCodecBase64FormatException_initWithNSString_(NSString *msg) {
  J2OBJC_CREATE_IMPL(OrgW3cToolsCodecBase64FormatException, initWithNSString_, msg)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgW3cToolsCodecBase64FormatException)
