//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../pdfreporter-core/src/org/oss/pdfreporter/engine/JRAlignment.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgOssPdfreporterEngineJRAlignment")
#ifdef RESTRICT_OrgOssPdfreporterEngineJRAlignment
#define INCLUDE_ALL_OrgOssPdfreporterEngineJRAlignment 0
#else
#define INCLUDE_ALL_OrgOssPdfreporterEngineJRAlignment 1
#endif
#undef RESTRICT_OrgOssPdfreporterEngineJRAlignment

#if !defined (OrgOssPdfreporterEngineJRAlignment_) && (INCLUDE_ALL_OrgOssPdfreporterEngineJRAlignment || defined(INCLUDE_OrgOssPdfreporterEngineJRAlignment))
#define OrgOssPdfreporterEngineJRAlignment_

#define RESTRICT_OrgOssPdfreporterEngineJRStyleContainer 1
#define INCLUDE_OrgOssPdfreporterEngineJRStyleContainer 1
#include "org/oss/pdfreporter/engine/JRStyleContainer.h"

@class OrgOssPdfreporterEngineTypeHorizontalAlignEnum;
@class OrgOssPdfreporterEngineTypeVerticalAlignEnum;

@protocol OrgOssPdfreporterEngineJRAlignment < OrgOssPdfreporterEngineJRStyleContainer, NSObject, JavaObject >

- (OrgOssPdfreporterEngineTypeHorizontalAlignEnum *)getHorizontalAlignmentValue;

- (OrgOssPdfreporterEngineTypeHorizontalAlignEnum *)getOwnHorizontalAlignmentValue;

- (void)setHorizontalAlignmentWithOrgOssPdfreporterEngineTypeHorizontalAlignEnum:(OrgOssPdfreporterEngineTypeHorizontalAlignEnum *)horizontalAlignment;

- (OrgOssPdfreporterEngineTypeVerticalAlignEnum *)getVerticalAlignmentValue;

- (OrgOssPdfreporterEngineTypeVerticalAlignEnum *)getOwnVerticalAlignmentValue;

- (void)setVerticalAlignmentWithOrgOssPdfreporterEngineTypeVerticalAlignEnum:(OrgOssPdfreporterEngineTypeVerticalAlignEnum *)verticalAlignment;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgOssPdfreporterEngineJRAlignment)

J2OBJC_TYPE_LITERAL_HEADER(OrgOssPdfreporterEngineJRAlignment)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgOssPdfreporterEngineJRAlignment")
