//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../pdfreporter-core/src/org/oss/pdfreporter/engine/JRCloneable.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgOssPdfreporterEngineJRCloneable")
#ifdef RESTRICT_OrgOssPdfreporterEngineJRCloneable
#define INCLUDE_ALL_OrgOssPdfreporterEngineJRCloneable 0
#else
#define INCLUDE_ALL_OrgOssPdfreporterEngineJRCloneable 1
#endif
#undef RESTRICT_OrgOssPdfreporterEngineJRCloneable

#if !defined (OrgOssPdfreporterEngineJRCloneable_) && (INCLUDE_ALL_OrgOssPdfreporterEngineJRCloneable || defined(INCLUDE_OrgOssPdfreporterEngineJRCloneable))
#define OrgOssPdfreporterEngineJRCloneable_

@protocol OrgOssPdfreporterEngineJRCloneable < NSCopying, NSObject, JavaObject >

- (id)clone;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgOssPdfreporterEngineJRCloneable)

J2OBJC_TYPE_LITERAL_HEADER(OrgOssPdfreporterEngineJRCloneable)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgOssPdfreporterEngineJRCloneable")
