//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../pdfreporter-core/src/org/oss/pdfreporter/engine/JRCommonRectangle.java
//

#include "J2ObjC_source.h"
#include "org/oss/pdfreporter/engine/JRCommonRectangle.h"

@interface OrgOssPdfreporterEngineJRCommonRectangle : NSObject

@end

@implementation OrgOssPdfreporterEngineJRCommonRectangle

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getRadius", NULL, "I", 0x401, NULL, NULL },
    { "getOwnRadius", NULL, "Ljava.lang.Integer;", 0x401, NULL, NULL },
    { "setRadiusWithInt:", "setRadius", "V", 0x401, NULL, NULL },
    { "setRadiusWithJavaLangInteger:", "setRadius", "V", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _OrgOssPdfreporterEngineJRCommonRectangle = { 2, "JRCommonRectangle", "org.oss.pdfreporter.engine", NULL, 0x609, 4, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgOssPdfreporterEngineJRCommonRectangle;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgOssPdfreporterEngineJRCommonRectangle)
