//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../pdfreporter-core/src/org/oss/pdfreporter/engine/JRConditionalStyle.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgOssPdfreporterEngineJRConditionalStyle")
#ifdef RESTRICT_OrgOssPdfreporterEngineJRConditionalStyle
#define INCLUDE_ALL_OrgOssPdfreporterEngineJRConditionalStyle 0
#else
#define INCLUDE_ALL_OrgOssPdfreporterEngineJRConditionalStyle 1
#endif
#undef RESTRICT_OrgOssPdfreporterEngineJRConditionalStyle

#if !defined (OrgOssPdfreporterEngineJRConditionalStyle_) && (INCLUDE_ALL_OrgOssPdfreporterEngineJRConditionalStyle || defined(INCLUDE_OrgOssPdfreporterEngineJRConditionalStyle))
#define OrgOssPdfreporterEngineJRConditionalStyle_

#define RESTRICT_OrgOssPdfreporterEngineJRStyle 1
#define INCLUDE_OrgOssPdfreporterEngineJRStyle 1
#include "org/oss/pdfreporter/engine/JRStyle.h"

@protocol OrgOssPdfreporterEngineJRExpression;

@protocol OrgOssPdfreporterEngineJRConditionalStyle < OrgOssPdfreporterEngineJRStyle, NSObject, JavaObject >

- (id<OrgOssPdfreporterEngineJRExpression>)getConditionExpression;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgOssPdfreporterEngineJRConditionalStyle)

J2OBJC_TYPE_LITERAL_HEADER(OrgOssPdfreporterEngineJRConditionalStyle)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgOssPdfreporterEngineJRConditionalStyle")
