//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../pdfreporter-core/src/org/oss/pdfreporter/engine/JRPrintImage.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgOssPdfreporterEngineJRPrintImage")
#ifdef RESTRICT_OrgOssPdfreporterEngineJRPrintImage
#define INCLUDE_ALL_OrgOssPdfreporterEngineJRPrintImage 0
#else
#define INCLUDE_ALL_OrgOssPdfreporterEngineJRPrintImage 1
#endif
#undef RESTRICT_OrgOssPdfreporterEngineJRPrintImage

#if !defined (OrgOssPdfreporterEngineJRPrintImage_) && (INCLUDE_ALL_OrgOssPdfreporterEngineJRPrintImage || defined(INCLUDE_OrgOssPdfreporterEngineJRPrintImage))
#define OrgOssPdfreporterEngineJRPrintImage_

#define RESTRICT_OrgOssPdfreporterEngineJRPrintGraphicElement 1
#define INCLUDE_OrgOssPdfreporterEngineJRPrintGraphicElement 1
#include "org/oss/pdfreporter/engine/JRPrintGraphicElement.h"

#define RESTRICT_OrgOssPdfreporterEngineJRPrintAnchor 1
#define INCLUDE_OrgOssPdfreporterEngineJRPrintAnchor 1
#include "org/oss/pdfreporter/engine/JRPrintAnchor.h"

#define RESTRICT_OrgOssPdfreporterEngineJRPrintHyperlink 1
#define INCLUDE_OrgOssPdfreporterEngineJRPrintHyperlink 1
#include "org/oss/pdfreporter/engine/JRPrintHyperlink.h"

#define RESTRICT_OrgOssPdfreporterEngineJRAlignment 1
#define INCLUDE_OrgOssPdfreporterEngineJRAlignment 1
#include "org/oss/pdfreporter/engine/JRAlignment.h"

#define RESTRICT_OrgOssPdfreporterEngineJRCommonImage 1
#define INCLUDE_OrgOssPdfreporterEngineJRCommonImage 1
#include "org/oss/pdfreporter/engine/JRCommonImage.h"

@class OrgOssPdfreporterEngineTypeOnErrorTypeEnum;
@class OrgOssPdfreporterEngineTypeScaleImageEnum;
@protocol OrgOssPdfreporterEngineRenderable;

@protocol OrgOssPdfreporterEngineJRPrintImage < OrgOssPdfreporterEngineJRPrintGraphicElement, OrgOssPdfreporterEngineJRPrintAnchor, OrgOssPdfreporterEngineJRPrintHyperlink, OrgOssPdfreporterEngineJRAlignment, OrgOssPdfreporterEngineJRCommonImage, NSObject, JavaObject >

- (id<OrgOssPdfreporterEngineRenderable>)getRenderable;

- (void)setRenderableWithOrgOssPdfreporterEngineRenderable:(id<OrgOssPdfreporterEngineRenderable>)renderer;

- (void)setScaleImageWithOrgOssPdfreporterEngineTypeScaleImageEnum:(OrgOssPdfreporterEngineTypeScaleImageEnum *)scaleImage;

- (jboolean)isUsingCache;

- (void)setUsingCacheWithBoolean:(jboolean)isUsingCache;

- (jboolean)isLazy;

- (void)setLazyWithBoolean:(jboolean)isLazy;

- (OrgOssPdfreporterEngineTypeOnErrorTypeEnum *)getOnErrorTypeValue;

- (void)setOnErrorTypeWithOrgOssPdfreporterEngineTypeOnErrorTypeEnum:(OrgOssPdfreporterEngineTypeOnErrorTypeEnum *)onErrorType;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgOssPdfreporterEngineJRPrintImage)

J2OBJC_TYPE_LITERAL_HEADER(OrgOssPdfreporterEngineJRPrintImage)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgOssPdfreporterEngineJRPrintImage")
