//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../pdfreporter-core/src/org/oss/pdfreporter/engine/JRPrintText.java
//

#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "org/oss/pdfreporter/engine/JRPrintText.h"

J2OBJC_INITIALIZED_DEFN(OrgOssPdfreporterEngineJRPrintText)

IOSShortArray *OrgOssPdfreporterEngineJRPrintText_ZERO_LINE_BREAK_OFFSETS;

@implementation OrgOssPdfreporterEngineJRPrintText

+ (IOSShortArray *)ZERO_LINE_BREAK_OFFSETS {
  return OrgOssPdfreporterEngineJRPrintText_ZERO_LINE_BREAK_OFFSETS;
}

+ (void)initialize {
  if (self == [OrgOssPdfreporterEngineJRPrintText class]) {
    OrgOssPdfreporterEngineJRPrintText_ZERO_LINE_BREAK_OFFSETS = [IOSShortArray newArrayWithLength:0];
    J2OBJC_SET_INITIALIZED(OrgOssPdfreporterEngineJRPrintText)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getText", NULL, "Ljava.lang.String;", 0x401, NULL, NULL },
    { "setTextWithNSString:", "setText", "V", 0x401, NULL, NULL },
    { "getValue", NULL, "Ljava.lang.Object;", 0x401, NULL, NULL },
    { "setValueWithId:", "setValue", "V", 0x401, NULL, NULL },
    { "getTextTruncateIndex", NULL, "Ljava.lang.Integer;", 0x401, NULL, NULL },
    { "setTextTruncateIndexWithJavaLangInteger:", "setTextTruncateIndex", "V", 0x401, NULL, NULL },
    { "getTextTruncateSuffix", NULL, "Ljava.lang.String;", 0x401, NULL, NULL },
    { "setTextTruncateSuffixWithNSString:", "setTextTruncateSuffix", "V", 0x401, NULL, NULL },
    { "getFullText", NULL, "Ljava.lang.String;", 0x401, NULL, NULL },
    { "getOriginalText", NULL, "Ljava.lang.String;", 0x401, NULL, NULL },
    { "getStyledTextWithOrgOssPdfreporterEngineJRStyledTextAttributeSelector:", "getStyledText", "Lorg.oss.pdfreporter.engine.util.JRStyledText;", 0x401, NULL, NULL },
    { "getFullStyledTextWithOrgOssPdfreporterEngineJRStyledTextAttributeSelector:", "getFullStyledText", "Lorg.oss.pdfreporter.engine.util.JRStyledText;", 0x401, NULL, NULL },
    { "setTextFormatWithOrgOssPdfreporterEngineFillTextFormat:", "setTextFormat", "V", 0x401, NULL, NULL },
    { "getLineSpacingFactor", NULL, "F", 0x401, NULL, NULL },
    { "setLineSpacingFactorWithFloat:", "setLineSpacingFactor", "V", 0x401, NULL, NULL },
    { "getLeadingOffset", NULL, "F", 0x401, NULL, NULL },
    { "setLeadingOffsetWithFloat:", "setLeadingOffset", "V", 0x401, NULL, NULL },
    { "getOwnRotationValue", NULL, "Lorg.oss.pdfreporter.engine.type.RotationEnum;", 0x401, NULL, NULL },
    { "setRotationWithOrgOssPdfreporterEngineTypeRotationEnum:", "setRotation", "V", 0x401, NULL, NULL },
    { "getRunDirectionValue", NULL, "Lorg.oss.pdfreporter.engine.type.RunDirectionEnum;", 0x401, NULL, NULL },
    { "setRunDirectionWithOrgOssPdfreporterEngineTypeRunDirectionEnum:", "setRunDirection", "V", 0x401, NULL, NULL },
    { "getTextHeight", NULL, "F", 0x401, NULL, NULL },
    { "setTextHeightWithFloat:", "setTextHeight", "V", 0x401, NULL, NULL },
    { "getOwnLineSpacingValue", NULL, "Lorg.oss.pdfreporter.engine.type.LineSpacingEnum;", 0x401, NULL, NULL },
    { "setLineSpacingWithOrgOssPdfreporterEngineTypeLineSpacingEnum:", "setLineSpacing", "V", 0x401, NULL, NULL },
    { "getOwnMarkup", NULL, "Ljava.lang.String;", 0x401, NULL, NULL },
    { "setMarkupWithNSString:", "setMarkup", "V", 0x401, NULL, NULL },
    { "getFont", NULL, "Lorg.oss.pdfreporter.engine.JRFont;", 0x401, NULL, NULL },
    { "setFontWithOrgOssPdfreporterEngineJRFont:", "setFont", "V", 0x401, NULL, NULL },
    { "getValueClassName", NULL, "Ljava.lang.String;", 0x401, NULL, NULL },
    { "getPattern", NULL, "Ljava.lang.String;", 0x401, NULL, NULL },
    { "getFormatFactoryClass", NULL, "Ljava.lang.String;", 0x401, NULL, NULL },
    { "getLocaleCode", NULL, "Ljava.lang.String;", 0x401, NULL, NULL },
    { "getTimeZoneId", NULL, "Ljava.lang.String;", 0x401, NULL, NULL },
    { "getLineBreakOffsets", NULL, "[S", 0x401, NULL, NULL },
    { "setLineBreakOffsetsWithShortArray:", "setLineBreakOffsets", "V", 0x401, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "ZERO_LINE_BREAK_OFFSETS", "ZERO_LINE_BREAK_OFFSETS", 0x19, "[S", &OrgOssPdfreporterEngineJRPrintText_ZERO_LINE_BREAK_OFFSETS, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _OrgOssPdfreporterEngineJRPrintText = { 2, "JRPrintText", "org.oss.pdfreporter.engine", NULL, 0x609, 36, methods, 1, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgOssPdfreporterEngineJRPrintText;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgOssPdfreporterEngineJRPrintText)
