//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../pdfreporter-core/src/org/oss/pdfreporter/engine/JRTextField.java
//

#include "J2ObjC_source.h"
#include "org/oss/pdfreporter/engine/JRTextField.h"

NSString *OrgOssPdfreporterEngineJRTextField_PROPERTY_FORMAT_TIMEZONE = @"net.sf.jasperreports.pattern.timezone";
NSString *OrgOssPdfreporterEngineJRTextField_FORMAT_TIMEZONE_SYSTEM = @"System";

@implementation OrgOssPdfreporterEngineJRTextField

+ (NSString *)PROPERTY_FORMAT_TIMEZONE {
  return OrgOssPdfreporterEngineJRTextField_PROPERTY_FORMAT_TIMEZONE;
}

+ (NSString *)FORMAT_TIMEZONE_SYSTEM {
  return OrgOssPdfreporterEngineJRTextField_FORMAT_TIMEZONE_SYSTEM;
}

- (id)copyWithZone:(NSZone *)zone {
  return [self clone];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "isStretchWithOverflow", NULL, "Z", 0x401, NULL, NULL },
    { "setStretchWithOverflowWithBoolean:", "setStretchWithOverflow", "V", 0x401, NULL, NULL },
    { "getPattern", NULL, "Ljava.lang.String;", 0x401, NULL, NULL },
    { "getOwnPattern", NULL, "Ljava.lang.String;", 0x401, NULL, NULL },
    { "setPatternWithNSString:", "setPattern", "V", 0x401, NULL, NULL },
    { "isBlankWhenNull", NULL, "Z", 0x401, NULL, NULL },
    { "isOwnBlankWhenNull", NULL, "Ljava.lang.Boolean;", 0x401, NULL, NULL },
    { "setBlankWhenNullWithBoolean:", "setBlankWhenNull", "V", 0x401, NULL, NULL },
    { "setBlankWhenNullWithJavaLangBoolean:", "setBlankWhenNull", "V", 0x401, NULL, NULL },
    { "getExpression", NULL, "Lorg.oss.pdfreporter.engine.JRExpression;", 0x401, NULL, NULL },
    { "getPatternExpression", NULL, "Lorg.oss.pdfreporter.engine.JRExpression;", 0x401, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "PROPERTY_FORMAT_TIMEZONE", "PROPERTY_FORMAT_TIMEZONE", 0x19, "Ljava.lang.String;", &OrgOssPdfreporterEngineJRTextField_PROPERTY_FORMAT_TIMEZONE, NULL, .constantValue.asLong = 0 },
    { "FORMAT_TIMEZONE_SYSTEM", "FORMAT_TIMEZONE_SYSTEM", 0x19, "Ljava.lang.String;", &OrgOssPdfreporterEngineJRTextField_FORMAT_TIMEZONE_SYSTEM, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _OrgOssPdfreporterEngineJRTextField = { 2, "JRTextField", "org.oss.pdfreporter.engine", NULL, 0x609, 11, methods, 2, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgOssPdfreporterEngineJRTextField;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgOssPdfreporterEngineJRTextField)
