//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../pdfreporter-core/src/org/oss/pdfreporter/engine/base/JRBaseComponentElement.java
//

#include "J2ObjC_source.h"
#include "org/oss/pdfreporter/engine/DefaultJasperReportsContext.h"
#include "org/oss/pdfreporter/engine/JRComponentElement.h"
#include "org/oss/pdfreporter/engine/JRConstants.h"
#include "org/oss/pdfreporter/engine/JRExpressionCollector.h"
#include "org/oss/pdfreporter/engine/JRVisitor.h"
#include "org/oss/pdfreporter/engine/base/JRBaseComponentElement.h"
#include "org/oss/pdfreporter/engine/base/JRBaseElement.h"
#include "org/oss/pdfreporter/engine/base/JRBaseObjectFactory.h"
#include "org/oss/pdfreporter/engine/component/Component.h"
#include "org/oss/pdfreporter/engine/component/ComponentCompiler.h"
#include "org/oss/pdfreporter/engine/component/ComponentKey.h"
#include "org/oss/pdfreporter/engine/component/ComponentsEnvironment.h"
#include "org/oss/pdfreporter/engine/component/IComponentManager.h"

@interface OrgOssPdfreporterEngineBaseJRBaseComponentElement () {
 @public
  OrgOssPdfreporterEngineComponentComponentKey *componentKey_;
  id<OrgOssPdfreporterEngineComponentComponent> component_;
}

@end

J2OBJC_FIELD_SETTER(OrgOssPdfreporterEngineBaseJRBaseComponentElement, componentKey_, OrgOssPdfreporterEngineComponentComponentKey *)
J2OBJC_FIELD_SETTER(OrgOssPdfreporterEngineBaseJRBaseComponentElement, component_, id<OrgOssPdfreporterEngineComponentComponent>)

inline jlong OrgOssPdfreporterEngineBaseJRBaseComponentElement_get_serialVersionUID();
#define OrgOssPdfreporterEngineBaseJRBaseComponentElement_serialVersionUID 10200LL
J2OBJC_STATIC_FIELD_CONSTANT(OrgOssPdfreporterEngineBaseJRBaseComponentElement, serialVersionUID, jlong)

@implementation OrgOssPdfreporterEngineBaseJRBaseComponentElement

- (instancetype)initWithOrgOssPdfreporterEngineJRComponentElement:(id<OrgOssPdfreporterEngineJRComponentElement>)element
               withOrgOssPdfreporterEngineBaseJRBaseObjectFactory:(OrgOssPdfreporterEngineBaseJRBaseObjectFactory *)factory {
  OrgOssPdfreporterEngineBaseJRBaseComponentElement_initWithOrgOssPdfreporterEngineJRComponentElement_withOrgOssPdfreporterEngineBaseJRBaseObjectFactory_(self, element, factory);
  return self;
}

- (id<OrgOssPdfreporterEngineComponentComponent>)getComponent {
  return component_;
}

- (OrgOssPdfreporterEngineComponentComponentKey *)getComponentKey {
  return componentKey_;
}

- (void)collectExpressionsWithOrgOssPdfreporterEngineJRExpressionCollector:(OrgOssPdfreporterEngineJRExpressionCollector *)collector {
  id<OrgOssPdfreporterEngineComponentIComponentManager> manager = [((OrgOssPdfreporterEngineComponentComponentsEnvironment *) nil_chk(OrgOssPdfreporterEngineComponentComponentsEnvironment_getInstanceWithOrgOssPdfreporterEngineJasperReportsContext_(OrgOssPdfreporterEngineDefaultJasperReportsContext_getInstance()))) getManagerWithOrgOssPdfreporterEngineComponentComponentKey:componentKey_];
  [((id<OrgOssPdfreporterEngineComponentComponentCompiler>) nil_chk([((id<OrgOssPdfreporterEngineComponentIComponentManager>) nil_chk(manager)) getComponentCompilerWithOrgOssPdfreporterEngineJasperReportsContext:OrgOssPdfreporterEngineDefaultJasperReportsContext_getInstance()])) collectExpressionsWithOrgOssPdfreporterEngineComponentComponent:component_ withOrgOssPdfreporterEngineJRExpressionCollector:collector];
}

- (void)visitWithOrgOssPdfreporterEngineJRVisitor:(id<OrgOssPdfreporterEngineJRVisitor>)visitor {
  [((id<OrgOssPdfreporterEngineJRVisitor>) nil_chk(visitor)) visitComponentElementWithOrgOssPdfreporterEngineJRComponentElement:self];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithOrgOssPdfreporterEngineJRComponentElement:withOrgOssPdfreporterEngineBaseJRBaseObjectFactory:", "JRBaseComponentElement", NULL, 0x1, NULL, NULL },
    { "getComponent", NULL, "Lorg.oss.pdfreporter.engine.component.Component;", 0x1, NULL, NULL },
    { "getComponentKey", NULL, "Lorg.oss.pdfreporter.engine.component.ComponentKey;", 0x1, NULL, NULL },
    { "collectExpressionsWithOrgOssPdfreporterEngineJRExpressionCollector:", "collectExpressions", "V", 0x1, NULL, NULL },
    { "visitWithOrgOssPdfreporterEngineJRVisitor:", "visit", "V", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "serialVersionUID", "serialVersionUID", 0x1a, "J", NULL, NULL, .constantValue.asLong = OrgOssPdfreporterEngineBaseJRBaseComponentElement_serialVersionUID },
    { "componentKey_", NULL, 0x2, "Lorg.oss.pdfreporter.engine.component.ComponentKey;", NULL, NULL, .constantValue.asLong = 0 },
    { "component_", NULL, 0x2, "Lorg.oss.pdfreporter.engine.component.Component;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _OrgOssPdfreporterEngineBaseJRBaseComponentElement = { 2, "JRBaseComponentElement", "org.oss.pdfreporter.engine.base", NULL, 0x1, 5, methods, 3, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgOssPdfreporterEngineBaseJRBaseComponentElement;
}

@end

void OrgOssPdfreporterEngineBaseJRBaseComponentElement_initWithOrgOssPdfreporterEngineJRComponentElement_withOrgOssPdfreporterEngineBaseJRBaseObjectFactory_(OrgOssPdfreporterEngineBaseJRBaseComponentElement *self, id<OrgOssPdfreporterEngineJRComponentElement> element, OrgOssPdfreporterEngineBaseJRBaseObjectFactory *factory) {
  OrgOssPdfreporterEngineBaseJRBaseElement_initWithOrgOssPdfreporterEngineJRElement_withOrgOssPdfreporterEngineBaseJRBaseObjectFactory_(self, element, factory);
  self->componentKey_ = [((id<OrgOssPdfreporterEngineJRComponentElement>) nil_chk(element)) getComponentKey];
  id<OrgOssPdfreporterEngineComponentIComponentManager> manager = [((OrgOssPdfreporterEngineComponentComponentsEnvironment *) nil_chk(OrgOssPdfreporterEngineComponentComponentsEnvironment_getInstanceWithOrgOssPdfreporterEngineJasperReportsContext_(OrgOssPdfreporterEngineDefaultJasperReportsContext_getInstance()))) getManagerWithOrgOssPdfreporterEngineComponentComponentKey:self->componentKey_];
  self->component_ = [((id<OrgOssPdfreporterEngineComponentComponentCompiler>) nil_chk([((id<OrgOssPdfreporterEngineComponentIComponentManager>) nil_chk(manager)) getComponentCompilerWithOrgOssPdfreporterEngineJasperReportsContext:OrgOssPdfreporterEngineDefaultJasperReportsContext_getInstance()])) toCompiledComponentWithOrgOssPdfreporterEngineComponentComponent:[element getComponent] withOrgOssPdfreporterEngineBaseJRBaseObjectFactory:factory];
}

OrgOssPdfreporterEngineBaseJRBaseComponentElement *new_OrgOssPdfreporterEngineBaseJRBaseComponentElement_initWithOrgOssPdfreporterEngineJRComponentElement_withOrgOssPdfreporterEngineBaseJRBaseObjectFactory_(id<OrgOssPdfreporterEngineJRComponentElement> element, OrgOssPdfreporterEngineBaseJRBaseObjectFactory *factory) {
  J2OBJC_NEW_IMPL(OrgOssPdfreporterEngineBaseJRBaseComponentElement, initWithOrgOssPdfreporterEngineJRComponentElement_withOrgOssPdfreporterEngineBaseJRBaseObjectFactory_, element, factory)
}

OrgOssPdfreporterEngineBaseJRBaseComponentElement *create_OrgOssPdfreporterEngineBaseJRBaseComponentElement_initWithOrgOssPdfreporterEngineJRComponentElement_withOrgOssPdfreporterEngineBaseJRBaseObjectFactory_(id<OrgOssPdfreporterEngineJRComponentElement> element, OrgOssPdfreporterEngineBaseJRBaseObjectFactory *factory) {
  J2OBJC_CREATE_IMPL(OrgOssPdfreporterEngineBaseJRBaseComponentElement, initWithOrgOssPdfreporterEngineJRComponentElement_withOrgOssPdfreporterEngineBaseJRBaseObjectFactory_, element, factory)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgOssPdfreporterEngineBaseJRBaseComponentElement)
