//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../pdfreporter-core/src/org/oss/pdfreporter/engine/base/VirtualizableElementList.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "java/lang/IndexOutOfBoundsException.h"
#include "java/lang/Math.h"
#include "java/lang/System.h"
#include "java/util/AbstractCollection.h"
#include "java/util/AbstractList.h"
#include "java/util/ArrayList.h"
#include "java/util/Arrays.h"
#include "java/util/List.h"
#include "java/util/Random.h"
#include "java/util/concurrent/atomic/AtomicInteger.h"
#include "org/oss/pdfreporter/engine/JRConstants.h"
#include "org/oss/pdfreporter/engine/JRPrintElement.h"
#include "org/oss/pdfreporter/engine/JRVirtualizer.h"
#include "org/oss/pdfreporter/engine/base/ElementStore.h"
#include "org/oss/pdfreporter/engine/base/JRVirtualPrintPage.h"
#include "org/oss/pdfreporter/engine/base/VirtualElementsData.h"
#include "org/oss/pdfreporter/engine/base/VirtualizableElementList.h"
#include "org/oss/pdfreporter/engine/fill/JRVirtualizationContext.h"
#include "org/oss/pdfreporter/engine/util/DeepPrintElementCounter.h"

@interface OrgOssPdfreporterEngineBaseVirtualizableElementList () {
 @public
  OrgOssPdfreporterEngineFillJRVirtualizationContext *virtualizationContext_;
  id<OrgOssPdfreporterEngineBaseElementStore> store_;
}

- (void)initStoreWithOrgOssPdfreporterEngineBaseJRVirtualPrintPage:(OrgOssPdfreporterEngineBaseJRVirtualPrintPage *)page OBJC_METHOD_FAMILY_NONE;

- (void)cacheInContextWithOrgOssPdfreporterEngineJRPrintElement:(id<OrgOssPdfreporterEngineJRPrintElement>)element;

- (void)createBlockList;

@end

J2OBJC_FIELD_SETTER(OrgOssPdfreporterEngineBaseVirtualizableElementList, virtualizationContext_, OrgOssPdfreporterEngineFillJRVirtualizationContext *)
J2OBJC_FIELD_SETTER(OrgOssPdfreporterEngineBaseVirtualizableElementList, store_, id<OrgOssPdfreporterEngineBaseElementStore>)

inline jlong OrgOssPdfreporterEngineBaseVirtualizableElementList_get_serialVersionUID();
#define OrgOssPdfreporterEngineBaseVirtualizableElementList_serialVersionUID 10200LL
J2OBJC_STATIC_FIELD_CONSTANT(OrgOssPdfreporterEngineBaseVirtualizableElementList, serialVersionUID, jlong)

__attribute__((unused)) static void OrgOssPdfreporterEngineBaseVirtualizableElementList_initStoreWithOrgOssPdfreporterEngineBaseJRVirtualPrintPage_(OrgOssPdfreporterEngineBaseVirtualizableElementList *self, OrgOssPdfreporterEngineBaseJRVirtualPrintPage *page);

__attribute__((unused)) static void OrgOssPdfreporterEngineBaseVirtualizableElementList_cacheInContextWithOrgOssPdfreporterEngineJRPrintElement_(OrgOssPdfreporterEngineBaseVirtualizableElementList *self, id<OrgOssPdfreporterEngineJRPrintElement> element);

__attribute__((unused)) static void OrgOssPdfreporterEngineBaseVirtualizableElementList_createBlockList(OrgOssPdfreporterEngineBaseVirtualizableElementList *self);

@interface OrgOssPdfreporterEngineBaseElementsBlock () {
 @public
  OrgOssPdfreporterEngineFillJRVirtualizationContext *context_;
  NSString *uid_;
  id<JavaUtilList> elements_;
  volatile_jint size_;
  OrgOssPdfreporterEngineBaseVirtualElementsData *virtualData_;
  jint deepElementCount_;
  OrgOssPdfreporterEngineBaseJRVirtualPrintPage *page_;
}

- (void)lockContext;

- (void)unlockContext;

- (void)register__;

- (NSString *)makeUID;

- (void)ensureDataAndTouch;

- (void)ensureData;

- (void)deregister;

@end

J2OBJC_FIELD_SETTER(OrgOssPdfreporterEngineBaseElementsBlock, context_, OrgOssPdfreporterEngineFillJRVirtualizationContext *)
J2OBJC_FIELD_SETTER(OrgOssPdfreporterEngineBaseElementsBlock, uid_, NSString *)
J2OBJC_FIELD_SETTER(OrgOssPdfreporterEngineBaseElementsBlock, elements_, id<JavaUtilList>)
J2OBJC_FIELD_SETTER(OrgOssPdfreporterEngineBaseElementsBlock, virtualData_, OrgOssPdfreporterEngineBaseVirtualElementsData *)
J2OBJC_FIELD_SETTER(OrgOssPdfreporterEngineBaseElementsBlock, page_, OrgOssPdfreporterEngineBaseJRVirtualPrintPage *)

inline jlong OrgOssPdfreporterEngineBaseElementsBlock_get_serialVersionUID();
#define OrgOssPdfreporterEngineBaseElementsBlock_serialVersionUID 10200LL
J2OBJC_STATIC_FIELD_CONSTANT(OrgOssPdfreporterEngineBaseElementsBlock, serialVersionUID, jlong)

inline JavaUtilConcurrentAtomicAtomicInteger *OrgOssPdfreporterEngineBaseElementsBlock_get_uidCounter();
static JavaUtilConcurrentAtomicAtomicInteger *OrgOssPdfreporterEngineBaseElementsBlock_uidCounter;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterEngineBaseElementsBlock, uidCounter, JavaUtilConcurrentAtomicAtomicInteger *)

inline JavaUtilRandom *OrgOssPdfreporterEngineBaseElementsBlock_get_uidRandom();
static JavaUtilRandom *OrgOssPdfreporterEngineBaseElementsBlock_uidRandom;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterEngineBaseElementsBlock, uidRandom, JavaUtilRandom *)

__attribute__((unused)) static void OrgOssPdfreporterEngineBaseElementsBlock_lockContext(OrgOssPdfreporterEngineBaseElementsBlock *self);

__attribute__((unused)) static void OrgOssPdfreporterEngineBaseElementsBlock_unlockContext(OrgOssPdfreporterEngineBaseElementsBlock *self);

__attribute__((unused)) static void OrgOssPdfreporterEngineBaseElementsBlock_register__(OrgOssPdfreporterEngineBaseElementsBlock *self);

__attribute__((unused)) static NSString *OrgOssPdfreporterEngineBaseElementsBlock_makeUID(OrgOssPdfreporterEngineBaseElementsBlock *self);

__attribute__((unused)) static void OrgOssPdfreporterEngineBaseElementsBlock_ensureDataAndTouch(OrgOssPdfreporterEngineBaseElementsBlock *self);

__attribute__((unused)) static void OrgOssPdfreporterEngineBaseElementsBlock_ensureData(OrgOssPdfreporterEngineBaseElementsBlock *self);

__attribute__((unused)) static void OrgOssPdfreporterEngineBaseElementsBlock_deregister(OrgOssPdfreporterEngineBaseElementsBlock *self);

@interface OrgOssPdfreporterEngineBaseElementsBlockList () {
 @public
  jint blockCount_;
  IOSIntArray *offsets_;
  IOSObjectArray *blocks_;
  jint size_;
  jint lastIndex_;
}

@end

J2OBJC_FIELD_SETTER(OrgOssPdfreporterEngineBaseElementsBlockList, offsets_, IOSIntArray *)
J2OBJC_FIELD_SETTER(OrgOssPdfreporterEngineBaseElementsBlockList, blocks_, IOSObjectArray *)

inline jlong OrgOssPdfreporterEngineBaseElementsBlockList_get_serialVersionUID();
#define OrgOssPdfreporterEngineBaseElementsBlockList_serialVersionUID 10200LL
J2OBJC_STATIC_FIELD_CONSTANT(OrgOssPdfreporterEngineBaseElementsBlockList, serialVersionUID, jlong)

inline jint OrgOssPdfreporterEngineBaseElementsBlockList_get_INITIAL_SIZE();
#define OrgOssPdfreporterEngineBaseElementsBlockList_INITIAL_SIZE 3
J2OBJC_STATIC_FIELD_CONSTANT(OrgOssPdfreporterEngineBaseElementsBlockList, INITIAL_SIZE, jint)

inline jint OrgOssPdfreporterEngineBaseElementsBlockList_get_MAX_INCREMENT();
#define OrgOssPdfreporterEngineBaseElementsBlockList_MAX_INCREMENT 200
J2OBJC_STATIC_FIELD_CONSTANT(OrgOssPdfreporterEngineBaseElementsBlockList, MAX_INCREMENT, jint)

@implementation OrgOssPdfreporterEngineBaseVirtualizableElementList

- (instancetype)initWithOrgOssPdfreporterEngineFillJRVirtualizationContext:(OrgOssPdfreporterEngineFillJRVirtualizationContext *)virtualizationContext
                         withOrgOssPdfreporterEngineBaseJRVirtualPrintPage:(OrgOssPdfreporterEngineBaseJRVirtualPrintPage *)page {
  OrgOssPdfreporterEngineBaseVirtualizableElementList_initWithOrgOssPdfreporterEngineFillJRVirtualizationContext_withOrgOssPdfreporterEngineBaseJRVirtualPrintPage_(self, virtualizationContext, page);
  return self;
}

- (void)initStoreWithOrgOssPdfreporterEngineBaseJRVirtualPrintPage:(OrgOssPdfreporterEngineBaseJRVirtualPrintPage *)page {
  OrgOssPdfreporterEngineBaseVirtualizableElementList_initStoreWithOrgOssPdfreporterEngineBaseJRVirtualPrintPage_(self, page);
}

- (void)setWithJavaUtilList:(id<JavaUtilList>)elements {
  @synchronized(self) {
    [self clear];
    [self addAllWithJavaUtilCollection:elements];
  }
}

- (void)cacheInContextWithOrgOssPdfreporterEngineJRPrintElement:(id<OrgOssPdfreporterEngineJRPrintElement>)element {
  OrgOssPdfreporterEngineBaseVirtualizableElementList_cacheInContextWithOrgOssPdfreporterEngineJRPrintElement_(self, element);
}

- (id<OrgOssPdfreporterEngineJRPrintElement>)getWithInt:(jint)index {
  @synchronized(self) {
    return [((id<OrgOssPdfreporterEngineBaseElementStore>) nil_chk(store_)) getWithInt:index];
  }
}

- (jint)size {
  @synchronized(self) {
    return [((id<OrgOssPdfreporterEngineBaseElementStore>) nil_chk(store_)) size];
  }
}

- (id<OrgOssPdfreporterEngineJRPrintElement>)setWithInt:(jint)index
                                                 withId:(id<OrgOssPdfreporterEngineJRPrintElement>)element {
  @synchronized(self) {
    OrgOssPdfreporterEngineBaseVirtualizableElementList_cacheInContextWithOrgOssPdfreporterEngineJRPrintElement_(self, element);
    return [((id<OrgOssPdfreporterEngineBaseElementStore>) nil_chk(store_)) setWithInt:index withOrgOssPdfreporterEngineJRPrintElement:element];
  }
}

- (void)createBlockList {
  OrgOssPdfreporterEngineBaseVirtualizableElementList_createBlockList(self);
}

- (jboolean)addWithId:(id<OrgOssPdfreporterEngineJRPrintElement>)element {
  @synchronized(self) {
    OrgOssPdfreporterEngineBaseVirtualizableElementList_cacheInContextWithOrgOssPdfreporterEngineJRPrintElement_(self, element);
    if (![((id<OrgOssPdfreporterEngineBaseElementStore>) nil_chk(store_)) addWithOrgOssPdfreporterEngineJRPrintElement:element]) {
      OrgOssPdfreporterEngineBaseVirtualizableElementList_createBlockList(self);
      [((id<OrgOssPdfreporterEngineBaseElementStore>) nil_chk(store_)) addWithOrgOssPdfreporterEngineJRPrintElement:element];
    }
    return true;
  }
}

- (void)addWithInt:(jint)index
            withId:(id<OrgOssPdfreporterEngineJRPrintElement>)element {
  @synchronized(self) {
    OrgOssPdfreporterEngineBaseVirtualizableElementList_cacheInContextWithOrgOssPdfreporterEngineJRPrintElement_(self, element);
    if (![((id<OrgOssPdfreporterEngineBaseElementStore>) nil_chk(store_)) addWithInt:index withOrgOssPdfreporterEngineJRPrintElement:element]) {
      OrgOssPdfreporterEngineBaseVirtualizableElementList_createBlockList(self);
      [((id<OrgOssPdfreporterEngineBaseElementStore>) nil_chk(store_)) addWithInt:index withOrgOssPdfreporterEngineJRPrintElement:element];
    }
  }
}

- (id<OrgOssPdfreporterEngineJRPrintElement>)removeWithInt:(jint)index {
  @synchronized(self) {
    return [((id<OrgOssPdfreporterEngineBaseElementStore>) nil_chk(store_)) removeWithInt:index];
  }
}

- (void)clear {
  @synchronized(self) {
    OrgOssPdfreporterEngineBaseJRVirtualPrintPage *page = [((id<OrgOssPdfreporterEngineBaseElementStore>) nil_chk(store_)) getPage];
    [((id<OrgOssPdfreporterEngineBaseElementStore>) nil_chk(store_)) dispose];
    OrgOssPdfreporterEngineBaseVirtualizableElementList_initStoreWithOrgOssPdfreporterEngineBaseJRVirtualPrintPage_(self, page);
  }
}

- (void)dispose {
  @synchronized(self) {
    [((id<OrgOssPdfreporterEngineBaseElementStore>) nil_chk(store_)) dispose];
  }
}

- (NSUInteger)countByEnumeratingWithState:(NSFastEnumerationState *)state objects:(__unsafe_unretained id *)stackbuf count:(NSUInteger)len {
  return JreDefaultFastEnumeration(self, state, stackbuf, len);
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithOrgOssPdfreporterEngineFillJRVirtualizationContext:withOrgOssPdfreporterEngineBaseJRVirtualPrintPage:", "VirtualizableElementList", NULL, 0x1, NULL, NULL },
    { "initStoreWithOrgOssPdfreporterEngineBaseJRVirtualPrintPage:", "initStore", "V", 0x2, NULL, NULL },
    { "setWithJavaUtilList:", "set", "V", 0x21, NULL, "(Ljava/util/List<Lorg/oss/pdfreporter/engine/JRPrintElement;>;)V" },
    { "cacheInContextWithOrgOssPdfreporterEngineJRPrintElement:", "cacheInContext", "V", 0x2, NULL, NULL },
    { "getWithInt:", "get", "Lorg.oss.pdfreporter.engine.JRPrintElement;", 0x21, NULL, "(I)Lorg/oss/pdfreporter/engine/JRPrintElement;" },
    { "size", NULL, "I", 0x21, NULL, NULL },
    { "setWithInt:withId:", "set", "Lorg.oss.pdfreporter.engine.JRPrintElement;", 0x21, NULL, "(ILorg/oss/pdfreporter/engine/JRPrintElement;)Lorg/oss/pdfreporter/engine/JRPrintElement;" },
    { "createBlockList", NULL, "V", 0x2, NULL, NULL },
    { "addWithId:", "add", "Z", 0x21, NULL, "(Lorg/oss/pdfreporter/engine/JRPrintElement;)Z" },
    { "addWithInt:withId:", "add", "V", 0x21, NULL, "(ILorg/oss/pdfreporter/engine/JRPrintElement;)V" },
    { "removeWithInt:", "remove", "Lorg.oss.pdfreporter.engine.JRPrintElement;", 0x21, NULL, "(I)Lorg/oss/pdfreporter/engine/JRPrintElement;" },
    { "clear", NULL, "V", 0x21, NULL, NULL },
    { "dispose", NULL, "V", 0x21, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "serialVersionUID", "serialVersionUID", 0x1a, "J", NULL, NULL, .constantValue.asLong = OrgOssPdfreporterEngineBaseVirtualizableElementList_serialVersionUID },
    { "virtualizationContext_", NULL, 0x12, "Lorg.oss.pdfreporter.engine.fill.JRVirtualizationContext;", NULL, NULL, .constantValue.asLong = 0 },
    { "store_", NULL, 0x2, "Lorg.oss.pdfreporter.engine.base.ElementStore;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const char *superclass_type_args[] = {"Lorg.oss.pdfreporter.engine.JRPrintElement;"};
  static const J2ObjcClassInfo _OrgOssPdfreporterEngineBaseVirtualizableElementList = { 2, "VirtualizableElementList", "org.oss.pdfreporter.engine.base", NULL, 0x1, 13, methods, 3, fields, 1, superclass_type_args, 0, NULL, NULL, "Ljava/util/AbstractList<Lorg/oss/pdfreporter/engine/JRPrintElement;>;Ljava/io/Serializable;" };
  return &_OrgOssPdfreporterEngineBaseVirtualizableElementList;
}

@end

void OrgOssPdfreporterEngineBaseVirtualizableElementList_initWithOrgOssPdfreporterEngineFillJRVirtualizationContext_withOrgOssPdfreporterEngineBaseJRVirtualPrintPage_(OrgOssPdfreporterEngineBaseVirtualizableElementList *self, OrgOssPdfreporterEngineFillJRVirtualizationContext *virtualizationContext, OrgOssPdfreporterEngineBaseJRVirtualPrintPage *page) {
  JavaUtilAbstractList_init(self);
  self->virtualizationContext_ = virtualizationContext;
  OrgOssPdfreporterEngineBaseVirtualizableElementList_initStoreWithOrgOssPdfreporterEngineBaseJRVirtualPrintPage_(self, page);
}

OrgOssPdfreporterEngineBaseVirtualizableElementList *new_OrgOssPdfreporterEngineBaseVirtualizableElementList_initWithOrgOssPdfreporterEngineFillJRVirtualizationContext_withOrgOssPdfreporterEngineBaseJRVirtualPrintPage_(OrgOssPdfreporterEngineFillJRVirtualizationContext *virtualizationContext, OrgOssPdfreporterEngineBaseJRVirtualPrintPage *page) {
  J2OBJC_NEW_IMPL(OrgOssPdfreporterEngineBaseVirtualizableElementList, initWithOrgOssPdfreporterEngineFillJRVirtualizationContext_withOrgOssPdfreporterEngineBaseJRVirtualPrintPage_, virtualizationContext, page)
}

OrgOssPdfreporterEngineBaseVirtualizableElementList *create_OrgOssPdfreporterEngineBaseVirtualizableElementList_initWithOrgOssPdfreporterEngineFillJRVirtualizationContext_withOrgOssPdfreporterEngineBaseJRVirtualPrintPage_(OrgOssPdfreporterEngineFillJRVirtualizationContext *virtualizationContext, OrgOssPdfreporterEngineBaseJRVirtualPrintPage *page) {
  J2OBJC_CREATE_IMPL(OrgOssPdfreporterEngineBaseVirtualizableElementList, initWithOrgOssPdfreporterEngineFillJRVirtualizationContext_withOrgOssPdfreporterEngineBaseJRVirtualPrintPage_, virtualizationContext, page)
}

void OrgOssPdfreporterEngineBaseVirtualizableElementList_initStoreWithOrgOssPdfreporterEngineBaseJRVirtualPrintPage_(OrgOssPdfreporterEngineBaseVirtualizableElementList *self, OrgOssPdfreporterEngineBaseJRVirtualPrintPage *page) {
  self->store_ = new_OrgOssPdfreporterEngineBaseElementsBlock_initWithOrgOssPdfreporterEngineFillJRVirtualizationContext_withOrgOssPdfreporterEngineBaseJRVirtualPrintPage_(self->virtualizationContext_, page);
}

void OrgOssPdfreporterEngineBaseVirtualizableElementList_cacheInContextWithOrgOssPdfreporterEngineJRPrintElement_(OrgOssPdfreporterEngineBaseVirtualizableElementList *self, id<OrgOssPdfreporterEngineJRPrintElement> element) {
  [((OrgOssPdfreporterEngineFillJRVirtualizationContext *) nil_chk(self->virtualizationContext_)) cacheTemplateWithOrgOssPdfreporterEngineJRPrintElement:element];
}

void OrgOssPdfreporterEngineBaseVirtualizableElementList_createBlockList(OrgOssPdfreporterEngineBaseVirtualizableElementList *self) {
  OrgOssPdfreporterEngineBaseElementsBlockList *blockList = new_OrgOssPdfreporterEngineBaseElementsBlockList_initWithOrgOssPdfreporterEngineBaseElementsBlock_((OrgOssPdfreporterEngineBaseElementsBlock *) cast_chk(self->store_, [OrgOssPdfreporterEngineBaseElementsBlock class]));
  [blockList addBlock];
  self->store_ = blockList;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgOssPdfreporterEngineBaseVirtualizableElementList)

J2OBJC_INITIALIZED_DEFN(OrgOssPdfreporterEngineBaseElementsBlock)

@implementation OrgOssPdfreporterEngineBaseElementsBlock

- (instancetype)initWithOrgOssPdfreporterEngineFillJRVirtualizationContext:(OrgOssPdfreporterEngineFillJRVirtualizationContext *)context
                         withOrgOssPdfreporterEngineBaseJRVirtualPrintPage:(OrgOssPdfreporterEngineBaseJRVirtualPrintPage *)page {
  OrgOssPdfreporterEngineBaseElementsBlock_initWithOrgOssPdfreporterEngineFillJRVirtualizationContext_withOrgOssPdfreporterEngineBaseJRVirtualPrintPage_(self, context, page);
  return self;
}

- (void)lockContext {
  OrgOssPdfreporterEngineBaseElementsBlock_lockContext(self);
}

- (void)unlockContext {
  OrgOssPdfreporterEngineBaseElementsBlock_unlockContext(self);
}

- (void)register__ {
  OrgOssPdfreporterEngineBaseElementsBlock_register__(self);
}

- (NSString *)makeUID {
  return OrgOssPdfreporterEngineBaseElementsBlock_makeUID(self);
}

- (jint)size {
  return JreLoadVolatileInt(&size_);
}

- (jboolean)isEmpty {
  return JreLoadVolatileInt(&size_) == 0;
}

- (id<OrgOssPdfreporterEngineJRPrintElement>)getWithInt:(jint)index {
  OrgOssPdfreporterEngineBaseElementsBlock_lockContext(self);
  @try {
    OrgOssPdfreporterEngineBaseElementsBlock_ensureDataAndTouch(self);
    return [((id<JavaUtilList>) nil_chk(elements_)) getWithInt:index];
  }
  @finally {
    OrgOssPdfreporterEngineBaseElementsBlock_unlockContext(self);
  }
}

- (jboolean)preAddWithOrgOssPdfreporterEngineJRPrintElement:(id<OrgOssPdfreporterEngineJRPrintElement>)element
                                                withBoolean:(jboolean)force {
  jboolean empty = elements_ != nil && [elements_ isEmpty];
  if (empty) {
    OrgOssPdfreporterEngineBaseElementsBlock_register__(self);
  }
  else {
    OrgOssPdfreporterEngineBaseElementsBlock_ensureDataAndTouch(self);
  }
  jint elementCount = OrgOssPdfreporterEngineUtilDeepPrintElementCounter_countWithOrgOssPdfreporterEngineJRPrintElement_(element);
  if (!force && ![((id<JavaUtilList>) nil_chk(elements_)) isEmpty]) {
    jint pageSize = [((OrgOssPdfreporterEngineFillJRVirtualizationContext *) nil_chk(context_)) getPageElementSize];
    if (pageSize > 0 && deepElementCount_ + elementCount > pageSize) {
      return false;
    }
  }
  deepElementCount_ += elementCount;
  return true;
}

- (jboolean)addWithOrgOssPdfreporterEngineJRPrintElement:(id<OrgOssPdfreporterEngineJRPrintElement>)element
                                             withBoolean:(jboolean)force {
  OrgOssPdfreporterEngineBaseElementsBlock_lockContext(self);
  @try {
    jboolean adding = [self preAddWithOrgOssPdfreporterEngineJRPrintElement:element withBoolean:force];
    if (adding) {
      [((id<JavaUtilList>) nil_chk(elements_)) addWithId:element];
      ++size_;
    }
    return adding;
  }
  @finally {
    OrgOssPdfreporterEngineBaseElementsBlock_unlockContext(self);
  }
}

- (jboolean)addWithOrgOssPdfreporterEngineJRPrintElement:(id<OrgOssPdfreporterEngineJRPrintElement>)element {
  return [self addWithOrgOssPdfreporterEngineJRPrintElement:element withBoolean:false];
}

- (jboolean)addWithInt:(jint)index
withOrgOssPdfreporterEngineJRPrintElement:(id<OrgOssPdfreporterEngineJRPrintElement>)element
           withBoolean:(jboolean)force {
  OrgOssPdfreporterEngineBaseElementsBlock_lockContext(self);
  @try {
    jboolean adding = [self preAddWithOrgOssPdfreporterEngineJRPrintElement:element withBoolean:force];
    if (adding) {
      [((id<JavaUtilList>) nil_chk(elements_)) addWithInt:index withId:element];
      ++size_;
    }
    return adding;
  }
  @finally {
    OrgOssPdfreporterEngineBaseElementsBlock_unlockContext(self);
  }
}

- (jboolean)addWithInt:(jint)index
withOrgOssPdfreporterEngineJRPrintElement:(id<OrgOssPdfreporterEngineJRPrintElement>)element {
  return [self addWithInt:index withOrgOssPdfreporterEngineJRPrintElement:element withBoolean:false];
}

- (id<OrgOssPdfreporterEngineJRPrintElement>)setWithInt:(jint)index
              withOrgOssPdfreporterEngineJRPrintElement:(id<OrgOssPdfreporterEngineJRPrintElement>)element {
  OrgOssPdfreporterEngineBaseElementsBlock_lockContext(self);
  @try {
    OrgOssPdfreporterEngineBaseElementsBlock_ensureDataAndTouch(self);
    id<OrgOssPdfreporterEngineJRPrintElement> oldElement = [((id<JavaUtilList>) nil_chk(elements_)) getWithInt:index];
    deepElementCount_ -= OrgOssPdfreporterEngineUtilDeepPrintElementCounter_countWithOrgOssPdfreporterEngineJRPrintElement_(oldElement);
    deepElementCount_ += OrgOssPdfreporterEngineUtilDeepPrintElementCounter_countWithOrgOssPdfreporterEngineJRPrintElement_(element);
    return [((id<JavaUtilList>) nil_chk(elements_)) setWithInt:index withId:element];
  }
  @finally {
    OrgOssPdfreporterEngineBaseElementsBlock_unlockContext(self);
  }
}

- (id<OrgOssPdfreporterEngineJRPrintElement>)removeWithInt:(jint)index {
  OrgOssPdfreporterEngineBaseElementsBlock_lockContext(self);
  @try {
    OrgOssPdfreporterEngineBaseElementsBlock_ensureDataAndTouch(self);
    id<OrgOssPdfreporterEngineJRPrintElement> element = [((id<JavaUtilList>) nil_chk(elements_)) removeWithInt:index];
    --size_;
    deepElementCount_ -= OrgOssPdfreporterEngineUtilDeepPrintElementCounter_countWithOrgOssPdfreporterEngineJRPrintElement_(element);
    if ([((id<JavaUtilList>) nil_chk(elements_)) isEmpty]) {
      OrgOssPdfreporterEngineBaseElementsBlock_deregister(self);
    }
    return element;
  }
  @finally {
    OrgOssPdfreporterEngineBaseElementsBlock_unlockContext(self);
  }
}

- (NSString *)getUID {
  return uid_;
}

- (void)ensureDataAndTouch {
  OrgOssPdfreporterEngineBaseElementsBlock_ensureDataAndTouch(self);
}

- (void)ensureVirtualData {
  OrgOssPdfreporterEngineBaseElementsBlock_lockContext(self);
  @try {
    if (elements_ == nil) {
      OrgOssPdfreporterEngineBaseElementsBlock_ensureData(self);
    }
  }
  @finally {
    OrgOssPdfreporterEngineBaseElementsBlock_unlockContext(self);
  }
}

- (void)ensureData {
  OrgOssPdfreporterEngineBaseElementsBlock_ensureData(self);
}

- (void)setVirtualDataWithId:(OrgOssPdfreporterEngineBaseVirtualElementsData *)virtualData {
  OrgOssPdfreporterEngineBaseElementsBlock_lockContext(self);
  @try {
    self->virtualData_ = virtualData;
    self->elements_ = [((OrgOssPdfreporterEngineBaseVirtualElementsData *) nil_chk(virtualData)) getElements];
  }
  @finally {
    OrgOssPdfreporterEngineBaseElementsBlock_unlockContext(self);
  }
}

- (OrgOssPdfreporterEngineBaseVirtualElementsData *)getVirtualData {
  return virtualData_;
}

- (void)removeVirtualData {
  OrgOssPdfreporterEngineBaseElementsBlock_lockContext(self);
  @try {
    virtualData_ = nil;
    elements_ = nil;
  }
  @finally {
    OrgOssPdfreporterEngineBaseElementsBlock_unlockContext(self);
  }
}

- (void)beforeExternalization {
  OrgOssPdfreporterEngineBaseElementsBlock_lockContext(self);
  @try {
    virtualData_ = new_OrgOssPdfreporterEngineBaseVirtualElementsData_initWithJavaUtilList_(elements_);
    [((OrgOssPdfreporterEngineFillJRVirtualizationContext *) nil_chk(context_)) beforeExternalizationWithOrgOssPdfreporterEngineJRVirtualizable:self];
  }
  @finally {
    OrgOssPdfreporterEngineBaseElementsBlock_unlockContext(self);
  }
}

- (void)afterExternalization {
  OrgOssPdfreporterEngineBaseElementsBlock_lockContext(self);
  @try {
    [((OrgOssPdfreporterEngineFillJRVirtualizationContext *) nil_chk(context_)) afterExternalizationWithOrgOssPdfreporterEngineJRVirtualizable:self];
  }
  @finally {
    OrgOssPdfreporterEngineBaseElementsBlock_unlockContext(self);
  }
}

- (void)afterInternalization {
  OrgOssPdfreporterEngineBaseElementsBlock_lockContext(self);
  @try {
    [((OrgOssPdfreporterEngineFillJRVirtualizationContext *) nil_chk(context_)) afterInternalizationWithOrgOssPdfreporterEngineJRVirtualizable:self];
    virtualData_ = nil;
  }
  @finally {
    OrgOssPdfreporterEngineBaseElementsBlock_unlockContext(self);
  }
}

- (OrgOssPdfreporterEngineFillJRVirtualizationContext *)getContext {
  return context_;
}

- (void)javaFinalize {
  [self dispose];
  [super javaFinalize];
}

- (void)dispose {
  OrgOssPdfreporterEngineBaseElementsBlock_lockContext(self);
  @try {
    if (elements_ == nil || ![elements_ isEmpty]) {
      OrgOssPdfreporterEngineBaseElementsBlock_deregister(self);
    }
  }
  @finally {
    OrgOssPdfreporterEngineBaseElementsBlock_unlockContext(self);
  }
}

- (void)deregister {
  OrgOssPdfreporterEngineBaseElementsBlock_deregister(self);
}

- (OrgOssPdfreporterEngineBaseJRVirtualPrintPage *)getPage {
  return page_;
}

- (void)dealloc {
  JreCheckFinalize(self, [OrgOssPdfreporterEngineBaseElementsBlock class]);
}

+ (void)initialize {
  if (self == [OrgOssPdfreporterEngineBaseElementsBlock class]) {
    OrgOssPdfreporterEngineBaseElementsBlock_uidCounter = new_JavaUtilConcurrentAtomicAtomicInteger_init();
    OrgOssPdfreporterEngineBaseElementsBlock_uidRandom = new_JavaUtilRandom_init();
    J2OBJC_SET_INITIALIZED(OrgOssPdfreporterEngineBaseElementsBlock)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithOrgOssPdfreporterEngineFillJRVirtualizationContext:withOrgOssPdfreporterEngineBaseJRVirtualPrintPage:", "ElementsBlock", NULL, 0x1, NULL, NULL },
    { "lockContext", NULL, "V", 0x2, NULL, NULL },
    { "unlockContext", NULL, "V", 0x2, NULL, NULL },
    { "register__", "register", "V", 0x2, NULL, NULL },
    { "makeUID", NULL, "Ljava.lang.String;", 0x2, NULL, NULL },
    { "size", NULL, "I", 0x1, NULL, NULL },
    { "isEmpty", NULL, "Z", 0x1, NULL, NULL },
    { "getWithInt:", "get", "Lorg.oss.pdfreporter.engine.JRPrintElement;", 0x1, NULL, NULL },
    { "preAddWithOrgOssPdfreporterEngineJRPrintElement:withBoolean:", "preAdd", "Z", 0x4, NULL, NULL },
    { "addWithOrgOssPdfreporterEngineJRPrintElement:withBoolean:", "add", "Z", 0x1, NULL, NULL },
    { "addWithOrgOssPdfreporterEngineJRPrintElement:", "add", "Z", 0x1, NULL, NULL },
    { "addWithInt:withOrgOssPdfreporterEngineJRPrintElement:withBoolean:", "add", "Z", 0x1, NULL, NULL },
    { "addWithInt:withOrgOssPdfreporterEngineJRPrintElement:", "add", "Z", 0x1, NULL, NULL },
    { "setWithInt:withOrgOssPdfreporterEngineJRPrintElement:", "set", "Lorg.oss.pdfreporter.engine.JRPrintElement;", 0x1, NULL, NULL },
    { "removeWithInt:", "remove", "Lorg.oss.pdfreporter.engine.JRPrintElement;", 0x1, NULL, NULL },
    { "getUID", NULL, "Ljava.lang.String;", 0x1, NULL, NULL },
    { "ensureDataAndTouch", NULL, "V", 0x2, NULL, NULL },
    { "ensureVirtualData", NULL, "V", 0x1, NULL, NULL },
    { "ensureData", NULL, "V", 0x2, NULL, NULL },
    { "setVirtualDataWithId:", "setVirtualData", "V", 0x1, NULL, NULL },
    { "getVirtualData", NULL, "Lorg.oss.pdfreporter.engine.base.VirtualElementsData;", 0x1, NULL, NULL },
    { "removeVirtualData", NULL, "V", 0x1, NULL, NULL },
    { "beforeExternalization", NULL, "V", 0x1, NULL, NULL },
    { "afterExternalization", NULL, "V", 0x1, NULL, NULL },
    { "afterInternalization", NULL, "V", 0x1, NULL, NULL },
    { "getContext", NULL, "Lorg.oss.pdfreporter.engine.fill.JRVirtualizationContext;", 0x1, NULL, NULL },
    { "javaFinalize", "finalize", "V", 0x4, "Ljava.lang.Throwable;", NULL },
    { "dispose", NULL, "V", 0x1, NULL, NULL },
    { "deregister", NULL, "V", 0x2, NULL, NULL },
    { "getPage", NULL, "Lorg.oss.pdfreporter.engine.base.JRVirtualPrintPage;", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "serialVersionUID", "serialVersionUID", 0x1a, "J", NULL, NULL, .constantValue.asLong = OrgOssPdfreporterEngineBaseElementsBlock_serialVersionUID },
    { "uidCounter", "uidCounter", 0x1a, "Ljava.util.concurrent.atomic.AtomicInteger;", &OrgOssPdfreporterEngineBaseElementsBlock_uidCounter, NULL, .constantValue.asLong = 0 },
    { "uidRandom", "uidRandom", 0x1a, "Ljava.util.Random;", &OrgOssPdfreporterEngineBaseElementsBlock_uidRandom, NULL, .constantValue.asLong = 0 },
    { "context_", NULL, 0x2, "Lorg.oss.pdfreporter.engine.fill.JRVirtualizationContext;", NULL, NULL, .constantValue.asLong = 0 },
    { "uid_", NULL, 0x2, "Ljava.lang.String;", NULL, NULL, .constantValue.asLong = 0 },
    { "elements_", NULL, 0x2, "Ljava.util.List;", NULL, "Ljava/util/List<Lorg/oss/pdfreporter/engine/JRPrintElement;>;", .constantValue.asLong = 0 },
    { "size_", NULL, 0xc2, "I", NULL, NULL, .constantValue.asLong = 0 },
    { "virtualData_", NULL, 0x82, "Lorg.oss.pdfreporter.engine.base.VirtualElementsData;", NULL, NULL, .constantValue.asLong = 0 },
    { "deepElementCount_", NULL, 0x82, "I", NULL, NULL, .constantValue.asLong = 0 },
    { "page_", NULL, 0x82, "Lorg.oss.pdfreporter.engine.base.JRVirtualPrintPage;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _OrgOssPdfreporterEngineBaseElementsBlock = { 2, "ElementsBlock", "org.oss.pdfreporter.engine.base", NULL, 0x0, 30, methods, 10, fields, 0, NULL, 0, NULL, NULL, "Ljava/lang/Object;Lorg/oss/pdfreporter/engine/JRVirtualizable<Lorg/oss/pdfreporter/engine/base/VirtualElementsData;>;Lorg/oss/pdfreporter/engine/base/ElementStore;Ljava/io/Serializable;" };
  return &_OrgOssPdfreporterEngineBaseElementsBlock;
}

@end

void OrgOssPdfreporterEngineBaseElementsBlock_initWithOrgOssPdfreporterEngineFillJRVirtualizationContext_withOrgOssPdfreporterEngineBaseJRVirtualPrintPage_(OrgOssPdfreporterEngineBaseElementsBlock *self, OrgOssPdfreporterEngineFillJRVirtualizationContext *context, OrgOssPdfreporterEngineBaseJRVirtualPrintPage *page) {
  NSObject_init(self);
  self->context_ = context;
  self->page_ = page;
  self->uid_ = OrgOssPdfreporterEngineBaseElementsBlock_makeUID(self);
  self->elements_ = new_JavaUtilArrayList_init();
  JreAssignVolatileInt(&self->size_, 0);
  self->deepElementCount_ = 0;
}

OrgOssPdfreporterEngineBaseElementsBlock *new_OrgOssPdfreporterEngineBaseElementsBlock_initWithOrgOssPdfreporterEngineFillJRVirtualizationContext_withOrgOssPdfreporterEngineBaseJRVirtualPrintPage_(OrgOssPdfreporterEngineFillJRVirtualizationContext *context, OrgOssPdfreporterEngineBaseJRVirtualPrintPage *page) {
  J2OBJC_NEW_IMPL(OrgOssPdfreporterEngineBaseElementsBlock, initWithOrgOssPdfreporterEngineFillJRVirtualizationContext_withOrgOssPdfreporterEngineBaseJRVirtualPrintPage_, context, page)
}

OrgOssPdfreporterEngineBaseElementsBlock *create_OrgOssPdfreporterEngineBaseElementsBlock_initWithOrgOssPdfreporterEngineFillJRVirtualizationContext_withOrgOssPdfreporterEngineBaseJRVirtualPrintPage_(OrgOssPdfreporterEngineFillJRVirtualizationContext *context, OrgOssPdfreporterEngineBaseJRVirtualPrintPage *page) {
  J2OBJC_CREATE_IMPL(OrgOssPdfreporterEngineBaseElementsBlock, initWithOrgOssPdfreporterEngineFillJRVirtualizationContext_withOrgOssPdfreporterEngineBaseJRVirtualPrintPage_, context, page)
}

void OrgOssPdfreporterEngineBaseElementsBlock_lockContext(OrgOssPdfreporterEngineBaseElementsBlock *self) {
  [((OrgOssPdfreporterEngineFillJRVirtualizationContext *) nil_chk(self->context_)) lock];
}

void OrgOssPdfreporterEngineBaseElementsBlock_unlockContext(OrgOssPdfreporterEngineBaseElementsBlock *self) {
  [((OrgOssPdfreporterEngineFillJRVirtualizationContext *) nil_chk(self->context_)) unlock];
}

void OrgOssPdfreporterEngineBaseElementsBlock_register__(OrgOssPdfreporterEngineBaseElementsBlock *self) {
  if ([((OrgOssPdfreporterEngineFillJRVirtualizationContext *) nil_chk(self->context_)) getVirtualizer] != nil) {
    [((id<OrgOssPdfreporterEngineJRVirtualizer>) nil_chk([((OrgOssPdfreporterEngineFillJRVirtualizationContext *) nil_chk(self->context_)) getVirtualizer])) registerObjectWithOrgOssPdfreporterEngineIJRVirtualizable:self];
  }
}

NSString *OrgOssPdfreporterEngineBaseElementsBlock_makeUID(OrgOssPdfreporterEngineBaseElementsBlock *self) {
  return JreStrcat("ICICICI", JavaLangSystem_identityHashCodeWithId_(self->context_), '_', JavaLangSystem_identityHashCodeWithId_(self), '_', [((JavaUtilConcurrentAtomicAtomicInteger *) nil_chk(OrgOssPdfreporterEngineBaseElementsBlock_uidCounter)) incrementAndGet], '_', [((JavaUtilRandom *) nil_chk(OrgOssPdfreporterEngineBaseElementsBlock_uidRandom)) nextInt]);
}

void OrgOssPdfreporterEngineBaseElementsBlock_ensureDataAndTouch(OrgOssPdfreporterEngineBaseElementsBlock *self) {
  if (self->elements_ == nil) {
    OrgOssPdfreporterEngineBaseElementsBlock_ensureData(self);
  }
  else {
    if ([((OrgOssPdfreporterEngineFillJRVirtualizationContext *) nil_chk(self->context_)) getVirtualizer] != nil) {
      [((id<OrgOssPdfreporterEngineJRVirtualizer>) nil_chk([((OrgOssPdfreporterEngineFillJRVirtualizationContext *) nil_chk(self->context_)) getVirtualizer])) touchWithOrgOssPdfreporterEngineIJRVirtualizable:self];
    }
  }
}

void OrgOssPdfreporterEngineBaseElementsBlock_ensureData(OrgOssPdfreporterEngineBaseElementsBlock *self) {
  if ([((OrgOssPdfreporterEngineFillJRVirtualizationContext *) nil_chk(self->context_)) getVirtualizer] != nil) {
    [((id<OrgOssPdfreporterEngineJRVirtualizer>) nil_chk([((OrgOssPdfreporterEngineFillJRVirtualizationContext *) nil_chk(self->context_)) getVirtualizer])) requestDataWithOrgOssPdfreporterEngineIJRVirtualizable:self];
  }
}

void OrgOssPdfreporterEngineBaseElementsBlock_deregister(OrgOssPdfreporterEngineBaseElementsBlock *self) {
  if ([((OrgOssPdfreporterEngineFillJRVirtualizationContext *) nil_chk(self->context_)) getVirtualizer] != nil) {
    [((id<OrgOssPdfreporterEngineJRVirtualizer>) nil_chk([((OrgOssPdfreporterEngineFillJRVirtualizationContext *) nil_chk(self->context_)) getVirtualizer])) deregisterObjectWithOrgOssPdfreporterEngineIJRVirtualizable:self];
  }
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgOssPdfreporterEngineBaseElementsBlock)

@implementation OrgOssPdfreporterEngineBaseElementsBlockList

- (instancetype)initWithOrgOssPdfreporterEngineBaseElementsBlock:(OrgOssPdfreporterEngineBaseElementsBlock *)block {
  OrgOssPdfreporterEngineBaseElementsBlockList_initWithOrgOssPdfreporterEngineBaseElementsBlock_(self, block);
  return self;
}

- (void)addBlock {
  [self incrementBlocks];
  OrgOssPdfreporterEngineBaseElementsBlock *block = new_OrgOssPdfreporterEngineBaseElementsBlock_initWithOrgOssPdfreporterEngineFillJRVirtualizationContext_withOrgOssPdfreporterEngineBaseJRVirtualPrintPage_([((OrgOssPdfreporterEngineBaseElementsBlock *) nil_chk(IOSObjectArray_Get(nil_chk(blocks_), 0))) getContext], [((OrgOssPdfreporterEngineBaseElementsBlock *) nil_chk(IOSObjectArray_Get(nil_chk(blocks_), 0))) getPage]);
  (void) IOSObjectArray_Set(nil_chk(blocks_), blockCount_, block);
  *IOSIntArray_GetRef(nil_chk(offsets_), blockCount_) = size_;
  ++blockCount_;
}

- (void)incrementBlocks {
  if (blockCount_ == ((IOSObjectArray *) nil_chk(blocks_))->size_) {
    jint newSize = JavaLangMath_minWithInt_withInt_((blockCount_ * 3) / 2 + 1, blockCount_ + OrgOssPdfreporterEngineBaseElementsBlockList_MAX_INCREMENT);
    IOSObjectArray *newBlocks = [IOSObjectArray newArrayWithLength:newSize type:OrgOssPdfreporterEngineBaseElementsBlock_class_()];
    JavaLangSystem_arraycopyWithId_withInt_withId_withInt_withInt_(blocks_, 0, newBlocks, 0, blockCount_);
    blocks_ = newBlocks;
    IOSIntArray *newOffsets = [IOSIntArray newArrayWithLength:newSize];
    JavaLangSystem_arraycopyWithId_withInt_withId_withInt_withInt_(offsets_, 0, newOffsets, 0, blockCount_);
    offsets_ = newOffsets;
  }
}

- (jint)size {
  return size_;
}

- (id<OrgOssPdfreporterEngineJRPrintElement>)getWithInt:(jint)index {
  jint blockIndex = [self blockIndexWithInt:index];
  return [((OrgOssPdfreporterEngineBaseElementsBlock *) nil_chk(IOSObjectArray_Get(nil_chk(blocks_), blockIndex))) getWithInt:index - IOSIntArray_Get(nil_chk(offsets_), blockIndex)];
}

- (jboolean)addWithOrgOssPdfreporterEngineJRPrintElement:(id<OrgOssPdfreporterEngineJRPrintElement>)element {
  if (![((OrgOssPdfreporterEngineBaseElementsBlock *) nil_chk(IOSObjectArray_Get(nil_chk(blocks_), blockCount_ - 1))) addWithOrgOssPdfreporterEngineJRPrintElement:element withBoolean:false]) {
    [self addBlock];
    [((OrgOssPdfreporterEngineBaseElementsBlock *) nil_chk(IOSObjectArray_Get(nil_chk(blocks_), blockCount_ - 1))) addWithOrgOssPdfreporterEngineJRPrintElement:element withBoolean:true];
  }
  ++size_;
  return true;
}

- (jboolean)addWithInt:(jint)index
withOrgOssPdfreporterEngineJRPrintElement:(id<OrgOssPdfreporterEngineJRPrintElement>)element {
  jint blockIndex = [self blockIndexWithInt:index];
  jboolean last = blockIndex == blockCount_ - 1;
  if (last) {
    if (![((OrgOssPdfreporterEngineBaseElementsBlock *) nil_chk(IOSObjectArray_Get(nil_chk(blocks_), blockIndex))) addWithInt:index - IOSIntArray_Get(nil_chk(offsets_), blockIndex) withOrgOssPdfreporterEngineJRPrintElement:element withBoolean:false]) {
      [self addBlock];
      blockIndex = blockCount_ - 1;
      [((OrgOssPdfreporterEngineBaseElementsBlock *) nil_chk(IOSObjectArray_Get(nil_chk(blocks_), blockIndex))) addWithInt:index - IOSIntArray_Get(nil_chk(offsets_), blockIndex) withOrgOssPdfreporterEngineJRPrintElement:element withBoolean:true];
    }
  }
  else {
    [((OrgOssPdfreporterEngineBaseElementsBlock *) nil_chk(IOSObjectArray_Get(nil_chk(blocks_), blockIndex))) addWithInt:index - IOSIntArray_Get(nil_chk(offsets_), blockIndex) withOrgOssPdfreporterEngineJRPrintElement:element withBoolean:true];
    for (jint idx = blockIndex + 1; idx < blockCount_; ++idx) {
      ++(*IOSIntArray_GetRef(nil_chk(offsets_), blockIndex));
    }
  }
  ++size_;
  return true;
}

- (id<OrgOssPdfreporterEngineJRPrintElement>)setWithInt:(jint)index
              withOrgOssPdfreporterEngineJRPrintElement:(id<OrgOssPdfreporterEngineJRPrintElement>)element {
  jint blockIndex = [self blockIndexWithInt:index];
  return [((OrgOssPdfreporterEngineBaseElementsBlock *) nil_chk(IOSObjectArray_Get(nil_chk(blocks_), blockIndex))) setWithInt:index - IOSIntArray_Get(nil_chk(offsets_), blockIndex) withOrgOssPdfreporterEngineJRPrintElement:element];
}

- (id<OrgOssPdfreporterEngineJRPrintElement>)removeWithInt:(jint)index {
  jint blockIndex = [self blockIndexWithInt:index];
  OrgOssPdfreporterEngineBaseElementsBlock *block = IOSObjectArray_Get(nil_chk(blocks_), blockIndex);
  id<OrgOssPdfreporterEngineJRPrintElement> element = [((OrgOssPdfreporterEngineBaseElementsBlock *) nil_chk(block)) removeWithInt:index - IOSIntArray_Get(nil_chk(offsets_), blockIndex)];
  if (blockIndex + 1 < blockCount_) {
    for (jint idx = blockIndex + 1; idx < blockCount_; ++idx) {
      --(*IOSIntArray_GetRef(nil_chk(offsets_), idx));
    }
  }
  if (blockCount_ > 1 && [block isEmpty]) {
    for (jint idx = blockIndex + 1; idx < blockCount_; ++idx) {
      (void) IOSObjectArray_Set(nil_chk(blocks_), idx - 1, IOSObjectArray_Get(blocks_, idx));
      *IOSIntArray_GetRef(nil_chk(offsets_), idx - 1) = IOSIntArray_Get(offsets_, idx);
    }
    --blockCount_;
    (void) IOSObjectArray_Set(nil_chk(blocks_), blockCount_, nil);
    *IOSIntArray_GetRef(nil_chk(offsets_), blockCount_) = 0;
  }
  --size_;
  return element;
}

- (void)dispose {
  for (jint idx = 0; idx < blockCount_; ++idx) {
    [((OrgOssPdfreporterEngineBaseElementsBlock *) nil_chk(IOSObjectArray_Get(nil_chk(blocks_), idx))) dispose];
  }
}

- (jint)blockIndexWithInt:(jint)index {
  if (index < 0) {
    @throw new_JavaLangIndexOutOfBoundsException_initWithNSString_(JreStrcat("$I", @"index: ", index));
  }
  if (lastIndex_ >= 0 && lastIndex_ < blockCount_) {
    if (index >= IOSIntArray_Get(nil_chk(offsets_), lastIndex_) && (lastIndex_ + 1 == blockCount_ || index < IOSIntArray_Get(offsets_, lastIndex_ + 1))) {
      return lastIndex_;
    }
  }
  jint blockIndex = JavaUtilArrays_binarySearchWithIntArray_withInt_withInt_withInt_(offsets_, 0, blockCount_, index);
  if (blockIndex < 0) {
    blockIndex = -blockIndex - 2;
  }
  lastIndex_ = blockIndex;
  return blockIndex;
}

- (OrgOssPdfreporterEngineBaseJRVirtualPrintPage *)getPage {
  return [((OrgOssPdfreporterEngineBaseElementsBlock *) nil_chk(IOSObjectArray_Get(nil_chk(blocks_), 0))) getPage];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithOrgOssPdfreporterEngineBaseElementsBlock:", "ElementsBlockList", NULL, 0x1, NULL, NULL },
    { "addBlock", NULL, "V", 0x4, NULL, NULL },
    { "incrementBlocks", NULL, "V", 0x4, NULL, NULL },
    { "size", NULL, "I", 0x1, NULL, NULL },
    { "getWithInt:", "get", "Lorg.oss.pdfreporter.engine.JRPrintElement;", 0x1, NULL, NULL },
    { "addWithOrgOssPdfreporterEngineJRPrintElement:", "add", "Z", 0x1, NULL, NULL },
    { "addWithInt:withOrgOssPdfreporterEngineJRPrintElement:", "add", "Z", 0x1, NULL, NULL },
    { "setWithInt:withOrgOssPdfreporterEngineJRPrintElement:", "set", "Lorg.oss.pdfreporter.engine.JRPrintElement;", 0x1, NULL, NULL },
    { "removeWithInt:", "remove", "Lorg.oss.pdfreporter.engine.JRPrintElement;", 0x1, NULL, NULL },
    { "dispose", NULL, "V", 0x1, NULL, NULL },
    { "blockIndexWithInt:", "blockIndex", "I", 0x4, NULL, NULL },
    { "getPage", NULL, "Lorg.oss.pdfreporter.engine.base.JRVirtualPrintPage;", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "serialVersionUID", "serialVersionUID", 0x1a, "J", NULL, NULL, .constantValue.asLong = OrgOssPdfreporterEngineBaseElementsBlockList_serialVersionUID },
    { "INITIAL_SIZE", "INITIAL_SIZE", 0x1a, "I", NULL, NULL, .constantValue.asInt = OrgOssPdfreporterEngineBaseElementsBlockList_INITIAL_SIZE },
    { "MAX_INCREMENT", "MAX_INCREMENT", 0x1a, "I", NULL, NULL, .constantValue.asInt = OrgOssPdfreporterEngineBaseElementsBlockList_MAX_INCREMENT },
    { "blockCount_", NULL, 0x2, "I", NULL, NULL, .constantValue.asLong = 0 },
    { "offsets_", NULL, 0x2, "[I", NULL, NULL, .constantValue.asLong = 0 },
    { "blocks_", NULL, 0x2, "[Lorg.oss.pdfreporter.engine.base.ElementsBlock;", NULL, NULL, .constantValue.asLong = 0 },
    { "size_", NULL, 0x2, "I", NULL, NULL, .constantValue.asLong = 0 },
    { "lastIndex_", NULL, 0x82, "I", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _OrgOssPdfreporterEngineBaseElementsBlockList = { 2, "ElementsBlockList", "org.oss.pdfreporter.engine.base", NULL, 0x0, 12, methods, 8, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgOssPdfreporterEngineBaseElementsBlockList;
}

@end

void OrgOssPdfreporterEngineBaseElementsBlockList_initWithOrgOssPdfreporterEngineBaseElementsBlock_(OrgOssPdfreporterEngineBaseElementsBlockList *self, OrgOssPdfreporterEngineBaseElementsBlock *block) {
  NSObject_init(self);
  self->lastIndex_ = -1;
  self->blocks_ = [IOSObjectArray newArrayWithLength:OrgOssPdfreporterEngineBaseElementsBlockList_INITIAL_SIZE type:OrgOssPdfreporterEngineBaseElementsBlock_class_()];
  self->offsets_ = [IOSIntArray newArrayWithLength:OrgOssPdfreporterEngineBaseElementsBlockList_INITIAL_SIZE];
  self->blockCount_ = 1;
  (void) IOSObjectArray_Set(self->blocks_, 0, block);
  *IOSIntArray_GetRef(self->offsets_, 0) = 0;
  self->size_ = [((OrgOssPdfreporterEngineBaseElementsBlock *) nil_chk(block)) size];
}

OrgOssPdfreporterEngineBaseElementsBlockList *new_OrgOssPdfreporterEngineBaseElementsBlockList_initWithOrgOssPdfreporterEngineBaseElementsBlock_(OrgOssPdfreporterEngineBaseElementsBlock *block) {
  J2OBJC_NEW_IMPL(OrgOssPdfreporterEngineBaseElementsBlockList, initWithOrgOssPdfreporterEngineBaseElementsBlock_, block)
}

OrgOssPdfreporterEngineBaseElementsBlockList *create_OrgOssPdfreporterEngineBaseElementsBlockList_initWithOrgOssPdfreporterEngineBaseElementsBlock_(OrgOssPdfreporterEngineBaseElementsBlock *block) {
  J2OBJC_CREATE_IMPL(OrgOssPdfreporterEngineBaseElementsBlockList, initWithOrgOssPdfreporterEngineBaseElementsBlock_, block)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgOssPdfreporterEngineBaseElementsBlockList)
