//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../pdfreporter-core/src/org/oss/pdfreporter/compilers/jeval/functions/NullValue.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgOssPdfreporterCompilersJevalFunctionsNullValue")
#ifdef RESTRICT_OrgOssPdfreporterCompilersJevalFunctionsNullValue
#define INCLUDE_ALL_OrgOssPdfreporterCompilersJevalFunctionsNullValue 0
#else
#define INCLUDE_ALL_OrgOssPdfreporterCompilersJevalFunctionsNullValue 1
#endif
#undef RESTRICT_OrgOssPdfreporterCompilersJevalFunctionsNullValue

#if !defined (OrgOssPdfreporterCompilersJevalFunctionsNullValue_) && (INCLUDE_ALL_OrgOssPdfreporterCompilersJevalFunctionsNullValue || defined(INCLUDE_OrgOssPdfreporterCompilersJevalFunctionsNullValue))
#define OrgOssPdfreporterCompilersJevalFunctionsNullValue_

#define RESTRICT_OrgOssPdfreporterUsesNetSourceforgeJevalFunctionFunction 1
#define INCLUDE_OrgOssPdfreporterUsesNetSourceforgeJevalFunctionFunction 1
#include "org/oss/pdfreporter/uses/net/sourceforge/jeval/function/Function.h"

@class OrgOssPdfreporterUsesNetSourceforgeJevalEvaluator;
@class OrgOssPdfreporterUsesNetSourceforgeJevalFunctionFunctionResult;

@interface OrgOssPdfreporterCompilersJevalFunctionsNullValue : NSObject < OrgOssPdfreporterUsesNetSourceforgeJevalFunctionFunction >

#pragma mark Public

- (instancetype)init;

- (OrgOssPdfreporterUsesNetSourceforgeJevalFunctionFunctionResult *)executeWithOrgOssPdfreporterUsesNetSourceforgeJevalEvaluator:(OrgOssPdfreporterUsesNetSourceforgeJevalEvaluator *)evaluator
                                                                                                                    withNSString:(NSString *)arguments;

- (NSString *)getName;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgOssPdfreporterCompilersJevalFunctionsNullValue)

FOUNDATION_EXPORT void OrgOssPdfreporterCompilersJevalFunctionsNullValue_init(OrgOssPdfreporterCompilersJevalFunctionsNullValue *self);

FOUNDATION_EXPORT OrgOssPdfreporterCompilersJevalFunctionsNullValue *new_OrgOssPdfreporterCompilersJevalFunctionsNullValue_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgOssPdfreporterCompilersJevalFunctionsNullValue *create_OrgOssPdfreporterCompilersJevalFunctionsNullValue_init();

J2OBJC_TYPE_LITERAL_HEADER(OrgOssPdfreporterCompilersJevalFunctionsNullValue)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgOssPdfreporterCompilersJevalFunctionsNullValue")
