//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../pdfreporter-extensions/src/org/oss/pdfreporter/uses/org/oss/jshuntingyard/evaluator/NullArgument.java
//

#include "J2ObjC_source.h"
#include "org/oss/pdfreporter/uses/org/oss/jshuntingyard/evaluator/AbstractFunctionElementArgument.h"
#include "org/oss/pdfreporter/uses/org/oss/jshuntingyard/evaluator/FunctionElementArgument.h"
#include "org/oss/pdfreporter/uses/org/oss/jshuntingyard/evaluator/NullArgument.h"

@implementation OrgOssPdfreporterUsesOrgOssJshuntingyardEvaluatorNullArgument

- (OrgOssPdfreporterUsesOrgOssJshuntingyardEvaluatorFunctionElementArgument_ArgumentType *)getType {
  return JreLoadEnum(OrgOssPdfreporterUsesOrgOssJshuntingyardEvaluatorFunctionElementArgument_ArgumentType, NULL);
}

- (id)getValue {
  return nil;
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgOssPdfreporterUsesOrgOssJshuntingyardEvaluatorNullArgument_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getType", NULL, "Lorg.oss.pdfreporter.uses.org.oss.jshuntingyard.evaluator.FunctionElementArgument$ArgumentType;", 0x1, NULL, NULL },
    { "getValue", NULL, "Ljava.lang.Object;", 0x1, NULL, NULL },
    { "init", "NullArgument", NULL, 0x1, NULL, NULL },
  };
  static const char *superclass_type_args[] = {"Ljava.lang.Object;"};
  static const J2ObjcClassInfo _OrgOssPdfreporterUsesOrgOssJshuntingyardEvaluatorNullArgument = { 2, "NullArgument", "org.oss.pdfreporter.uses.org.oss.jshuntingyard.evaluator", NULL, 0x1, 3, methods, 0, NULL, 1, superclass_type_args, 0, NULL, NULL, "Lorg/oss/pdfreporter/uses/org/oss/jshuntingyard/evaluator/AbstractFunctionElementArgument<Ljava/lang/Object;>;" };
  return &_OrgOssPdfreporterUsesOrgOssJshuntingyardEvaluatorNullArgument;
}

@end

void OrgOssPdfreporterUsesOrgOssJshuntingyardEvaluatorNullArgument_init(OrgOssPdfreporterUsesOrgOssJshuntingyardEvaluatorNullArgument *self) {
  OrgOssPdfreporterUsesOrgOssJshuntingyardEvaluatorAbstractFunctionElementArgument_init(self);
}

OrgOssPdfreporterUsesOrgOssJshuntingyardEvaluatorNullArgument *new_OrgOssPdfreporterUsesOrgOssJshuntingyardEvaluatorNullArgument_init() {
  J2OBJC_NEW_IMPL(OrgOssPdfreporterUsesOrgOssJshuntingyardEvaluatorNullArgument, init)
}

OrgOssPdfreporterUsesOrgOssJshuntingyardEvaluatorNullArgument *create_OrgOssPdfreporterUsesOrgOssJshuntingyardEvaluatorNullArgument_init() {
  J2OBJC_CREATE_IMPL(OrgOssPdfreporterUsesOrgOssJshuntingyardEvaluatorNullArgument, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgOssPdfreporterUsesOrgOssJshuntingyardEvaluatorNullArgument)
