//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../pdfreporter-core/src/org/oss/pdfreporter/extensions/ExtensionsRegistry.java
//

#include "J2ObjC_source.h"
#include "org/oss/pdfreporter/extensions/ExtensionsRegistry.h"

@interface OrgOssPdfreporterExtensionsExtensionsRegistry : NSObject

@end

@implementation OrgOssPdfreporterExtensionsExtensionsRegistry

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getExtensionsWithIOSClass:", "getExtensions", "Ljava.util.List;", 0x401, NULL, "<T:Ljava/lang/Object;>(Ljava/lang/Class<TT;>;)Ljava/util/List<TT;>;" },
  };
  static const J2ObjcClassInfo _OrgOssPdfreporterExtensionsExtensionsRegistry = { 2, "ExtensionsRegistry", "org.oss.pdfreporter.extensions", NULL, 0x609, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgOssPdfreporterExtensionsExtensionsRegistry;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgOssPdfreporterExtensionsExtensionsRegistry)
