//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../pdfreporter-core/src/org/oss/pdfreporter/engine/fill/JRFloatIncrementerFactory.java
//

#include "J2ObjC_source.h"
#include "java/lang/Float.h"
#include "java/lang/Math.h"
#include "org/oss/pdfreporter/engine/fill/AbstractValueProvider.h"
#include "org/oss/pdfreporter/engine/fill/DistinctCountHolder.h"
#include "org/oss/pdfreporter/engine/fill/JRAbstractExtendedIncrementer.h"
#include "org/oss/pdfreporter/engine/fill/JRAbstractExtendedIncrementerFactory.h"
#include "org/oss/pdfreporter/engine/fill/JRCalculable.h"
#include "org/oss/pdfreporter/engine/fill/JRComparableIncrementerFactory.h"
#include "org/oss/pdfreporter/engine/fill/JRDefaultIncrementerFactory.h"
#include "org/oss/pdfreporter/engine/fill/JRExtendedIncrementer.h"
#include "org/oss/pdfreporter/engine/fill/JRFloatIncrementerFactory.h"
#include "org/oss/pdfreporter/engine/type/CalculationEnum.h"

inline OrgOssPdfreporterEngineFillJRFloatIncrementerFactory *OrgOssPdfreporterEngineFillJRFloatIncrementerFactory_get_mainInstance();
inline OrgOssPdfreporterEngineFillJRFloatIncrementerFactory *OrgOssPdfreporterEngineFillJRFloatIncrementerFactory_set_mainInstance(OrgOssPdfreporterEngineFillJRFloatIncrementerFactory *value);
static OrgOssPdfreporterEngineFillJRFloatIncrementerFactory *OrgOssPdfreporterEngineFillJRFloatIncrementerFactory_mainInstance;
J2OBJC_STATIC_FIELD_OBJ(OrgOssPdfreporterEngineFillJRFloatIncrementerFactory, mainInstance, OrgOssPdfreporterEngineFillJRFloatIncrementerFactory *)

@interface OrgOssPdfreporterEngineFillJRFloatCountIncrementer ()

- (instancetype)init;

@end

inline OrgOssPdfreporterEngineFillJRFloatCountIncrementer *OrgOssPdfreporterEngineFillJRFloatCountIncrementer_get_mainInstance();
inline OrgOssPdfreporterEngineFillJRFloatCountIncrementer *OrgOssPdfreporterEngineFillJRFloatCountIncrementer_set_mainInstance(OrgOssPdfreporterEngineFillJRFloatCountIncrementer *value);
static OrgOssPdfreporterEngineFillJRFloatCountIncrementer *OrgOssPdfreporterEngineFillJRFloatCountIncrementer_mainInstance;
J2OBJC_STATIC_FIELD_OBJ(OrgOssPdfreporterEngineFillJRFloatCountIncrementer, mainInstance, OrgOssPdfreporterEngineFillJRFloatCountIncrementer *)

__attribute__((unused)) static void OrgOssPdfreporterEngineFillJRFloatCountIncrementer_init(OrgOssPdfreporterEngineFillJRFloatCountIncrementer *self);

__attribute__((unused)) static OrgOssPdfreporterEngineFillJRFloatCountIncrementer *new_OrgOssPdfreporterEngineFillJRFloatCountIncrementer_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static OrgOssPdfreporterEngineFillJRFloatCountIncrementer *create_OrgOssPdfreporterEngineFillJRFloatCountIncrementer_init();

@interface OrgOssPdfreporterEngineFillJRFloatDistinctCountIncrementer ()

- (instancetype)init;

@end

inline OrgOssPdfreporterEngineFillJRFloatDistinctCountIncrementer *OrgOssPdfreporterEngineFillJRFloatDistinctCountIncrementer_get_mainInstance();
inline OrgOssPdfreporterEngineFillJRFloatDistinctCountIncrementer *OrgOssPdfreporterEngineFillJRFloatDistinctCountIncrementer_set_mainInstance(OrgOssPdfreporterEngineFillJRFloatDistinctCountIncrementer *value);
static OrgOssPdfreporterEngineFillJRFloatDistinctCountIncrementer *OrgOssPdfreporterEngineFillJRFloatDistinctCountIncrementer_mainInstance;
J2OBJC_STATIC_FIELD_OBJ(OrgOssPdfreporterEngineFillJRFloatDistinctCountIncrementer, mainInstance, OrgOssPdfreporterEngineFillJRFloatDistinctCountIncrementer *)

__attribute__((unused)) static void OrgOssPdfreporterEngineFillJRFloatDistinctCountIncrementer_init(OrgOssPdfreporterEngineFillJRFloatDistinctCountIncrementer *self);

__attribute__((unused)) static OrgOssPdfreporterEngineFillJRFloatDistinctCountIncrementer *new_OrgOssPdfreporterEngineFillJRFloatDistinctCountIncrementer_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static OrgOssPdfreporterEngineFillJRFloatDistinctCountIncrementer *create_OrgOssPdfreporterEngineFillJRFloatDistinctCountIncrementer_init();

@interface OrgOssPdfreporterEngineFillJRFloatSumIncrementer ()

- (instancetype)init;

@end

inline OrgOssPdfreporterEngineFillJRFloatSumIncrementer *OrgOssPdfreporterEngineFillJRFloatSumIncrementer_get_mainInstance();
inline OrgOssPdfreporterEngineFillJRFloatSumIncrementer *OrgOssPdfreporterEngineFillJRFloatSumIncrementer_set_mainInstance(OrgOssPdfreporterEngineFillJRFloatSumIncrementer *value);
static OrgOssPdfreporterEngineFillJRFloatSumIncrementer *OrgOssPdfreporterEngineFillJRFloatSumIncrementer_mainInstance;
J2OBJC_STATIC_FIELD_OBJ(OrgOssPdfreporterEngineFillJRFloatSumIncrementer, mainInstance, OrgOssPdfreporterEngineFillJRFloatSumIncrementer *)

__attribute__((unused)) static void OrgOssPdfreporterEngineFillJRFloatSumIncrementer_init(OrgOssPdfreporterEngineFillJRFloatSumIncrementer *self);

__attribute__((unused)) static OrgOssPdfreporterEngineFillJRFloatSumIncrementer *new_OrgOssPdfreporterEngineFillJRFloatSumIncrementer_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static OrgOssPdfreporterEngineFillJRFloatSumIncrementer *create_OrgOssPdfreporterEngineFillJRFloatSumIncrementer_init();

@interface OrgOssPdfreporterEngineFillJRFloatAverageIncrementer ()

- (instancetype)init;

@end

inline OrgOssPdfreporterEngineFillJRFloatAverageIncrementer *OrgOssPdfreporterEngineFillJRFloatAverageIncrementer_get_mainInstance();
inline OrgOssPdfreporterEngineFillJRFloatAverageIncrementer *OrgOssPdfreporterEngineFillJRFloatAverageIncrementer_set_mainInstance(OrgOssPdfreporterEngineFillJRFloatAverageIncrementer *value);
static OrgOssPdfreporterEngineFillJRFloatAverageIncrementer *OrgOssPdfreporterEngineFillJRFloatAverageIncrementer_mainInstance;
J2OBJC_STATIC_FIELD_OBJ(OrgOssPdfreporterEngineFillJRFloatAverageIncrementer, mainInstance, OrgOssPdfreporterEngineFillJRFloatAverageIncrementer *)

__attribute__((unused)) static void OrgOssPdfreporterEngineFillJRFloatAverageIncrementer_init(OrgOssPdfreporterEngineFillJRFloatAverageIncrementer *self);

__attribute__((unused)) static OrgOssPdfreporterEngineFillJRFloatAverageIncrementer *new_OrgOssPdfreporterEngineFillJRFloatAverageIncrementer_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static OrgOssPdfreporterEngineFillJRFloatAverageIncrementer *create_OrgOssPdfreporterEngineFillJRFloatAverageIncrementer_init();

@interface OrgOssPdfreporterEngineFillJRFloatStandardDeviationIncrementer ()

- (instancetype)init;

@end

inline OrgOssPdfreporterEngineFillJRFloatStandardDeviationIncrementer *OrgOssPdfreporterEngineFillJRFloatStandardDeviationIncrementer_get_mainInstance();
inline OrgOssPdfreporterEngineFillJRFloatStandardDeviationIncrementer *OrgOssPdfreporterEngineFillJRFloatStandardDeviationIncrementer_set_mainInstance(OrgOssPdfreporterEngineFillJRFloatStandardDeviationIncrementer *value);
static OrgOssPdfreporterEngineFillJRFloatStandardDeviationIncrementer *OrgOssPdfreporterEngineFillJRFloatStandardDeviationIncrementer_mainInstance;
J2OBJC_STATIC_FIELD_OBJ(OrgOssPdfreporterEngineFillJRFloatStandardDeviationIncrementer, mainInstance, OrgOssPdfreporterEngineFillJRFloatStandardDeviationIncrementer *)

__attribute__((unused)) static void OrgOssPdfreporterEngineFillJRFloatStandardDeviationIncrementer_init(OrgOssPdfreporterEngineFillJRFloatStandardDeviationIncrementer *self);

__attribute__((unused)) static OrgOssPdfreporterEngineFillJRFloatStandardDeviationIncrementer *new_OrgOssPdfreporterEngineFillJRFloatStandardDeviationIncrementer_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static OrgOssPdfreporterEngineFillJRFloatStandardDeviationIncrementer *create_OrgOssPdfreporterEngineFillJRFloatStandardDeviationIncrementer_init();

@interface OrgOssPdfreporterEngineFillJRFloatVarianceIncrementer ()

- (instancetype)init;

@end

inline OrgOssPdfreporterEngineFillJRFloatVarianceIncrementer *OrgOssPdfreporterEngineFillJRFloatVarianceIncrementer_get_mainInstance();
inline OrgOssPdfreporterEngineFillJRFloatVarianceIncrementer *OrgOssPdfreporterEngineFillJRFloatVarianceIncrementer_set_mainInstance(OrgOssPdfreporterEngineFillJRFloatVarianceIncrementer *value);
static OrgOssPdfreporterEngineFillJRFloatVarianceIncrementer *OrgOssPdfreporterEngineFillJRFloatVarianceIncrementer_mainInstance;
J2OBJC_STATIC_FIELD_OBJ(OrgOssPdfreporterEngineFillJRFloatVarianceIncrementer, mainInstance, OrgOssPdfreporterEngineFillJRFloatVarianceIncrementer *)

__attribute__((unused)) static void OrgOssPdfreporterEngineFillJRFloatVarianceIncrementer_init(OrgOssPdfreporterEngineFillJRFloatVarianceIncrementer *self);

__attribute__((unused)) static OrgOssPdfreporterEngineFillJRFloatVarianceIncrementer *new_OrgOssPdfreporterEngineFillJRFloatVarianceIncrementer_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static OrgOssPdfreporterEngineFillJRFloatVarianceIncrementer *create_OrgOssPdfreporterEngineFillJRFloatVarianceIncrementer_init();

J2OBJC_INITIALIZED_DEFN(OrgOssPdfreporterEngineFillJRFloatIncrementerFactory)

JavaLangFloat *OrgOssPdfreporterEngineFillJRFloatIncrementerFactory_ZERO;

@implementation OrgOssPdfreporterEngineFillJRFloatIncrementerFactory

+ (JavaLangFloat *)ZERO {
  return OrgOssPdfreporterEngineFillJRFloatIncrementerFactory_ZERO;
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgOssPdfreporterEngineFillJRFloatIncrementerFactory_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (OrgOssPdfreporterEngineFillJRFloatIncrementerFactory *)getInstance {
  return OrgOssPdfreporterEngineFillJRFloatIncrementerFactory_getInstance();
}

- (id<OrgOssPdfreporterEngineFillJRExtendedIncrementer>)getExtendedIncrementerWithOrgOssPdfreporterEngineTypeCalculationEnum:(OrgOssPdfreporterEngineTypeCalculationEnum *)calculation {
  id<OrgOssPdfreporterEngineFillJRExtendedIncrementer> incrementer = nil;
  switch ([calculation ordinal]) {
    case OrgOssPdfreporterEngineTypeCalculationEnum_Enum_COUNT:
    {
      incrementer = OrgOssPdfreporterEngineFillJRFloatCountIncrementer_getInstance();
      break;
    }
    case OrgOssPdfreporterEngineTypeCalculationEnum_Enum_SUM:
    {
      incrementer = OrgOssPdfreporterEngineFillJRFloatSumIncrementer_getInstance();
      break;
    }
    case OrgOssPdfreporterEngineTypeCalculationEnum_Enum_AVERAGE:
    {
      incrementer = OrgOssPdfreporterEngineFillJRFloatAverageIncrementer_getInstance();
      break;
    }
    case OrgOssPdfreporterEngineTypeCalculationEnum_Enum_LOWEST:
    case OrgOssPdfreporterEngineTypeCalculationEnum_Enum_HIGHEST:
    {
      incrementer = [((OrgOssPdfreporterEngineFillJRComparableIncrementerFactory *) nil_chk(OrgOssPdfreporterEngineFillJRComparableIncrementerFactory_getInstance())) getExtendedIncrementerWithOrgOssPdfreporterEngineTypeCalculationEnum:calculation];
      break;
    }
    case OrgOssPdfreporterEngineTypeCalculationEnum_Enum_STANDARD_DEVIATION:
    {
      incrementer = OrgOssPdfreporterEngineFillJRFloatStandardDeviationIncrementer_getInstance();
      break;
    }
    case OrgOssPdfreporterEngineTypeCalculationEnum_Enum_VARIANCE:
    {
      incrementer = OrgOssPdfreporterEngineFillJRFloatVarianceIncrementer_getInstance();
      break;
    }
    case OrgOssPdfreporterEngineTypeCalculationEnum_Enum_DISTINCT_COUNT:
    {
      incrementer = OrgOssPdfreporterEngineFillJRFloatDistinctCountIncrementer_getInstance();
      break;
    }
    case OrgOssPdfreporterEngineTypeCalculationEnum_Enum_SYSTEM:
    case OrgOssPdfreporterEngineTypeCalculationEnum_Enum_NOTHING:
    case OrgOssPdfreporterEngineTypeCalculationEnum_Enum_FIRST:
    default:
    {
      incrementer = [((OrgOssPdfreporterEngineFillJRDefaultIncrementerFactory *) nil_chk(OrgOssPdfreporterEngineFillJRDefaultIncrementerFactory_getInstance())) getExtendedIncrementerWithOrgOssPdfreporterEngineTypeCalculationEnum:calculation];
      break;
    }
  }
  return incrementer;
}

+ (void)initialize {
  if (self == [OrgOssPdfreporterEngineFillJRFloatIncrementerFactory class]) {
    OrgOssPdfreporterEngineFillJRFloatIncrementerFactory_ZERO = new_JavaLangFloat_initWithFloat_(0);
    OrgOssPdfreporterEngineFillJRFloatIncrementerFactory_mainInstance = new_OrgOssPdfreporterEngineFillJRFloatIncrementerFactory_init();
    J2OBJC_SET_INITIALIZED(OrgOssPdfreporterEngineFillJRFloatIncrementerFactory)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "JRFloatIncrementerFactory", NULL, 0x1, NULL, NULL },
    { "getInstance", NULL, "Lorg.oss.pdfreporter.engine.fill.JRFloatIncrementerFactory;", 0x9, NULL, NULL },
    { "getExtendedIncrementerWithOrgOssPdfreporterEngineTypeCalculationEnum:", "getExtendedIncrementer", "Lorg.oss.pdfreporter.engine.fill.JRExtendedIncrementer;", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "ZERO", "ZERO", 0x1c, "Ljava.lang.Float;", &OrgOssPdfreporterEngineFillJRFloatIncrementerFactory_ZERO, NULL, .constantValue.asLong = 0 },
    { "mainInstance", "mainInstance", 0xa, "Lorg.oss.pdfreporter.engine.fill.JRFloatIncrementerFactory;", &OrgOssPdfreporterEngineFillJRFloatIncrementerFactory_mainInstance, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _OrgOssPdfreporterEngineFillJRFloatIncrementerFactory = { 2, "JRFloatIncrementerFactory", "org.oss.pdfreporter.engine.fill", NULL, 0x11, 3, methods, 2, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgOssPdfreporterEngineFillJRFloatIncrementerFactory;
}

@end

void OrgOssPdfreporterEngineFillJRFloatIncrementerFactory_init(OrgOssPdfreporterEngineFillJRFloatIncrementerFactory *self) {
  OrgOssPdfreporterEngineFillJRAbstractExtendedIncrementerFactory_init(self);
}

OrgOssPdfreporterEngineFillJRFloatIncrementerFactory *new_OrgOssPdfreporterEngineFillJRFloatIncrementerFactory_init() {
  J2OBJC_NEW_IMPL(OrgOssPdfreporterEngineFillJRFloatIncrementerFactory, init)
}

OrgOssPdfreporterEngineFillJRFloatIncrementerFactory *create_OrgOssPdfreporterEngineFillJRFloatIncrementerFactory_init() {
  J2OBJC_CREATE_IMPL(OrgOssPdfreporterEngineFillJRFloatIncrementerFactory, init)
}

OrgOssPdfreporterEngineFillJRFloatIncrementerFactory *OrgOssPdfreporterEngineFillJRFloatIncrementerFactory_getInstance() {
  OrgOssPdfreporterEngineFillJRFloatIncrementerFactory_initialize();
  return OrgOssPdfreporterEngineFillJRFloatIncrementerFactory_mainInstance;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgOssPdfreporterEngineFillJRFloatIncrementerFactory)

J2OBJC_INITIALIZED_DEFN(OrgOssPdfreporterEngineFillJRFloatCountIncrementer)

@implementation OrgOssPdfreporterEngineFillJRFloatCountIncrementer

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgOssPdfreporterEngineFillJRFloatCountIncrementer_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (OrgOssPdfreporterEngineFillJRFloatCountIncrementer *)getInstance {
  return OrgOssPdfreporterEngineFillJRFloatCountIncrementer_getInstance();
}

- (id)incrementWithOrgOssPdfreporterEngineFillJRCalculable:(id<OrgOssPdfreporterEngineFillJRCalculable>)variable
                                                    withId:(id)expressionValue
      withOrgOssPdfreporterEngineFillAbstractValueProvider:(OrgOssPdfreporterEngineFillAbstractValueProvider *)valueProvider {
  NSNumber *value = (NSNumber *) cast_chk([((id<OrgOssPdfreporterEngineFillJRCalculable>) nil_chk(variable)) getIncrementedValue], [NSNumber class]);
  if (value == nil || [variable isInitialized]) {
    value = JreLoadStatic(OrgOssPdfreporterEngineFillJRFloatIncrementerFactory, ZERO);
  }
  if (expressionValue == nil) {
    return value;
  }
  return new_JavaLangFloat_initWithFloat_([((NSNumber *) nil_chk(value)) floatValue] + 1);
}

- (id)combineWithOrgOssPdfreporterEngineFillJRCalculable:(id<OrgOssPdfreporterEngineFillJRCalculable>)calculable
             withOrgOssPdfreporterEngineFillJRCalculable:(id<OrgOssPdfreporterEngineFillJRCalculable>)calculableValue
    withOrgOssPdfreporterEngineFillAbstractValueProvider:(OrgOssPdfreporterEngineFillAbstractValueProvider *)valueProvider {
  NSNumber *value = (NSNumber *) cast_chk([((id<OrgOssPdfreporterEngineFillJRCalculable>) nil_chk(calculable)) getIncrementedValue], [NSNumber class]);
  NSNumber *combineValue = (NSNumber *) cast_chk([((id<OrgOssPdfreporterEngineFillJRCalculable>) nil_chk(calculableValue)) getValue], [NSNumber class]);
  if (value == nil || [calculable isInitialized]) {
    value = JreLoadStatic(OrgOssPdfreporterEngineFillJRFloatIncrementerFactory, ZERO);
  }
  if (combineValue == nil) {
    return value;
  }
  return new_JavaLangFloat_initWithFloat_([((NSNumber *) nil_chk(value)) floatValue] + [combineValue floatValue]);
}

- (id)initialValue {
  return JreLoadStatic(OrgOssPdfreporterEngineFillJRFloatIncrementerFactory, ZERO);
}

+ (void)initialize {
  if (self == [OrgOssPdfreporterEngineFillJRFloatCountIncrementer class]) {
    OrgOssPdfreporterEngineFillJRFloatCountIncrementer_mainInstance = new_OrgOssPdfreporterEngineFillJRFloatCountIncrementer_init();
    J2OBJC_SET_INITIALIZED(OrgOssPdfreporterEngineFillJRFloatCountIncrementer)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "JRFloatCountIncrementer", NULL, 0x2, NULL, NULL },
    { "getInstance", NULL, "Lorg.oss.pdfreporter.engine.fill.JRFloatCountIncrementer;", 0x9, NULL, NULL },
    { "incrementWithOrgOssPdfreporterEngineFillJRCalculable:withId:withOrgOssPdfreporterEngineFillAbstractValueProvider:", "increment", "Ljava.lang.Object;", 0x1, NULL, NULL },
    { "combineWithOrgOssPdfreporterEngineFillJRCalculable:withOrgOssPdfreporterEngineFillJRCalculable:withOrgOssPdfreporterEngineFillAbstractValueProvider:", "combine", "Ljava.lang.Object;", 0x1, NULL, NULL },
    { "initialValue", NULL, "Ljava.lang.Object;", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "mainInstance", "mainInstance", 0xa, "Lorg.oss.pdfreporter.engine.fill.JRFloatCountIncrementer;", &OrgOssPdfreporterEngineFillJRFloatCountIncrementer_mainInstance, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _OrgOssPdfreporterEngineFillJRFloatCountIncrementer = { 2, "JRFloatCountIncrementer", "org.oss.pdfreporter.engine.fill", NULL, 0x10, 5, methods, 1, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgOssPdfreporterEngineFillJRFloatCountIncrementer;
}

@end

void OrgOssPdfreporterEngineFillJRFloatCountIncrementer_init(OrgOssPdfreporterEngineFillJRFloatCountIncrementer *self) {
  OrgOssPdfreporterEngineFillJRAbstractExtendedIncrementer_init(self);
}

OrgOssPdfreporterEngineFillJRFloatCountIncrementer *new_OrgOssPdfreporterEngineFillJRFloatCountIncrementer_init() {
  J2OBJC_NEW_IMPL(OrgOssPdfreporterEngineFillJRFloatCountIncrementer, init)
}

OrgOssPdfreporterEngineFillJRFloatCountIncrementer *create_OrgOssPdfreporterEngineFillJRFloatCountIncrementer_init() {
  J2OBJC_CREATE_IMPL(OrgOssPdfreporterEngineFillJRFloatCountIncrementer, init)
}

OrgOssPdfreporterEngineFillJRFloatCountIncrementer *OrgOssPdfreporterEngineFillJRFloatCountIncrementer_getInstance() {
  OrgOssPdfreporterEngineFillJRFloatCountIncrementer_initialize();
  return OrgOssPdfreporterEngineFillJRFloatCountIncrementer_mainInstance;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgOssPdfreporterEngineFillJRFloatCountIncrementer)

J2OBJC_INITIALIZED_DEFN(OrgOssPdfreporterEngineFillJRFloatDistinctCountIncrementer)

@implementation OrgOssPdfreporterEngineFillJRFloatDistinctCountIncrementer

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgOssPdfreporterEngineFillJRFloatDistinctCountIncrementer_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (OrgOssPdfreporterEngineFillJRFloatDistinctCountIncrementer *)getInstance {
  return OrgOssPdfreporterEngineFillJRFloatDistinctCountIncrementer_getInstance();
}

- (id)incrementWithOrgOssPdfreporterEngineFillJRCalculable:(id<OrgOssPdfreporterEngineFillJRCalculable>)variable
                                                    withId:(id)expressionValue
      withOrgOssPdfreporterEngineFillAbstractValueProvider:(OrgOssPdfreporterEngineFillAbstractValueProvider *)valueProvider {
  OrgOssPdfreporterEngineFillDistinctCountHolder *holder = (OrgOssPdfreporterEngineFillDistinctCountHolder *) cast_chk([((OrgOssPdfreporterEngineFillAbstractValueProvider *) nil_chk(valueProvider)) getValueWithOrgOssPdfreporterEngineFillJRCalculable:[((id<OrgOssPdfreporterEngineFillJRCalculable>) nil_chk(variable)) getHelperVariableWithByte:OrgOssPdfreporterEngineFillJRCalculable_HELPER_COUNT]], [OrgOssPdfreporterEngineFillDistinctCountHolder class]);
  if ([variable isInitialized]) {
    [((OrgOssPdfreporterEngineFillDistinctCountHolder *) nil_chk(holder)) init__];
  }
  return new_JavaLangFloat_initWithFloat_([((OrgOssPdfreporterEngineFillDistinctCountHolder *) nil_chk(holder)) getCount]);
}

- (id)combineWithOrgOssPdfreporterEngineFillJRCalculable:(id<OrgOssPdfreporterEngineFillJRCalculable>)calculable
             withOrgOssPdfreporterEngineFillJRCalculable:(id<OrgOssPdfreporterEngineFillJRCalculable>)calculableValue
    withOrgOssPdfreporterEngineFillAbstractValueProvider:(OrgOssPdfreporterEngineFillAbstractValueProvider *)valueProvider {
  OrgOssPdfreporterEngineFillDistinctCountHolder *holder = (OrgOssPdfreporterEngineFillDistinctCountHolder *) cast_chk([((OrgOssPdfreporterEngineFillAbstractValueProvider *) nil_chk(valueProvider)) getValueWithOrgOssPdfreporterEngineFillJRCalculable:[((id<OrgOssPdfreporterEngineFillJRCalculable>) nil_chk(calculable)) getHelperVariableWithByte:OrgOssPdfreporterEngineFillJRCalculable_HELPER_COUNT]], [OrgOssPdfreporterEngineFillDistinctCountHolder class]);
  return new_JavaLangFloat_initWithFloat_([((OrgOssPdfreporterEngineFillDistinctCountHolder *) nil_chk(holder)) getCount]);
}

- (id)initialValue {
  return JreLoadStatic(OrgOssPdfreporterEngineFillJRFloatIncrementerFactory, ZERO);
}

+ (void)initialize {
  if (self == [OrgOssPdfreporterEngineFillJRFloatDistinctCountIncrementer class]) {
    OrgOssPdfreporterEngineFillJRFloatDistinctCountIncrementer_mainInstance = new_OrgOssPdfreporterEngineFillJRFloatDistinctCountIncrementer_init();
    J2OBJC_SET_INITIALIZED(OrgOssPdfreporterEngineFillJRFloatDistinctCountIncrementer)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "JRFloatDistinctCountIncrementer", NULL, 0x2, NULL, NULL },
    { "getInstance", NULL, "Lorg.oss.pdfreporter.engine.fill.JRFloatDistinctCountIncrementer;", 0x9, NULL, NULL },
    { "incrementWithOrgOssPdfreporterEngineFillJRCalculable:withId:withOrgOssPdfreporterEngineFillAbstractValueProvider:", "increment", "Ljava.lang.Object;", 0x1, NULL, NULL },
    { "combineWithOrgOssPdfreporterEngineFillJRCalculable:withOrgOssPdfreporterEngineFillJRCalculable:withOrgOssPdfreporterEngineFillAbstractValueProvider:", "combine", "Ljava.lang.Object;", 0x1, NULL, NULL },
    { "initialValue", NULL, "Ljava.lang.Object;", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "mainInstance", "mainInstance", 0xa, "Lorg.oss.pdfreporter.engine.fill.JRFloatDistinctCountIncrementer;", &OrgOssPdfreporterEngineFillJRFloatDistinctCountIncrementer_mainInstance, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _OrgOssPdfreporterEngineFillJRFloatDistinctCountIncrementer = { 2, "JRFloatDistinctCountIncrementer", "org.oss.pdfreporter.engine.fill", NULL, 0x10, 5, methods, 1, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgOssPdfreporterEngineFillJRFloatDistinctCountIncrementer;
}

@end

void OrgOssPdfreporterEngineFillJRFloatDistinctCountIncrementer_init(OrgOssPdfreporterEngineFillJRFloatDistinctCountIncrementer *self) {
  OrgOssPdfreporterEngineFillJRAbstractExtendedIncrementer_init(self);
}

OrgOssPdfreporterEngineFillJRFloatDistinctCountIncrementer *new_OrgOssPdfreporterEngineFillJRFloatDistinctCountIncrementer_init() {
  J2OBJC_NEW_IMPL(OrgOssPdfreporterEngineFillJRFloatDistinctCountIncrementer, init)
}

OrgOssPdfreporterEngineFillJRFloatDistinctCountIncrementer *create_OrgOssPdfreporterEngineFillJRFloatDistinctCountIncrementer_init() {
  J2OBJC_CREATE_IMPL(OrgOssPdfreporterEngineFillJRFloatDistinctCountIncrementer, init)
}

OrgOssPdfreporterEngineFillJRFloatDistinctCountIncrementer *OrgOssPdfreporterEngineFillJRFloatDistinctCountIncrementer_getInstance() {
  OrgOssPdfreporterEngineFillJRFloatDistinctCountIncrementer_initialize();
  return OrgOssPdfreporterEngineFillJRFloatDistinctCountIncrementer_mainInstance;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgOssPdfreporterEngineFillJRFloatDistinctCountIncrementer)

J2OBJC_INITIALIZED_DEFN(OrgOssPdfreporterEngineFillJRFloatSumIncrementer)

@implementation OrgOssPdfreporterEngineFillJRFloatSumIncrementer

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgOssPdfreporterEngineFillJRFloatSumIncrementer_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (OrgOssPdfreporterEngineFillJRFloatSumIncrementer *)getInstance {
  return OrgOssPdfreporterEngineFillJRFloatSumIncrementer_getInstance();
}

- (id)incrementWithOrgOssPdfreporterEngineFillJRCalculable:(id<OrgOssPdfreporterEngineFillJRCalculable>)variable
                                                    withId:(id)expressionValue
      withOrgOssPdfreporterEngineFillAbstractValueProvider:(OrgOssPdfreporterEngineFillAbstractValueProvider *)valueProvider {
  NSNumber *value = (NSNumber *) cast_chk([((id<OrgOssPdfreporterEngineFillJRCalculable>) nil_chk(variable)) getIncrementedValue], [NSNumber class]);
  NSNumber *newValue = (NSNumber *) cast_chk(expressionValue, [NSNumber class]);
  if (newValue == nil) {
    if ([variable isInitialized]) {
      return nil;
    }
    return value;
  }
  if (value == nil || [variable isInitialized]) {
    value = JreLoadStatic(OrgOssPdfreporterEngineFillJRFloatIncrementerFactory, ZERO);
  }
  return new_JavaLangFloat_initWithFloat_([((NSNumber *) nil_chk(value)) floatValue] + [newValue floatValue]);
}

- (id)initialValue {
  return JreLoadStatic(OrgOssPdfreporterEngineFillJRFloatIncrementerFactory, ZERO);
}

+ (void)initialize {
  if (self == [OrgOssPdfreporterEngineFillJRFloatSumIncrementer class]) {
    OrgOssPdfreporterEngineFillJRFloatSumIncrementer_mainInstance = new_OrgOssPdfreporterEngineFillJRFloatSumIncrementer_init();
    J2OBJC_SET_INITIALIZED(OrgOssPdfreporterEngineFillJRFloatSumIncrementer)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "JRFloatSumIncrementer", NULL, 0x2, NULL, NULL },
    { "getInstance", NULL, "Lorg.oss.pdfreporter.engine.fill.JRFloatSumIncrementer;", 0x9, NULL, NULL },
    { "incrementWithOrgOssPdfreporterEngineFillJRCalculable:withId:withOrgOssPdfreporterEngineFillAbstractValueProvider:", "increment", "Ljava.lang.Object;", 0x1, NULL, NULL },
    { "initialValue", NULL, "Ljava.lang.Object;", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "mainInstance", "mainInstance", 0xa, "Lorg.oss.pdfreporter.engine.fill.JRFloatSumIncrementer;", &OrgOssPdfreporterEngineFillJRFloatSumIncrementer_mainInstance, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _OrgOssPdfreporterEngineFillJRFloatSumIncrementer = { 2, "JRFloatSumIncrementer", "org.oss.pdfreporter.engine.fill", NULL, 0x10, 4, methods, 1, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgOssPdfreporterEngineFillJRFloatSumIncrementer;
}

@end

void OrgOssPdfreporterEngineFillJRFloatSumIncrementer_init(OrgOssPdfreporterEngineFillJRFloatSumIncrementer *self) {
  OrgOssPdfreporterEngineFillJRAbstractExtendedIncrementer_init(self);
}

OrgOssPdfreporterEngineFillJRFloatSumIncrementer *new_OrgOssPdfreporterEngineFillJRFloatSumIncrementer_init() {
  J2OBJC_NEW_IMPL(OrgOssPdfreporterEngineFillJRFloatSumIncrementer, init)
}

OrgOssPdfreporterEngineFillJRFloatSumIncrementer *create_OrgOssPdfreporterEngineFillJRFloatSumIncrementer_init() {
  J2OBJC_CREATE_IMPL(OrgOssPdfreporterEngineFillJRFloatSumIncrementer, init)
}

OrgOssPdfreporterEngineFillJRFloatSumIncrementer *OrgOssPdfreporterEngineFillJRFloatSumIncrementer_getInstance() {
  OrgOssPdfreporterEngineFillJRFloatSumIncrementer_initialize();
  return OrgOssPdfreporterEngineFillJRFloatSumIncrementer_mainInstance;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgOssPdfreporterEngineFillJRFloatSumIncrementer)

J2OBJC_INITIALIZED_DEFN(OrgOssPdfreporterEngineFillJRFloatAverageIncrementer)

@implementation OrgOssPdfreporterEngineFillJRFloatAverageIncrementer

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgOssPdfreporterEngineFillJRFloatAverageIncrementer_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (OrgOssPdfreporterEngineFillJRFloatAverageIncrementer *)getInstance {
  return OrgOssPdfreporterEngineFillJRFloatAverageIncrementer_getInstance();
}

- (id)incrementWithOrgOssPdfreporterEngineFillJRCalculable:(id<OrgOssPdfreporterEngineFillJRCalculable>)variable
                                                    withId:(id)expressionValue
      withOrgOssPdfreporterEngineFillAbstractValueProvider:(OrgOssPdfreporterEngineFillAbstractValueProvider *)valueProvider {
  if (expressionValue == nil) {
    if ([((id<OrgOssPdfreporterEngineFillJRCalculable>) nil_chk(variable)) isInitialized]) {
      return nil;
    }
    return [variable getValue];
  }
  NSNumber *countValue = (NSNumber *) cast_chk([((OrgOssPdfreporterEngineFillAbstractValueProvider *) nil_chk(valueProvider)) getValueWithOrgOssPdfreporterEngineFillJRCalculable:[((id<OrgOssPdfreporterEngineFillJRCalculable>) nil_chk(variable)) getHelperVariableWithByte:OrgOssPdfreporterEngineFillJRCalculable_HELPER_COUNT]], [NSNumber class]);
  NSNumber *sumValue = (NSNumber *) cast_chk([valueProvider getValueWithOrgOssPdfreporterEngineFillJRCalculable:[variable getHelperVariableWithByte:OrgOssPdfreporterEngineFillJRCalculable_HELPER_SUM]], [NSNumber class]);
  return new_JavaLangFloat_initWithFloat_([((NSNumber *) nil_chk(sumValue)) floatValue] / [((NSNumber *) nil_chk(countValue)) floatValue]);
}

- (id)initialValue {
  return JreLoadStatic(OrgOssPdfreporterEngineFillJRFloatIncrementerFactory, ZERO);
}

+ (void)initialize {
  if (self == [OrgOssPdfreporterEngineFillJRFloatAverageIncrementer class]) {
    OrgOssPdfreporterEngineFillJRFloatAverageIncrementer_mainInstance = new_OrgOssPdfreporterEngineFillJRFloatAverageIncrementer_init();
    J2OBJC_SET_INITIALIZED(OrgOssPdfreporterEngineFillJRFloatAverageIncrementer)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "JRFloatAverageIncrementer", NULL, 0x2, NULL, NULL },
    { "getInstance", NULL, "Lorg.oss.pdfreporter.engine.fill.JRFloatAverageIncrementer;", 0x9, NULL, NULL },
    { "incrementWithOrgOssPdfreporterEngineFillJRCalculable:withId:withOrgOssPdfreporterEngineFillAbstractValueProvider:", "increment", "Ljava.lang.Object;", 0x1, NULL, NULL },
    { "initialValue", NULL, "Ljava.lang.Object;", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "mainInstance", "mainInstance", 0xa, "Lorg.oss.pdfreporter.engine.fill.JRFloatAverageIncrementer;", &OrgOssPdfreporterEngineFillJRFloatAverageIncrementer_mainInstance, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _OrgOssPdfreporterEngineFillJRFloatAverageIncrementer = { 2, "JRFloatAverageIncrementer", "org.oss.pdfreporter.engine.fill", NULL, 0x10, 4, methods, 1, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgOssPdfreporterEngineFillJRFloatAverageIncrementer;
}

@end

void OrgOssPdfreporterEngineFillJRFloatAverageIncrementer_init(OrgOssPdfreporterEngineFillJRFloatAverageIncrementer *self) {
  OrgOssPdfreporterEngineFillJRAbstractExtendedIncrementer_init(self);
}

OrgOssPdfreporterEngineFillJRFloatAverageIncrementer *new_OrgOssPdfreporterEngineFillJRFloatAverageIncrementer_init() {
  J2OBJC_NEW_IMPL(OrgOssPdfreporterEngineFillJRFloatAverageIncrementer, init)
}

OrgOssPdfreporterEngineFillJRFloatAverageIncrementer *create_OrgOssPdfreporterEngineFillJRFloatAverageIncrementer_init() {
  J2OBJC_CREATE_IMPL(OrgOssPdfreporterEngineFillJRFloatAverageIncrementer, init)
}

OrgOssPdfreporterEngineFillJRFloatAverageIncrementer *OrgOssPdfreporterEngineFillJRFloatAverageIncrementer_getInstance() {
  OrgOssPdfreporterEngineFillJRFloatAverageIncrementer_initialize();
  return OrgOssPdfreporterEngineFillJRFloatAverageIncrementer_mainInstance;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgOssPdfreporterEngineFillJRFloatAverageIncrementer)

J2OBJC_INITIALIZED_DEFN(OrgOssPdfreporterEngineFillJRFloatStandardDeviationIncrementer)

@implementation OrgOssPdfreporterEngineFillJRFloatStandardDeviationIncrementer

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgOssPdfreporterEngineFillJRFloatStandardDeviationIncrementer_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (OrgOssPdfreporterEngineFillJRFloatStandardDeviationIncrementer *)getInstance {
  return OrgOssPdfreporterEngineFillJRFloatStandardDeviationIncrementer_getInstance();
}

- (id)incrementWithOrgOssPdfreporterEngineFillJRCalculable:(id<OrgOssPdfreporterEngineFillJRCalculable>)variable
                                                    withId:(id)expressionValue
      withOrgOssPdfreporterEngineFillAbstractValueProvider:(OrgOssPdfreporterEngineFillAbstractValueProvider *)valueProvider {
  if (expressionValue == nil) {
    if ([((id<OrgOssPdfreporterEngineFillJRCalculable>) nil_chk(variable)) isInitialized]) {
      return nil;
    }
    return [variable getValue];
  }
  NSNumber *varianceValue = (NSNumber *) cast_chk([((OrgOssPdfreporterEngineFillAbstractValueProvider *) nil_chk(valueProvider)) getValueWithOrgOssPdfreporterEngineFillJRCalculable:[((id<OrgOssPdfreporterEngineFillJRCalculable>) nil_chk(variable)) getHelperVariableWithByte:OrgOssPdfreporterEngineFillJRCalculable_HELPER_VARIANCE]], [NSNumber class]);
  return new_JavaLangFloat_initWithDouble_(JavaLangMath_sqrtWithDouble_([((NSNumber *) nil_chk(varianceValue)) doubleValue]));
}

- (id)initialValue {
  return JreLoadStatic(OrgOssPdfreporterEngineFillJRFloatIncrementerFactory, ZERO);
}

+ (void)initialize {
  if (self == [OrgOssPdfreporterEngineFillJRFloatStandardDeviationIncrementer class]) {
    OrgOssPdfreporterEngineFillJRFloatStandardDeviationIncrementer_mainInstance = new_OrgOssPdfreporterEngineFillJRFloatStandardDeviationIncrementer_init();
    J2OBJC_SET_INITIALIZED(OrgOssPdfreporterEngineFillJRFloatStandardDeviationIncrementer)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "JRFloatStandardDeviationIncrementer", NULL, 0x2, NULL, NULL },
    { "getInstance", NULL, "Lorg.oss.pdfreporter.engine.fill.JRFloatStandardDeviationIncrementer;", 0x9, NULL, NULL },
    { "incrementWithOrgOssPdfreporterEngineFillJRCalculable:withId:withOrgOssPdfreporterEngineFillAbstractValueProvider:", "increment", "Ljava.lang.Object;", 0x1, NULL, NULL },
    { "initialValue", NULL, "Ljava.lang.Object;", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "mainInstance", "mainInstance", 0xa, "Lorg.oss.pdfreporter.engine.fill.JRFloatStandardDeviationIncrementer;", &OrgOssPdfreporterEngineFillJRFloatStandardDeviationIncrementer_mainInstance, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _OrgOssPdfreporterEngineFillJRFloatStandardDeviationIncrementer = { 2, "JRFloatStandardDeviationIncrementer", "org.oss.pdfreporter.engine.fill", NULL, 0x10, 4, methods, 1, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgOssPdfreporterEngineFillJRFloatStandardDeviationIncrementer;
}

@end

void OrgOssPdfreporterEngineFillJRFloatStandardDeviationIncrementer_init(OrgOssPdfreporterEngineFillJRFloatStandardDeviationIncrementer *self) {
  OrgOssPdfreporterEngineFillJRAbstractExtendedIncrementer_init(self);
}

OrgOssPdfreporterEngineFillJRFloatStandardDeviationIncrementer *new_OrgOssPdfreporterEngineFillJRFloatStandardDeviationIncrementer_init() {
  J2OBJC_NEW_IMPL(OrgOssPdfreporterEngineFillJRFloatStandardDeviationIncrementer, init)
}

OrgOssPdfreporterEngineFillJRFloatStandardDeviationIncrementer *create_OrgOssPdfreporterEngineFillJRFloatStandardDeviationIncrementer_init() {
  J2OBJC_CREATE_IMPL(OrgOssPdfreporterEngineFillJRFloatStandardDeviationIncrementer, init)
}

OrgOssPdfreporterEngineFillJRFloatStandardDeviationIncrementer *OrgOssPdfreporterEngineFillJRFloatStandardDeviationIncrementer_getInstance() {
  OrgOssPdfreporterEngineFillJRFloatStandardDeviationIncrementer_initialize();
  return OrgOssPdfreporterEngineFillJRFloatStandardDeviationIncrementer_mainInstance;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgOssPdfreporterEngineFillJRFloatStandardDeviationIncrementer)

J2OBJC_INITIALIZED_DEFN(OrgOssPdfreporterEngineFillJRFloatVarianceIncrementer)

@implementation OrgOssPdfreporterEngineFillJRFloatVarianceIncrementer

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgOssPdfreporterEngineFillJRFloatVarianceIncrementer_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (OrgOssPdfreporterEngineFillJRFloatVarianceIncrementer *)getInstance {
  return OrgOssPdfreporterEngineFillJRFloatVarianceIncrementer_getInstance();
}

- (id)incrementWithOrgOssPdfreporterEngineFillJRCalculable:(id<OrgOssPdfreporterEngineFillJRCalculable>)variable
                                                    withId:(id)expressionValue
      withOrgOssPdfreporterEngineFillAbstractValueProvider:(OrgOssPdfreporterEngineFillAbstractValueProvider *)valueProvider {
  NSNumber *value = (NSNumber *) cast_chk([((id<OrgOssPdfreporterEngineFillJRCalculable>) nil_chk(variable)) getIncrementedValue], [NSNumber class]);
  NSNumber *newValue = (NSNumber *) cast_chk(expressionValue, [NSNumber class]);
  if (newValue == nil) {
    if ([variable isInitialized]) {
      return nil;
    }
    return value;
  }
  else if (value == nil || [variable isInitialized]) {
    return JreLoadStatic(OrgOssPdfreporterEngineFillJRFloatIncrementerFactory, ZERO);
  }
  else {
    NSNumber *countValue = (NSNumber *) cast_chk([((OrgOssPdfreporterEngineFillAbstractValueProvider *) nil_chk(valueProvider)) getValueWithOrgOssPdfreporterEngineFillJRCalculable:[variable getHelperVariableWithByte:OrgOssPdfreporterEngineFillJRCalculable_HELPER_COUNT]], [NSNumber class]);
    NSNumber *sumValue = (NSNumber *) cast_chk([valueProvider getValueWithOrgOssPdfreporterEngineFillJRCalculable:[variable getHelperVariableWithByte:OrgOssPdfreporterEngineFillJRCalculable_HELPER_SUM]], [NSNumber class]);
    return new_JavaLangFloat_initWithFloat_(([((NSNumber *) nil_chk(countValue)) floatValue] - 1) * [value floatValue] / [countValue floatValue] + ([((NSNumber *) nil_chk(sumValue)) floatValue] / [countValue floatValue] - [newValue floatValue]) * ([sumValue floatValue] / [countValue floatValue] - [newValue floatValue]) / ([countValue floatValue] - 1));
  }
}

- (id)combineWithOrgOssPdfreporterEngineFillJRCalculable:(id<OrgOssPdfreporterEngineFillJRCalculable>)calculable
             withOrgOssPdfreporterEngineFillJRCalculable:(id<OrgOssPdfreporterEngineFillJRCalculable>)calculableValue
    withOrgOssPdfreporterEngineFillAbstractValueProvider:(OrgOssPdfreporterEngineFillAbstractValueProvider *)valueProvider {
  NSNumber *value = (NSNumber *) cast_chk([((id<OrgOssPdfreporterEngineFillJRCalculable>) nil_chk(calculable)) getIncrementedValue], [NSNumber class]);
  if ([((id<OrgOssPdfreporterEngineFillJRCalculable>) nil_chk(calculableValue)) getValue] == nil) {
    if ([calculable isInitialized]) {
      return nil;
    }
    return value;
  }
  else if (value == nil || [calculable isInitialized]) {
    return new_JavaLangFloat_initWithFloat_([((NSNumber *) nil_chk(((NSNumber *) cast_chk([calculableValue getIncrementedValue], [NSNumber class])))) floatValue]);
  }
  jfloat v1 = [value floatValue];
  jfloat c1 = [((NSNumber *) nil_chk(((NSNumber *) cast_chk([((OrgOssPdfreporterEngineFillAbstractValueProvider *) nil_chk(valueProvider)) getValueWithOrgOssPdfreporterEngineFillJRCalculable:[calculable getHelperVariableWithByte:OrgOssPdfreporterEngineFillJRCalculable_HELPER_COUNT]], [NSNumber class])))) floatValue];
  jfloat s1 = [((NSNumber *) nil_chk(((NSNumber *) cast_chk([valueProvider getValueWithOrgOssPdfreporterEngineFillJRCalculable:[calculable getHelperVariableWithByte:OrgOssPdfreporterEngineFillJRCalculable_HELPER_SUM]], [NSNumber class])))) floatValue];
  jfloat v2 = [((NSNumber *) nil_chk(((NSNumber *) cast_chk([calculableValue getIncrementedValue], [NSNumber class])))) floatValue];
  jfloat c2 = [((NSNumber *) nil_chk(((NSNumber *) cast_chk([valueProvider getValueWithOrgOssPdfreporterEngineFillJRCalculable:[calculableValue getHelperVariableWithByte:OrgOssPdfreporterEngineFillJRCalculable_HELPER_COUNT]], [NSNumber class])))) floatValue];
  jfloat s2 = [((NSNumber *) nil_chk(((NSNumber *) cast_chk([valueProvider getValueWithOrgOssPdfreporterEngineFillJRCalculable:[calculableValue getHelperVariableWithByte:OrgOssPdfreporterEngineFillJRCalculable_HELPER_SUM]], [NSNumber class])))) floatValue];
  JreMinusAssignFloatF(&c1, c2);
  JreMinusAssignFloatF(&s1, s2);
  jfloat c = c1 + c2;
  return new_JavaLangFloat_initWithFloat_(c1 / c * v1 + c2 / c * v2 + c2 / c1 * s1 / c * s1 / c + c1 / c2 * s2 / c * s2 / c - 2 * s1 / c * s2 / c);
}

- (id)initialValue {
  return JreLoadStatic(OrgOssPdfreporterEngineFillJRFloatIncrementerFactory, ZERO);
}

+ (void)initialize {
  if (self == [OrgOssPdfreporterEngineFillJRFloatVarianceIncrementer class]) {
    OrgOssPdfreporterEngineFillJRFloatVarianceIncrementer_mainInstance = new_OrgOssPdfreporterEngineFillJRFloatVarianceIncrementer_init();
    J2OBJC_SET_INITIALIZED(OrgOssPdfreporterEngineFillJRFloatVarianceIncrementer)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "JRFloatVarianceIncrementer", NULL, 0x2, NULL, NULL },
    { "getInstance", NULL, "Lorg.oss.pdfreporter.engine.fill.JRFloatVarianceIncrementer;", 0x9, NULL, NULL },
    { "incrementWithOrgOssPdfreporterEngineFillJRCalculable:withId:withOrgOssPdfreporterEngineFillAbstractValueProvider:", "increment", "Ljava.lang.Object;", 0x1, NULL, NULL },
    { "combineWithOrgOssPdfreporterEngineFillJRCalculable:withOrgOssPdfreporterEngineFillJRCalculable:withOrgOssPdfreporterEngineFillAbstractValueProvider:", "combine", "Ljava.lang.Object;", 0x1, NULL, NULL },
    { "initialValue", NULL, "Ljava.lang.Object;", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "mainInstance", "mainInstance", 0xa, "Lorg.oss.pdfreporter.engine.fill.JRFloatVarianceIncrementer;", &OrgOssPdfreporterEngineFillJRFloatVarianceIncrementer_mainInstance, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _OrgOssPdfreporterEngineFillJRFloatVarianceIncrementer = { 2, "JRFloatVarianceIncrementer", "org.oss.pdfreporter.engine.fill", NULL, 0x10, 5, methods, 1, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgOssPdfreporterEngineFillJRFloatVarianceIncrementer;
}

@end

void OrgOssPdfreporterEngineFillJRFloatVarianceIncrementer_init(OrgOssPdfreporterEngineFillJRFloatVarianceIncrementer *self) {
  OrgOssPdfreporterEngineFillJRAbstractExtendedIncrementer_init(self);
}

OrgOssPdfreporterEngineFillJRFloatVarianceIncrementer *new_OrgOssPdfreporterEngineFillJRFloatVarianceIncrementer_init() {
  J2OBJC_NEW_IMPL(OrgOssPdfreporterEngineFillJRFloatVarianceIncrementer, init)
}

OrgOssPdfreporterEngineFillJRFloatVarianceIncrementer *create_OrgOssPdfreporterEngineFillJRFloatVarianceIncrementer_init() {
  J2OBJC_CREATE_IMPL(OrgOssPdfreporterEngineFillJRFloatVarianceIncrementer, init)
}

OrgOssPdfreporterEngineFillJRFloatVarianceIncrementer *OrgOssPdfreporterEngineFillJRFloatVarianceIncrementer_getInstance() {
  OrgOssPdfreporterEngineFillJRFloatVarianceIncrementer_initialize();
  return OrgOssPdfreporterEngineFillJRFloatVarianceIncrementer_mainInstance;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgOssPdfreporterEngineFillJRFloatVarianceIncrementer)
