//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../pdfreporter-core/src/org/oss/pdfreporter/engine/fill/JRRecordedValuesPrintElement.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgOssPdfreporterEngineFillJRRecordedValuesPrintElement")
#ifdef RESTRICT_OrgOssPdfreporterEngineFillJRRecordedValuesPrintElement
#define INCLUDE_ALL_OrgOssPdfreporterEngineFillJRRecordedValuesPrintElement 0
#else
#define INCLUDE_ALL_OrgOssPdfreporterEngineFillJRRecordedValuesPrintElement 1
#endif
#undef RESTRICT_OrgOssPdfreporterEngineFillJRRecordedValuesPrintElement

#if !defined (OrgOssPdfreporterEngineFillJRRecordedValuesPrintElement_) && (INCLUDE_ALL_OrgOssPdfreporterEngineFillJRRecordedValuesPrintElement || defined(INCLUDE_OrgOssPdfreporterEngineFillJRRecordedValuesPrintElement))
#define OrgOssPdfreporterEngineFillJRRecordedValuesPrintElement_

#define RESTRICT_OrgOssPdfreporterEngineJRPrintElement 1
#define INCLUDE_OrgOssPdfreporterEngineJRPrintElement 1
#include "org/oss/pdfreporter/engine/JRPrintElement.h"

@class OrgOssPdfreporterEngineFillJRRecordedValues;
@protocol JavaUtilSet;

@protocol OrgOssPdfreporterEngineFillJRRecordedValuesPrintElement < OrgOssPdfreporterEngineJRPrintElement, NSObject, JavaObject >

- (void)initRecordedValuesWithJavaUtilSet:(id<JavaUtilSet>)evaluationTimes OBJC_METHOD_FAMILY_NONE;

- (OrgOssPdfreporterEngineFillJRRecordedValues *)getRecordedValues;

- (void)deleteRecordedValues;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgOssPdfreporterEngineFillJRRecordedValuesPrintElement)

J2OBJC_TYPE_LITERAL_HEADER(OrgOssPdfreporterEngineFillJRRecordedValuesPrintElement)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgOssPdfreporterEngineFillJRRecordedValuesPrintElement")
