//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../pdfreporter-core/src/org/oss/pdfreporter/data/cache/CachedDataset.java
//

#include "J2ObjC_source.h"
#include "org/oss/pdfreporter/data/cache/CachedDataset.h"

@interface OrgOssPdfreporterDataCacheCachedDataset : NSObject

@end

@implementation OrgOssPdfreporterDataCacheCachedDataset

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "hasParameterWithNSString:", "hasParameter", "Z", 0x401, NULL, NULL },
    { "getParameterValueWithNSString:", "getParameterValue", "Ljava.lang.Object;", 0x401, NULL, NULL },
    { "getDataSource", NULL, "Lorg.oss.pdfreporter.engine.data.IndexedDataSource;", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _OrgOssPdfreporterDataCacheCachedDataset = { 2, "CachedDataset", "org.oss.pdfreporter.data.cache", NULL, 0x609, 3, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgOssPdfreporterDataCacheCachedDataset;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgOssPdfreporterDataCacheCachedDataset)
