//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../pdfreporter-core/src/org/oss/pdfreporter/engine/query/QueryExecuterFactoryBundle.java
//

#include "J2ObjC_source.h"
#include "org/oss/pdfreporter/engine/query/QueryExecuterFactoryBundle.h"

@interface OrgOssPdfreporterEngineQueryQueryExecuterFactoryBundle : NSObject

@end

@implementation OrgOssPdfreporterEngineQueryQueryExecuterFactoryBundle

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getLanguages", NULL, "[Ljava.lang.String;", 0x401, NULL, NULL },
    { "getQueryExecuterFactoryWithNSString:", "getQueryExecuterFactory", "Lorg.oss.pdfreporter.engine.query.JRQueryExecuterFactory;", 0x401, "Lorg.oss.pdfreporter.engine.JRException;", NULL },
  };
  static const J2ObjcClassInfo _OrgOssPdfreporterEngineQueryQueryExecuterFactoryBundle = { 2, "QueryExecuterFactoryBundle", "org.oss.pdfreporter.engine.query", NULL, 0x609, 2, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgOssPdfreporterEngineQueryQueryExecuterFactoryBundle;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgOssPdfreporterEngineQueryQueryExecuterFactoryBundle)
