//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../pdfreporter-core/src/org/oss/pdfreporter/engine/design/DesignStyleContainer.java
//

#include "J2ObjC_source.h"
#include "org/oss/pdfreporter/engine/design/DesignStyleContainer.h"

@interface OrgOssPdfreporterEngineDesignDesignStyleContainer : NSObject

@end

@implementation OrgOssPdfreporterEngineDesignDesignStyleContainer

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "setDefaultStyleProviderWithOrgOssPdfreporterEngineJRDefaultStyleProvider:", "setDefaultStyleProvider", "V", 0x401, NULL, NULL },
    { "setStyleWithOrgOssPdfreporterEngineJRStyle:", "setStyle", "V", 0x401, NULL, NULL },
    { "setStyleNameReferenceWithNSString:", "setStyleNameReference", "V", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _OrgOssPdfreporterEngineDesignDesignStyleContainer = { 2, "DesignStyleContainer", "org.oss.pdfreporter.engine.design", NULL, 0x609, 3, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgOssPdfreporterEngineDesignDesignStyleContainer;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgOssPdfreporterEngineDesignDesignStyleContainer)
