//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../pdfreporter-core/src/org/oss/pdfreporter/engine/design/JRDesignStaticText.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "org/oss/pdfreporter/engine/JRConstants.h"
#include "org/oss/pdfreporter/engine/JRDefaultStyleProvider.h"
#include "org/oss/pdfreporter/engine/JRExpressionCollector.h"
#include "org/oss/pdfreporter/engine/JRVisitor.h"
#include "org/oss/pdfreporter/engine/base/JRBaseElement.h"
#include "org/oss/pdfreporter/engine/base/JRBaseStaticText.h"
#include "org/oss/pdfreporter/engine/design/JRDesignStaticText.h"
#include "org/oss/pdfreporter/engine/design/JRDesignTextElement.h"
#include "org/oss/pdfreporter/engine/design/events/JRPropertyChangeSupport.h"

inline jlong OrgOssPdfreporterEngineDesignJRDesignStaticText_get_serialVersionUID();
#define OrgOssPdfreporterEngineDesignJRDesignStaticText_serialVersionUID 10200LL
J2OBJC_STATIC_FIELD_CONSTANT(OrgOssPdfreporterEngineDesignJRDesignStaticText, serialVersionUID, jlong)

@implementation OrgOssPdfreporterEngineDesignJRDesignStaticText

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgOssPdfreporterEngineDesignJRDesignStaticText_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithOrgOssPdfreporterEngineJRDefaultStyleProvider:(id<OrgOssPdfreporterEngineJRDefaultStyleProvider>)defaultStyleProvider {
  OrgOssPdfreporterEngineDesignJRDesignStaticText_initWithOrgOssPdfreporterEngineJRDefaultStyleProvider_(self, defaultStyleProvider);
  return self;
}

- (NSString *)getText {
  return self->text_;
}

- (void)setTextWithNSString:(NSString *)text {
  id old = self->text_;
  self->text_ = text;
  [((OrgOssPdfreporterEngineDesignEventsJRPropertyChangeSupport *) nil_chk([self getEventSupport])) firePropertyChangeWithNSString:OrgOssPdfreporterEngineBaseJRBaseStaticText_PROPERTY_TEXT withId:old withId:self->text_];
}

- (void)collectExpressionsWithOrgOssPdfreporterEngineJRExpressionCollector:(OrgOssPdfreporterEngineJRExpressionCollector *)collector {
  [((OrgOssPdfreporterEngineJRExpressionCollector *) nil_chk(collector)) collectWithOrgOssPdfreporterEngineJRStaticText:self];
}

- (void)visitWithOrgOssPdfreporterEngineJRVisitor:(id<OrgOssPdfreporterEngineJRVisitor>)visitor {
  [((id<OrgOssPdfreporterEngineJRVisitor>) nil_chk(visitor)) visitStaticTextWithOrgOssPdfreporterEngineJRStaticText:self];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "JRDesignStaticText", NULL, 0x1, NULL, NULL },
    { "initWithOrgOssPdfreporterEngineJRDefaultStyleProvider:", "JRDesignStaticText", NULL, 0x1, NULL, NULL },
    { "getText", NULL, "Ljava.lang.String;", 0x1, NULL, NULL },
    { "setTextWithNSString:", "setText", "V", 0x1, NULL, NULL },
    { "collectExpressionsWithOrgOssPdfreporterEngineJRExpressionCollector:", "collectExpressions", "V", 0x1, NULL, NULL },
    { "visitWithOrgOssPdfreporterEngineJRVisitor:", "visit", "V", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "serialVersionUID", "serialVersionUID", 0x1a, "J", NULL, NULL, .constantValue.asLong = OrgOssPdfreporterEngineDesignJRDesignStaticText_serialVersionUID },
    { "text_", NULL, 0x4, "Ljava.lang.String;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _OrgOssPdfreporterEngineDesignJRDesignStaticText = { 2, "JRDesignStaticText", "org.oss.pdfreporter.engine.design", NULL, 0x1, 6, methods, 2, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgOssPdfreporterEngineDesignJRDesignStaticText;
}

@end

void OrgOssPdfreporterEngineDesignJRDesignStaticText_init(OrgOssPdfreporterEngineDesignJRDesignStaticText *self) {
  OrgOssPdfreporterEngineDesignJRDesignTextElement_initWithOrgOssPdfreporterEngineJRDefaultStyleProvider_(self, nil);
}

OrgOssPdfreporterEngineDesignJRDesignStaticText *new_OrgOssPdfreporterEngineDesignJRDesignStaticText_init() {
  J2OBJC_NEW_IMPL(OrgOssPdfreporterEngineDesignJRDesignStaticText, init)
}

OrgOssPdfreporterEngineDesignJRDesignStaticText *create_OrgOssPdfreporterEngineDesignJRDesignStaticText_init() {
  J2OBJC_CREATE_IMPL(OrgOssPdfreporterEngineDesignJRDesignStaticText, init)
}

void OrgOssPdfreporterEngineDesignJRDesignStaticText_initWithOrgOssPdfreporterEngineJRDefaultStyleProvider_(OrgOssPdfreporterEngineDesignJRDesignStaticText *self, id<OrgOssPdfreporterEngineJRDefaultStyleProvider> defaultStyleProvider) {
  OrgOssPdfreporterEngineDesignJRDesignTextElement_initWithOrgOssPdfreporterEngineJRDefaultStyleProvider_(self, defaultStyleProvider);
}

OrgOssPdfreporterEngineDesignJRDesignStaticText *new_OrgOssPdfreporterEngineDesignJRDesignStaticText_initWithOrgOssPdfreporterEngineJRDefaultStyleProvider_(id<OrgOssPdfreporterEngineJRDefaultStyleProvider> defaultStyleProvider) {
  J2OBJC_NEW_IMPL(OrgOssPdfreporterEngineDesignJRDesignStaticText, initWithOrgOssPdfreporterEngineJRDefaultStyleProvider_, defaultStyleProvider)
}

OrgOssPdfreporterEngineDesignJRDesignStaticText *create_OrgOssPdfreporterEngineDesignJRDesignStaticText_initWithOrgOssPdfreporterEngineJRDefaultStyleProvider_(id<OrgOssPdfreporterEngineJRDefaultStyleProvider> defaultStyleProvider) {
  J2OBJC_CREATE_IMPL(OrgOssPdfreporterEngineDesignJRDesignStaticText, initWithOrgOssPdfreporterEngineJRDefaultStyleProvider_, defaultStyleProvider)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgOssPdfreporterEngineDesignJRDesignStaticText)
