//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../pdfreporter-core/src/org/oss/pdfreporter/compilers/javascript/interpreter/extension/INativeTypeChecker.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgOssPdfreporterCompilersJavascriptInterpreterExtensionINativeTypeChecker")
#ifdef RESTRICT_OrgOssPdfreporterCompilersJavascriptInterpreterExtensionINativeTypeChecker
#define INCLUDE_ALL_OrgOssPdfreporterCompilersJavascriptInterpreterExtensionINativeTypeChecker 0
#else
#define INCLUDE_ALL_OrgOssPdfreporterCompilersJavascriptInterpreterExtensionINativeTypeChecker 1
#endif
#undef RESTRICT_OrgOssPdfreporterCompilersJavascriptInterpreterExtensionINativeTypeChecker

#if !defined (OrgOssPdfreporterCompilersJavascriptInterpreterExtensionINativeTypeChecker_) && (INCLUDE_ALL_OrgOssPdfreporterCompilersJavascriptInterpreterExtensionINativeTypeChecker || defined(INCLUDE_OrgOssPdfreporterCompilersJavascriptInterpreterExtensionINativeTypeChecker))
#define OrgOssPdfreporterCompilersJavascriptInterpreterExtensionINativeTypeChecker_

@protocol OrgOssPdfreporterCompilersJavascriptInterpreterExtensionINativeTypeChecker < NSObject, JavaObject >

- (jboolean)isBooleanWithId:(id)source;

- (jboolean)isStringWithId:(id)source;

- (jboolean)isNumberWithId:(id)source;

- (jboolean)isDateWithId:(id)source;

- (jboolean)isCollectionWithId:(id)source;

- (jboolean)isMapWithId:(id)source;

- (jint)getCollectionSizeWithId:(id)source;

- (jint)getMapSizeWithId:(id)source;

- (id)getMapElementWithId:(id)source
             withNSString:(NSString *)key;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgOssPdfreporterCompilersJavascriptInterpreterExtensionINativeTypeChecker)

J2OBJC_TYPE_LITERAL_HEADER(OrgOssPdfreporterCompilersJavascriptInterpreterExtensionINativeTypeChecker)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgOssPdfreporterCompilersJavascriptInterpreterExtensionINativeTypeChecker")
