//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../pdfreporter-core/src/org/oss/pdfreporter/properties/PropertyConstants.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgOssPdfreporterPropertiesPropertyConstants")
#ifdef RESTRICT_OrgOssPdfreporterPropertiesPropertyConstants
#define INCLUDE_ALL_OrgOssPdfreporterPropertiesPropertyConstants 0
#else
#define INCLUDE_ALL_OrgOssPdfreporterPropertiesPropertyConstants 1
#endif
#undef RESTRICT_OrgOssPdfreporterPropertiesPropertyConstants

#if !defined (OrgOssPdfreporterPropertiesPropertyConstants_) && (INCLUDE_ALL_OrgOssPdfreporterPropertiesPropertyConstants || defined(INCLUDE_OrgOssPdfreporterPropertiesPropertyConstants))
#define OrgOssPdfreporterPropertiesPropertyConstants_

@protocol OrgOssPdfreporterPropertiesPropertyConstants < NSObject, JavaObject >

@end

@interface OrgOssPdfreporterPropertiesPropertyConstants : NSObject

+ (NSString *)PREFIX_CATEGORY;

+ (NSString *)CATEGORY_DATA_SOURCE;

+ (NSString *)CATEGORY_COMPILE;

+ (NSString *)CATEGORY_DESIGN;

+ (NSString *)CATEGORY_FILL;

+ (NSString *)CATEGORY_GOVERNOR;

+ (NSString *)CATEGORY_CROSSTAB;

+ (NSString *)CATEGORY_BARCODE;

+ (NSString *)CATEGORY_MAP;

+ (NSString *)CATEGORY_TABLE;

+ (NSString *)CATEGORY_CHART_THEME;

+ (NSString *)CATEGORY_EXPORT;

+ (NSString *)CATEGORY_EXTENSIONS;

+ (NSString *)CATEGORY_REPOSITORY;

+ (NSString *)CATEGORY_OTHER;

+ (NSString *)CATEGORY_PHANTOM_JS;

+ (NSString *)CATEGORY_DATA_CACHE;

+ (NSString *)CATEGORY_WEB_UTIL;

+ (NSString *)BOOLEAN_FALSE;

+ (NSString *)BOOLEAN_TRUE;

+ (NSString *)UTF_8;

+ (NSString *)COMMA;

+ (NSString *)QUOTES;

+ (NSString *)NEWLINE;

+ (NSString *)SAME_DOMAIN;

+ (NSString *)COLLAPSE;

+ (NSString *)PIXEL_UNIT;

+ (NSString *)DEFAULT;

+ (NSString *)QUESTION_MARK;

+ (NSString *)MOVE_NO_SIZE;

+ (NSString *)LTR;

+ (NSString *)COMPONENT_KEY_QUALIFICATION_SEPARATOR;

+ (NSString *)VERSION_1_0_0;

+ (NSString *)VERSION_1_2_0;

+ (NSString *)VERSION_1_2_2;

+ (NSString *)VERSION_1_2_3;

+ (NSString *)VERSION_1_2_8;

+ (NSString *)VERSION_1_3_0;

+ (NSString *)VERSION_1_3_1;

+ (NSString *)VERSION_1_3_4;

+ (NSString *)VERSION_2_0_0;

+ (NSString *)VERSION_2_0_1;

+ (NSString *)VERSION_2_0_2;

+ (NSString *)VERSION_2_0_3;

+ (NSString *)VERSION_2_0_5;

+ (NSString *)VERSION_3_0_0;

+ (NSString *)VERSION_3_0_1;

+ (NSString *)VERSION_3_1_0;

+ (NSString *)VERSION_3_1_2;

+ (NSString *)VERSION_3_1_3;

+ (NSString *)VERSION_3_1_4;

+ (NSString *)VERSION_3_5_0;

+ (NSString *)VERSION_3_5_1;

+ (NSString *)VERSION_3_5_2;

+ (NSString *)VERSION_3_5_3;

+ (NSString *)VERSION_3_5_4;

+ (NSString *)VERSION_3_6_1;

+ (NSString *)VERSION_3_6_2;

+ (NSString *)VERSION_3_7_0;

+ (NSString *)VERSION_3_7_1;

+ (NSString *)VERSION_3_7_3;

+ (NSString *)VERSION_3_7_5;

+ (NSString *)VERSION_3_7_6;

+ (NSString *)VERSION_4_0_0;

+ (NSString *)VERSION_4_0_1;

+ (NSString *)VERSION_4_0_2;

+ (NSString *)VERSION_4_1_1;

+ (NSString *)VERSION_4_1_2;

+ (NSString *)VERSION_4_1_3;

+ (NSString *)VERSION_4_5_0;

+ (NSString *)VERSION_4_5_1;

+ (NSString *)VERSION_4_6_0;

+ (NSString *)VERSION_4_7_0;

+ (NSString *)VERSION_4_7_1;

+ (NSString *)VERSION_4_8_0;

+ (NSString *)VERSION_5_0_0;

+ (NSString *)VERSION_5_0_1;

+ (NSString *)VERSION_5_1_2;

+ (NSString *)VERSION_5_2_0;

+ (NSString *)VERSION_6_4_0;

+ (NSString *)VERSION_6_4_2;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgOssPdfreporterPropertiesPropertyConstants)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_PREFIX_CATEGORY();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_PREFIX_CATEGORY;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, PREFIX_CATEGORY, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_CATEGORY_DATA_SOURCE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_CATEGORY_DATA_SOURCE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, CATEGORY_DATA_SOURCE, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_CATEGORY_COMPILE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_CATEGORY_COMPILE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, CATEGORY_COMPILE, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_CATEGORY_DESIGN();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_CATEGORY_DESIGN;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, CATEGORY_DESIGN, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_CATEGORY_FILL();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_CATEGORY_FILL;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, CATEGORY_FILL, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_CATEGORY_GOVERNOR();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_CATEGORY_GOVERNOR;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, CATEGORY_GOVERNOR, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_CATEGORY_CROSSTAB();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_CATEGORY_CROSSTAB;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, CATEGORY_CROSSTAB, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_CATEGORY_BARCODE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_CATEGORY_BARCODE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, CATEGORY_BARCODE, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_CATEGORY_MAP();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_CATEGORY_MAP;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, CATEGORY_MAP, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_CATEGORY_TABLE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_CATEGORY_TABLE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, CATEGORY_TABLE, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_CATEGORY_CHART_THEME();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_CATEGORY_CHART_THEME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, CATEGORY_CHART_THEME, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_CATEGORY_EXPORT();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_CATEGORY_EXPORT;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, CATEGORY_EXPORT, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_CATEGORY_EXTENSIONS();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_CATEGORY_EXTENSIONS;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, CATEGORY_EXTENSIONS, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_CATEGORY_REPOSITORY();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_CATEGORY_REPOSITORY;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, CATEGORY_REPOSITORY, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_CATEGORY_OTHER();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_CATEGORY_OTHER;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, CATEGORY_OTHER, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_CATEGORY_PHANTOM_JS();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_CATEGORY_PHANTOM_JS;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, CATEGORY_PHANTOM_JS, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_CATEGORY_DATA_CACHE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_CATEGORY_DATA_CACHE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, CATEGORY_DATA_CACHE, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_CATEGORY_WEB_UTIL();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_CATEGORY_WEB_UTIL;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, CATEGORY_WEB_UTIL, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_BOOLEAN_FALSE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_BOOLEAN_FALSE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, BOOLEAN_FALSE, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_BOOLEAN_TRUE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_BOOLEAN_TRUE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, BOOLEAN_TRUE, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_UTF_8();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_UTF_8;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, UTF_8, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_COMMA();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_COMMA;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, COMMA, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_QUOTES();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_QUOTES;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, QUOTES, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_NEWLINE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_NEWLINE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, NEWLINE, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_SAME_DOMAIN();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_SAME_DOMAIN;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, SAME_DOMAIN, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_COLLAPSE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_COLLAPSE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, COLLAPSE, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_PIXEL_UNIT();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_PIXEL_UNIT;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, PIXEL_UNIT, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_DEFAULT();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_DEFAULT;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, DEFAULT, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_QUESTION_MARK();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_QUESTION_MARK;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, QUESTION_MARK, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_MOVE_NO_SIZE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_MOVE_NO_SIZE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, MOVE_NO_SIZE, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_LTR();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_LTR;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, LTR, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_COMPONENT_KEY_QUALIFICATION_SEPARATOR();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_COMPONENT_KEY_QUALIFICATION_SEPARATOR;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, COMPONENT_KEY_QUALIFICATION_SEPARATOR, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_1_0_0();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_1_0_0;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_1_0_0, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_1_2_0();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_1_2_0;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_1_2_0, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_1_2_2();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_1_2_2;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_1_2_2, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_1_2_3();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_1_2_3;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_1_2_3, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_1_2_8();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_1_2_8;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_1_2_8, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_1_3_0();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_1_3_0;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_1_3_0, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_1_3_1();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_1_3_1;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_1_3_1, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_1_3_4();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_1_3_4;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_1_3_4, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_2_0_0();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_2_0_0;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_2_0_0, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_2_0_1();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_2_0_1;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_2_0_1, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_2_0_2();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_2_0_2;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_2_0_2, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_2_0_3();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_2_0_3;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_2_0_3, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_2_0_5();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_2_0_5;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_2_0_5, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_3_0_0();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_3_0_0;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_3_0_0, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_3_0_1();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_3_0_1;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_3_0_1, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_3_1_0();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_3_1_0;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_3_1_0, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_3_1_2();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_3_1_2;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_3_1_2, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_3_1_3();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_3_1_3;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_3_1_3, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_3_1_4();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_3_1_4;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_3_1_4, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_3_5_0();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_3_5_0;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_3_5_0, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_3_5_1();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_3_5_1;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_3_5_1, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_3_5_2();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_3_5_2;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_3_5_2, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_3_5_3();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_3_5_3;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_3_5_3, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_3_5_4();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_3_5_4;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_3_5_4, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_3_6_1();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_3_6_1;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_3_6_1, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_3_6_2();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_3_6_2;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_3_6_2, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_3_7_0();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_3_7_0;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_3_7_0, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_3_7_1();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_3_7_1;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_3_7_1, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_3_7_3();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_3_7_3;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_3_7_3, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_3_7_5();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_3_7_5;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_3_7_5, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_3_7_6();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_3_7_6;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_3_7_6, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_4_0_0();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_4_0_0;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_4_0_0, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_4_0_1();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_4_0_1;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_4_0_1, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_4_0_2();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_4_0_2;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_4_0_2, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_4_1_1();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_4_1_1;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_4_1_1, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_4_1_2();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_4_1_2;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_4_1_2, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_4_1_3();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_4_1_3;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_4_1_3, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_4_5_0();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_4_5_0;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_4_5_0, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_4_5_1();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_4_5_1;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_4_5_1, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_4_6_0();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_4_6_0;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_4_6_0, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_4_7_0();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_4_7_0;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_4_7_0, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_4_7_1();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_4_7_1;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_4_7_1, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_4_8_0();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_4_8_0;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_4_8_0, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_5_0_0();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_5_0_0;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_5_0_0, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_5_0_1();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_5_0_1;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_5_0_1, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_5_1_2();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_5_1_2;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_5_1_2, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_5_2_0();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_5_2_0;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_5_2_0, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_6_4_0();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_6_4_0;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_6_4_0, NSString *)

inline NSString *OrgOssPdfreporterPropertiesPropertyConstants_get_VERSION_6_4_2();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgOssPdfreporterPropertiesPropertyConstants_VERSION_6_4_2;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgOssPdfreporterPropertiesPropertyConstants, VERSION_6_4_2, NSString *)

J2OBJC_TYPE_LITERAL_HEADER(OrgOssPdfreporterPropertiesPropertyConstants)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgOssPdfreporterPropertiesPropertyConstants")
