//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../pdfreporter-extensions/src/org/oss/pdfreporter/net/MalformedURLException.java
//

#include "J2ObjC_source.h"
#include "java/lang/Exception.h"
#include "org/oss/pdfreporter/net/MalformedURLException.h"

inline jlong OrgOssPdfreporterNetMalformedURLException_get_serialVersionUID();
#define OrgOssPdfreporterNetMalformedURLException_serialVersionUID 1LL
J2OBJC_STATIC_FIELD_CONSTANT(OrgOssPdfreporterNetMalformedURLException, serialVersionUID, jlong)

@implementation OrgOssPdfreporterNetMalformedURLException

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgOssPdfreporterNetMalformedURLException_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithNSString:(NSString *)message
                 withNSException:(NSException *)cause {
  OrgOssPdfreporterNetMalformedURLException_initWithNSString_withNSException_(self, message, cause);
  return self;
}

- (instancetype)initWithNSString:(NSString *)message {
  OrgOssPdfreporterNetMalformedURLException_initWithNSString_(self, message);
  return self;
}

- (instancetype)initWithNSException:(NSException *)cause {
  OrgOssPdfreporterNetMalformedURLException_initWithNSException_(self, cause);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "MalformedURLException", NULL, 0x1, NULL, NULL },
    { "initWithNSString:withNSException:", "MalformedURLException", NULL, 0x1, NULL, NULL },
    { "initWithNSString:", "MalformedURLException", NULL, 0x1, NULL, NULL },
    { "initWithNSException:", "MalformedURLException", NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "serialVersionUID", "serialVersionUID", 0x1a, "J", NULL, NULL, .constantValue.asLong = OrgOssPdfreporterNetMalformedURLException_serialVersionUID },
  };
  static const J2ObjcClassInfo _OrgOssPdfreporterNetMalformedURLException = { 2, "MalformedURLException", "org.oss.pdfreporter.net", NULL, 0x1, 4, methods, 1, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgOssPdfreporterNetMalformedURLException;
}

@end

void OrgOssPdfreporterNetMalformedURLException_init(OrgOssPdfreporterNetMalformedURLException *self) {
  JavaLangException_init(self);
}

OrgOssPdfreporterNetMalformedURLException *new_OrgOssPdfreporterNetMalformedURLException_init() {
  J2OBJC_NEW_IMPL(OrgOssPdfreporterNetMalformedURLException, init)
}

OrgOssPdfreporterNetMalformedURLException *create_OrgOssPdfreporterNetMalformedURLException_init() {
  J2OBJC_CREATE_IMPL(OrgOssPdfreporterNetMalformedURLException, init)
}

void OrgOssPdfreporterNetMalformedURLException_initWithNSString_withNSException_(OrgOssPdfreporterNetMalformedURLException *self, NSString *message, NSException *cause) {
  JavaLangException_initWithNSString_withNSException_(self, message, cause);
}

OrgOssPdfreporterNetMalformedURLException *new_OrgOssPdfreporterNetMalformedURLException_initWithNSString_withNSException_(NSString *message, NSException *cause) {
  J2OBJC_NEW_IMPL(OrgOssPdfreporterNetMalformedURLException, initWithNSString_withNSException_, message, cause)
}

OrgOssPdfreporterNetMalformedURLException *create_OrgOssPdfreporterNetMalformedURLException_initWithNSString_withNSException_(NSString *message, NSException *cause) {
  J2OBJC_CREATE_IMPL(OrgOssPdfreporterNetMalformedURLException, initWithNSString_withNSException_, message, cause)
}

void OrgOssPdfreporterNetMalformedURLException_initWithNSString_(OrgOssPdfreporterNetMalformedURLException *self, NSString *message) {
  JavaLangException_initWithNSString_(self, message);
}

OrgOssPdfreporterNetMalformedURLException *new_OrgOssPdfreporterNetMalformedURLException_initWithNSString_(NSString *message) {
  J2OBJC_NEW_IMPL(OrgOssPdfreporterNetMalformedURLException, initWithNSString_, message)
}

OrgOssPdfreporterNetMalformedURLException *create_OrgOssPdfreporterNetMalformedURLException_initWithNSString_(NSString *message) {
  J2OBJC_CREATE_IMPL(OrgOssPdfreporterNetMalformedURLException, initWithNSString_, message)
}

void OrgOssPdfreporterNetMalformedURLException_initWithNSException_(OrgOssPdfreporterNetMalformedURLException *self, NSException *cause) {
  JavaLangException_initWithNSException_(self, cause);
}

OrgOssPdfreporterNetMalformedURLException *new_OrgOssPdfreporterNetMalformedURLException_initWithNSException_(NSException *cause) {
  J2OBJC_NEW_IMPL(OrgOssPdfreporterNetMalformedURLException, initWithNSException_, cause)
}

OrgOssPdfreporterNetMalformedURLException *create_OrgOssPdfreporterNetMalformedURLException_initWithNSException_(NSException *cause) {
  J2OBJC_CREATE_IMPL(OrgOssPdfreporterNetMalformedURLException, initWithNSException_, cause)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgOssPdfreporterNetMalformedURLException)
