//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../pdfreporter-core/src/org/oss/pdfreporter/engine/fonts/FontInfo.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgOssPdfreporterEngineFontsFontInfo")
#ifdef RESTRICT_OrgOssPdfreporterEngineFontsFontInfo
#define INCLUDE_ALL_OrgOssPdfreporterEngineFontsFontInfo 0
#else
#define INCLUDE_ALL_OrgOssPdfreporterEngineFontsFontInfo 1
#endif
#undef RESTRICT_OrgOssPdfreporterEngineFontsFontInfo

#if !defined (OrgOssPdfreporterEngineFontsFontInfo_) && (INCLUDE_ALL_OrgOssPdfreporterEngineFontsFontInfo || defined(INCLUDE_OrgOssPdfreporterEngineFontsFontInfo))
#define OrgOssPdfreporterEngineFontsFontInfo_

@class OrgOssPdfreporterFontIFont_FontStyle;
@protocol OrgOssPdfreporterEngineFontsFontFace;
@protocol OrgOssPdfreporterEngineFontsFontFamily;

@interface OrgOssPdfreporterEngineFontsFontInfo : NSObject

#pragma mark Public

- (instancetype)initWithOrgOssPdfreporterEngineFontsFontFamily:(id<OrgOssPdfreporterEngineFontsFontFamily>)family
                      withOrgOssPdfreporterEngineFontsFontFace:(id<OrgOssPdfreporterEngineFontsFontFace>)face
                      withOrgOssPdfreporterFontIFont_FontStyle:(OrgOssPdfreporterFontIFont_FontStyle *)style;

- (id<OrgOssPdfreporterEngineFontsFontFace>)getFontFace;

- (id<OrgOssPdfreporterEngineFontsFontFamily>)getFontFamily;

- (OrgOssPdfreporterFontIFont_FontStyle *)getStyle;

- (void)setFontFaceWithOrgOssPdfreporterEngineFontsFontFace:(id<OrgOssPdfreporterEngineFontsFontFace>)face;

- (void)setFontFamilyWithOrgOssPdfreporterEngineFontsFontFamily:(id<OrgOssPdfreporterEngineFontsFontFamily>)family;

- (void)setStyleWithOrgOssPdfreporterFontIFont_FontStyle:(OrgOssPdfreporterFontIFont_FontStyle *)style;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgOssPdfreporterEngineFontsFontInfo)

FOUNDATION_EXPORT void OrgOssPdfreporterEngineFontsFontInfo_initWithOrgOssPdfreporterEngineFontsFontFamily_withOrgOssPdfreporterEngineFontsFontFace_withOrgOssPdfreporterFontIFont_FontStyle_(OrgOssPdfreporterEngineFontsFontInfo *self, id<OrgOssPdfreporterEngineFontsFontFamily> family, id<OrgOssPdfreporterEngineFontsFontFace> face, OrgOssPdfreporterFontIFont_FontStyle *style);

FOUNDATION_EXPORT OrgOssPdfreporterEngineFontsFontInfo *new_OrgOssPdfreporterEngineFontsFontInfo_initWithOrgOssPdfreporterEngineFontsFontFamily_withOrgOssPdfreporterEngineFontsFontFace_withOrgOssPdfreporterFontIFont_FontStyle_(id<OrgOssPdfreporterEngineFontsFontFamily> family, id<OrgOssPdfreporterEngineFontsFontFace> face, OrgOssPdfreporterFontIFont_FontStyle *style) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgOssPdfreporterEngineFontsFontInfo *create_OrgOssPdfreporterEngineFontsFontInfo_initWithOrgOssPdfreporterEngineFontsFontFamily_withOrgOssPdfreporterEngineFontsFontFace_withOrgOssPdfreporterFontIFont_FontStyle_(id<OrgOssPdfreporterEngineFontsFontFamily> family, id<OrgOssPdfreporterEngineFontsFontFace> face, OrgOssPdfreporterFontIFont_FontStyle *style);

J2OBJC_TYPE_LITERAL_HEADER(OrgOssPdfreporterEngineFontsFontInfo)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgOssPdfreporterEngineFontsFontInfo")
