//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../pdfreporter-extensions/src/org/oss/pdfreporter/uses/org/w3c/dom/EntityReference.java
//

#include "J2ObjC_source.h"
#include "org/oss/pdfreporter/uses/org/w3c/dom/EntityReference.h"

@interface OrgOssPdfreporterUsesOrgW3cDomEntityReference : NSObject

@end

@implementation OrgOssPdfreporterUsesOrgW3cDomEntityReference

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcClassInfo _OrgOssPdfreporterUsesOrgW3cDomEntityReference = { 2, "EntityReference", "org.oss.pdfreporter.uses.org.w3c.dom", NULL, 0x609, 0, NULL, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgOssPdfreporterUsesOrgW3cDomEntityReference;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgOssPdfreporterUsesOrgW3cDomEntityReference)
