//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../pdfreporter-extensions/src/org/oss/pdfreporter/uses/net/sourceforge/jeval/operator/Operator.java
//

#include "J2ObjC_source.h"
#include "org/oss/pdfreporter/uses/net/sourceforge/jeval/operator/Operator.h"

@interface OrgOssPdfreporterUsesNetSourceforgeJevalOperatorOperator : NSObject

@end

@implementation OrgOssPdfreporterUsesNetSourceforgeJevalOperatorOperator

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "evaluateWithDouble:withDouble:", "evaluate", "D", 0x401, NULL, NULL },
    { "evaluateWithNSString:withNSString:", "evaluate", "Ljava.lang.String;", 0x401, "Lorg.oss.pdfreporter.uses.net.sourceforge.jeval.EvaluationException;", NULL },
    { "evaluateWithDouble:", "evaluate", "D", 0x401, NULL, NULL },
    { "getSymbol", NULL, "Ljava.lang.String;", 0x401, NULL, NULL },
    { "getPrecedence", NULL, "I", 0x401, NULL, NULL },
    { "getLength", NULL, "I", 0x401, NULL, NULL },
    { "isUnary", NULL, "Z", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _OrgOssPdfreporterUsesNetSourceforgeJevalOperatorOperator = { 2, "Operator", "org.oss.pdfreporter.uses.net.sourceforge.jeval.operator", NULL, 0x609, 7, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgOssPdfreporterUsesNetSourceforgeJevalOperatorOperator;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgOssPdfreporterUsesNetSourceforgeJevalOperatorOperator)
