//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../pdfreporter-core/src/org/oss/pdfreporter/engine/util/AbstractTextMeasurerFactory.java
//

#include "J2ObjC_source.h"
#include "org/oss/pdfreporter/engine/DefaultJasperReportsContext.h"
#include "org/oss/pdfreporter/engine/JRCommonText.h"
#include "org/oss/pdfreporter/engine/fill/JRTextMeasurer.h"
#include "org/oss/pdfreporter/engine/util/AbstractTextMeasurerFactory.h"
#include "org/oss/pdfreporter/engine/util/JRTextMeasurerFactory.h"

#pragma clang diagnostic ignored "-Wprotocol"

@implementation OrgOssPdfreporterEngineUtilAbstractTextMeasurerFactory

- (id<OrgOssPdfreporterEngineFillJRTextMeasurer>)createMeasurerWithOrgOssPdfreporterEngineJRCommonText:(id<OrgOssPdfreporterEngineJRCommonText>)text {
  return [self createMeasurerWithOrgOssPdfreporterEngineJasperReportsContext:OrgOssPdfreporterEngineDefaultJasperReportsContext_getInstance() withOrgOssPdfreporterEngineJRCommonText:text];
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgOssPdfreporterEngineUtilAbstractTextMeasurerFactory_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "createMeasurerWithOrgOssPdfreporterEngineJRCommonText:", "createMeasurer", "Lorg.oss.pdfreporter.engine.fill.JRTextMeasurer;", 0x11, NULL, NULL },
    { "init", "AbstractTextMeasurerFactory", NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcClassInfo _OrgOssPdfreporterEngineUtilAbstractTextMeasurerFactory = { 2, "AbstractTextMeasurerFactory", "org.oss.pdfreporter.engine.util", NULL, 0x401, 2, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgOssPdfreporterEngineUtilAbstractTextMeasurerFactory;
}

@end

void OrgOssPdfreporterEngineUtilAbstractTextMeasurerFactory_init(OrgOssPdfreporterEngineUtilAbstractTextMeasurerFactory *self) {
  NSObject_init(self);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgOssPdfreporterEngineUtilAbstractTextMeasurerFactory)
