//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../pdfreporter-core/src/org/oss/pdfreporter/engine/util/DefaultPrintElementVisitor.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgOssPdfreporterEngineUtilDefaultPrintElementVisitor")
#ifdef RESTRICT_OrgOssPdfreporterEngineUtilDefaultPrintElementVisitor
#define INCLUDE_ALL_OrgOssPdfreporterEngineUtilDefaultPrintElementVisitor 0
#else
#define INCLUDE_ALL_OrgOssPdfreporterEngineUtilDefaultPrintElementVisitor 1
#endif
#undef RESTRICT_OrgOssPdfreporterEngineUtilDefaultPrintElementVisitor

#if !defined (OrgOssPdfreporterEngineUtilDefaultPrintElementVisitor_) && (INCLUDE_ALL_OrgOssPdfreporterEngineUtilDefaultPrintElementVisitor || defined(INCLUDE_OrgOssPdfreporterEngineUtilDefaultPrintElementVisitor))
#define OrgOssPdfreporterEngineUtilDefaultPrintElementVisitor_

#define RESTRICT_OrgOssPdfreporterEnginePrintElementVisitor 1
#define INCLUDE_OrgOssPdfreporterEnginePrintElementVisitor 1
#include "org/oss/pdfreporter/engine/PrintElementVisitor.h"

@protocol OrgOssPdfreporterEngineJRGenericPrintElement;
@protocol OrgOssPdfreporterEngineJRPrintEllipse;
@protocol OrgOssPdfreporterEngineJRPrintFrame;
@protocol OrgOssPdfreporterEngineJRPrintImage;
@protocol OrgOssPdfreporterEngineJRPrintLine;
@protocol OrgOssPdfreporterEngineJRPrintRectangle;
@protocol OrgOssPdfreporterEngineJRPrintText;

@interface OrgOssPdfreporterEngineUtilDefaultPrintElementVisitor : NSObject < OrgOssPdfreporterEnginePrintElementVisitor >

#pragma mark Public

- (instancetype)init;

- (void)visitWithOrgOssPdfreporterEngineJRGenericPrintElement:(id<OrgOssPdfreporterEngineJRGenericPrintElement>)printElement
                                                       withId:(id)arg;

- (void)visitWithOrgOssPdfreporterEngineJRPrintEllipse:(id<OrgOssPdfreporterEngineJRPrintEllipse>)ellipse
                                                withId:(id)arg;

- (void)visitWithOrgOssPdfreporterEngineJRPrintFrame:(id<OrgOssPdfreporterEngineJRPrintFrame>)frame
                                              withId:(id)arg;

- (void)visitWithOrgOssPdfreporterEngineJRPrintImage:(id<OrgOssPdfreporterEngineJRPrintImage>)image
                                              withId:(id)arg;

- (void)visitWithOrgOssPdfreporterEngineJRPrintLine:(id<OrgOssPdfreporterEngineJRPrintLine>)line
                                             withId:(id)arg;

- (void)visitWithOrgOssPdfreporterEngineJRPrintRectangle:(id<OrgOssPdfreporterEngineJRPrintRectangle>)rectangle
                                                  withId:(id)arg;

- (void)visitWithOrgOssPdfreporterEngineJRPrintText:(id<OrgOssPdfreporterEngineJRPrintText>)textElement
                                             withId:(id)arg;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgOssPdfreporterEngineUtilDefaultPrintElementVisitor)

FOUNDATION_EXPORT void OrgOssPdfreporterEngineUtilDefaultPrintElementVisitor_init(OrgOssPdfreporterEngineUtilDefaultPrintElementVisitor *self);

J2OBJC_TYPE_LITERAL_HEADER(OrgOssPdfreporterEngineUtilDefaultPrintElementVisitor)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgOssPdfreporterEngineUtilDefaultPrintElementVisitor")
