//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../pdfreporter-core/src/org/oss/pdfreporter/engine/util/LocalJasperReportsContext.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "java/lang/ClassLoader.h"
#include "java/util/List.h"
#include "java/util/Map.h"
#include "org/oss/pdfreporter/engine/JRParameter.h"
#include "org/oss/pdfreporter/engine/JasperReportsContext.h"
#include "org/oss/pdfreporter/engine/SimpleJasperReportsContext.h"
#include "org/oss/pdfreporter/engine/util/AbstrLocalJasperReportsContext.h"
#include "org/oss/pdfreporter/engine/util/FileResolver.h"
#include "org/oss/pdfreporter/engine/util/LocalJasperReportsContext.h"
#include "org/oss/pdfreporter/repo/DefaultRepositoryService.h"

@interface OrgOssPdfreporterEngineUtilLocalJasperReportsContext () {
 @public
  OrgOssPdfreporterEngineUtilAbstrLocalJasperReportsContext *delegate_;
  OrgOssPdfreporterRepoDefaultRepositoryService *localRepositoryService_;
}

- (OrgOssPdfreporterRepoDefaultRepositoryService *)getLocalRepositoryService;

@end

J2OBJC_FIELD_SETTER(OrgOssPdfreporterEngineUtilLocalJasperReportsContext, delegate_, OrgOssPdfreporterEngineUtilAbstrLocalJasperReportsContext *)
J2OBJC_FIELD_SETTER(OrgOssPdfreporterEngineUtilLocalJasperReportsContext, localRepositoryService_, OrgOssPdfreporterRepoDefaultRepositoryService *)

__attribute__((unused)) static OrgOssPdfreporterRepoDefaultRepositoryService *OrgOssPdfreporterEngineUtilLocalJasperReportsContext_getLocalRepositoryService(OrgOssPdfreporterEngineUtilLocalJasperReportsContext *self);

@implementation OrgOssPdfreporterEngineUtilLocalJasperReportsContext

- (instancetype)initWithOrgOssPdfreporterEngineJasperReportsContext:(id<OrgOssPdfreporterEngineJasperReportsContext>)parent {
  OrgOssPdfreporterEngineUtilLocalJasperReportsContext_initWithOrgOssPdfreporterEngineJasperReportsContext_(self, parent);
  return self;
}

+ (id<OrgOssPdfreporterEngineJasperReportsContext>)getLocalContextWithOrgOssPdfreporterEngineJasperReportsContext:(id<OrgOssPdfreporterEngineJasperReportsContext>)jasperReportsContext
                                                                                                  withJavaUtilMap:(id<JavaUtilMap>)parameterValues {
  return OrgOssPdfreporterEngineUtilLocalJasperReportsContext_getLocalContextWithOrgOssPdfreporterEngineJasperReportsContext_withJavaUtilMap_(jasperReportsContext, parameterValues);
}

- (OrgOssPdfreporterRepoDefaultRepositoryService *)getLocalRepositoryService {
  return OrgOssPdfreporterEngineUtilLocalJasperReportsContext_getLocalRepositoryService(self);
}

- (void)setClassLoaderWithJavaLangClassLoader:(JavaLangClassLoader *)classLoader {
  [((OrgOssPdfreporterRepoDefaultRepositoryService *) nil_chk(OrgOssPdfreporterEngineUtilLocalJasperReportsContext_getLocalRepositoryService(self))) setClassLoaderWithJavaLangClassLoader:classLoader];
}

- (id<OrgOssPdfreporterEngineUtilFileResolver>)getFileResolver {
  return localRepositoryService_ == nil ? nil : [localRepositoryService_ getFileResolver];
}

- (void)setFileResolverWithOrgOssPdfreporterEngineUtilFileResolver:(id<OrgOssPdfreporterEngineUtilFileResolver>)fileResolver {
  [((OrgOssPdfreporterRepoDefaultRepositoryService *) nil_chk(OrgOssPdfreporterEngineUtilLocalJasperReportsContext_getLocalRepositoryService(self))) setFileResolverWithOrgOssPdfreporterEngineUtilFileResolver:fileResolver];
}

- (id<JavaUtilList>)getExtensionsWithIOSClass:(IOSClass *)extensionType {
  return [((OrgOssPdfreporterEngineUtilAbstrLocalJasperReportsContext *) nil_chk(delegate_)) getExtensionsWithIOSClass:extensionType];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithOrgOssPdfreporterEngineJasperReportsContext:", "LocalJasperReportsContext", NULL, 0x1, NULL, NULL },
    { "getLocalContextWithOrgOssPdfreporterEngineJasperReportsContext:withJavaUtilMap:", "getLocalContext", "Lorg.oss.pdfreporter.engine.JasperReportsContext;", 0x9, NULL, "(Lorg/oss/pdfreporter/engine/JasperReportsContext;Ljava/util/Map<Ljava/lang/String;Ljava/lang/Object;>;)Lorg/oss/pdfreporter/engine/JasperReportsContext;" },
    { "getLocalRepositoryService", NULL, "Lorg.oss.pdfreporter.repo.DefaultRepositoryService;", 0x2, NULL, NULL },
    { "setClassLoaderWithJavaLangClassLoader:", "setClassLoader", "V", 0x1, NULL, NULL },
    { "getFileResolver", NULL, "Lorg.oss.pdfreporter.engine.util.FileResolver;", 0x1, NULL, NULL },
    { "setFileResolverWithOrgOssPdfreporterEngineUtilFileResolver:", "setFileResolver", "V", 0x1, NULL, NULL },
    { "getExtensionsWithIOSClass:", "getExtensions", "Ljava.util.List;", 0x1, NULL, "<T:Ljava/lang/Object;>(Ljava/lang/Class<TT;>;)Ljava/util/List<TT;>;" },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "delegate_", NULL, 0x2, "Lorg.oss.pdfreporter.engine.util.AbstrLocalJasperReportsContext;", NULL, NULL, .constantValue.asLong = 0 },
    { "localRepositoryService_", NULL, 0x2, "Lorg.oss.pdfreporter.repo.DefaultRepositoryService;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _OrgOssPdfreporterEngineUtilLocalJasperReportsContext = { 2, "LocalJasperReportsContext", "org.oss.pdfreporter.engine.util", NULL, 0x1, 7, methods, 2, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgOssPdfreporterEngineUtilLocalJasperReportsContext;
}

@end

void OrgOssPdfreporterEngineUtilLocalJasperReportsContext_initWithOrgOssPdfreporterEngineJasperReportsContext_(OrgOssPdfreporterEngineUtilLocalJasperReportsContext *self, id<OrgOssPdfreporterEngineJasperReportsContext> parent) {
  OrgOssPdfreporterEngineSimpleJasperReportsContext_init(self);
  self->delegate_ = new_OrgOssPdfreporterEngineUtilAbstrLocalJasperReportsContext_initWithOrgOssPdfreporterEngineJasperReportsContext_(parent);
}

OrgOssPdfreporterEngineUtilLocalJasperReportsContext *new_OrgOssPdfreporterEngineUtilLocalJasperReportsContext_initWithOrgOssPdfreporterEngineJasperReportsContext_(id<OrgOssPdfreporterEngineJasperReportsContext> parent) {
  J2OBJC_NEW_IMPL(OrgOssPdfreporterEngineUtilLocalJasperReportsContext, initWithOrgOssPdfreporterEngineJasperReportsContext_, parent)
}

OrgOssPdfreporterEngineUtilLocalJasperReportsContext *create_OrgOssPdfreporterEngineUtilLocalJasperReportsContext_initWithOrgOssPdfreporterEngineJasperReportsContext_(id<OrgOssPdfreporterEngineJasperReportsContext> parent) {
  J2OBJC_CREATE_IMPL(OrgOssPdfreporterEngineUtilLocalJasperReportsContext, initWithOrgOssPdfreporterEngineJasperReportsContext_, parent)
}

id<OrgOssPdfreporterEngineJasperReportsContext> OrgOssPdfreporterEngineUtilLocalJasperReportsContext_getLocalContextWithOrgOssPdfreporterEngineJasperReportsContext_withJavaUtilMap_(id<OrgOssPdfreporterEngineJasperReportsContext> jasperReportsContext, id<JavaUtilMap> parameterValues) {
  OrgOssPdfreporterEngineUtilLocalJasperReportsContext_initialize();
  if ([((id<JavaUtilMap>) nil_chk(parameterValues)) containsKeyWithId:OrgOssPdfreporterEngineJRParameter_REPORT_CLASS_LOADER] || [parameterValues containsKeyWithId:OrgOssPdfreporterEngineJRParameter_REPORT_FILE_RESOLVER]) {
    OrgOssPdfreporterEngineUtilLocalJasperReportsContext *localJasperReportsContext = new_OrgOssPdfreporterEngineUtilLocalJasperReportsContext_initWithOrgOssPdfreporterEngineJasperReportsContext_(jasperReportsContext);
    if ([parameterValues containsKeyWithId:OrgOssPdfreporterEngineJRParameter_REPORT_CLASS_LOADER]) {
      [localJasperReportsContext setClassLoaderWithJavaLangClassLoader:(JavaLangClassLoader *) cast_chk([parameterValues getWithId:OrgOssPdfreporterEngineJRParameter_REPORT_CLASS_LOADER], [JavaLangClassLoader class])];
    }
    if ([parameterValues containsKeyWithId:OrgOssPdfreporterEngineJRParameter_REPORT_FILE_RESOLVER]) {
      [localJasperReportsContext setFileResolverWithOrgOssPdfreporterEngineUtilFileResolver:(id<OrgOssPdfreporterEngineUtilFileResolver>) cast_check([parameterValues getWithId:OrgOssPdfreporterEngineJRParameter_REPORT_FILE_RESOLVER], OrgOssPdfreporterEngineUtilFileResolver_class_())];
    }
    return localJasperReportsContext;
  }
  return jasperReportsContext;
}

OrgOssPdfreporterRepoDefaultRepositoryService *OrgOssPdfreporterEngineUtilLocalJasperReportsContext_getLocalRepositoryService(OrgOssPdfreporterEngineUtilLocalJasperReportsContext *self) {
  if (self->localRepositoryService_ == nil) {
    self->localRepositoryService_ = new_OrgOssPdfreporterRepoDefaultRepositoryService_initWithOrgOssPdfreporterEngineJasperReportsContext_(self);
  }
  return self->localRepositoryService_;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgOssPdfreporterEngineUtilLocalJasperReportsContext)
