//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../pdfreporter-core/src/org/oss/pdfreporter/engine/util/ReportCreator.java
//

#include "J2ObjC_source.h"
#include "org/oss/pdfreporter/engine/util/ReportCreator.h"

@interface OrgOssPdfreporterEngineUtilReportCreator : NSObject

@end

@implementation OrgOssPdfreporterEngineUtilReportCreator

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "create", NULL, "Lorg.oss.pdfreporter.engine.design.JasperDesign;", 0x401, "Lorg.oss.pdfreporter.engine.JRException;", NULL },
  };
  static const J2ObjcClassInfo _OrgOssPdfreporterEngineUtilReportCreator = { 2, "ReportCreator", "org.oss.pdfreporter.engine.util", NULL, 0x609, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgOssPdfreporterEngineUtilReportCreator;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgOssPdfreporterEngineUtilReportCreator)
