//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../pdfreporter-core/src/org/oss/pdfreporter/engine/util/ResourceBundleMessageProvider.java
//

#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/text/MessageFormat.h"
#include "java/util/HashMap.h"
#include "org/oss/pdfreporter/engine/util/ResourceBundleMessageProvider.h"
#include "org/oss/pdfreporter/text/bundle/ITextBundle.h"
#include "org/oss/pdfreporter/text/bundle/StringLocale.h"
#include "org/oss/pdfreporter/text/bundle/TextBundle.h"

@interface OrgOssPdfreporterEngineUtilResourceBundleMessageProvider () {
 @public
  NSString *baseName_;
  JavaUtilHashMap *bundles_;
}

@end

J2OBJC_FIELD_SETTER(OrgOssPdfreporterEngineUtilResourceBundleMessageProvider, baseName_, NSString *)
J2OBJC_FIELD_SETTER(OrgOssPdfreporterEngineUtilResourceBundleMessageProvider, bundles_, JavaUtilHashMap *)

@implementation OrgOssPdfreporterEngineUtilResourceBundleMessageProvider

- (instancetype)initWithNSString:(NSString *)baseName {
  OrgOssPdfreporterEngineUtilResourceBundleMessageProvider_initWithNSString_(self, baseName);
  return self;
}

- (NSString *)getMessageWithNSString:(NSString *)code
                   withNSObjectArray:(IOSObjectArray *)args
withOrgOssPdfreporterTextBundleStringLocale:(OrgOssPdfreporterTextBundleStringLocale *)locale {
  NSString *pattern = [self getMessageWithNSString:code withOrgOssPdfreporterTextBundleStringLocale:locale];
  return JavaTextMessageFormat_formatWithNSString_withNSObjectArray_(pattern, args);
}

- (NSString *)getMessageWithNSString:(NSString *)code
withOrgOssPdfreporterTextBundleStringLocale:(OrgOssPdfreporterTextBundleStringLocale *)locale {
  id<OrgOssPdfreporterTextBundleITextBundle> bundle = [((JavaUtilHashMap *) nil_chk(bundles_)) getWithId:locale];
  if (bundle == nil) {
    bundle = OrgOssPdfreporterTextBundleTextBundle_getInstanceWithNSString_withOrgOssPdfreporterTextBundleStringLocale_(baseName_, locale);
    (void) [bundles_ putWithId:locale withId:bundle];
  }
  return [((id<OrgOssPdfreporterTextBundleITextBundle>) nil_chk(bundle)) getStringWithNSString:code];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithNSString:", "ResourceBundleMessageProvider", NULL, 0x1, NULL, NULL },
    { "getMessageWithNSString:withNSObjectArray:withOrgOssPdfreporterTextBundleStringLocale:", "getMessage", "Ljava.lang.String;", 0x1, NULL, NULL },
    { "getMessageWithNSString:withOrgOssPdfreporterTextBundleStringLocale:", "getMessage", "Ljava.lang.String;", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "baseName_", NULL, 0x12, "Ljava.lang.String;", NULL, NULL, .constantValue.asLong = 0 },
    { "bundles_", NULL, 0x12, "Ljava.util.HashMap;", NULL, "Ljava/util/HashMap<Lorg/oss/pdfreporter/text/bundle/StringLocale;Lorg/oss/pdfreporter/text/bundle/ITextBundle;>;", .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _OrgOssPdfreporterEngineUtilResourceBundleMessageProvider = { 2, "ResourceBundleMessageProvider", "org.oss.pdfreporter.engine.util", NULL, 0x1, 3, methods, 2, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgOssPdfreporterEngineUtilResourceBundleMessageProvider;
}

@end

void OrgOssPdfreporterEngineUtilResourceBundleMessageProvider_initWithNSString_(OrgOssPdfreporterEngineUtilResourceBundleMessageProvider *self, NSString *baseName) {
  NSObject_init(self);
  self->bundles_ = new_JavaUtilHashMap_init();
  self->baseName_ = baseName;
}

OrgOssPdfreporterEngineUtilResourceBundleMessageProvider *new_OrgOssPdfreporterEngineUtilResourceBundleMessageProvider_initWithNSString_(NSString *baseName) {
  J2OBJC_NEW_IMPL(OrgOssPdfreporterEngineUtilResourceBundleMessageProvider, initWithNSString_, baseName)
}

OrgOssPdfreporterEngineUtilResourceBundleMessageProvider *create_OrgOssPdfreporterEngineUtilResourceBundleMessageProvider_initWithNSString_(NSString *baseName) {
  J2OBJC_CREATE_IMPL(OrgOssPdfreporterEngineUtilResourceBundleMessageProvider, initWithNSString_, baseName)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgOssPdfreporterEngineUtilResourceBundleMessageProvider)
