//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../pdfreporter-core/src/org/oss/pdfreporter/engine/xml/JRXmlDigester.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "java/io/InputStream.h"
#include "java/lang/RuntimeException.h"
#include "java/util/HashMap.h"
#include "java/util/Map.h"
#include "org/oss/pdfreporter/engine/xml/JRXmlConstants.h"
#include "org/oss/pdfreporter/engine/xml/JRXmlDigester.h"
#include "org/oss/pdfreporter/exception/NotImplementedException.h"
#include "org/oss/pdfreporter/registry/IRegistry.h"
#include "org/oss/pdfreporter/repo/FileResourceLoader.h"
#include "org/oss/pdfreporter/uses/org/apache/digester/DelegatingAbstractDigester.h"
#include "org/oss/pdfreporter/uses/org/apache/digester/IDigester.h"
#include "org/oss/pdfreporter/xml/parsers/IInputSource.h"
#include "org/oss/pdfreporter/xml/parsers/XMLParseException.h"
#include "org/oss/pdfreporter/xml/parsers/factory/IXmlParserFactory.h"

@interface OrgOssPdfreporterEngineXmlJRXmlDigester () {
 @public
  id<OrgOssPdfreporterUsesOrgApacheDigesterIDigester> delegate_JRXmlDigester_;
  id<JavaUtilMap> internalEntityResources_;
  NSString *lastNamespacePrefix_;
  id lastPopped_;
}

- (void)initInternalResources OBJC_METHOD_FAMILY_NONE;

@end

J2OBJC_FIELD_SETTER(OrgOssPdfreporterEngineXmlJRXmlDigester, delegate_JRXmlDigester_, id<OrgOssPdfreporterUsesOrgApacheDigesterIDigester>)
J2OBJC_FIELD_SETTER(OrgOssPdfreporterEngineXmlJRXmlDigester, internalEntityResources_, id<JavaUtilMap>)
J2OBJC_FIELD_SETTER(OrgOssPdfreporterEngineXmlJRXmlDigester, lastNamespacePrefix_, NSString *)
J2OBJC_FIELD_SETTER(OrgOssPdfreporterEngineXmlJRXmlDigester, lastPopped_, id)

__attribute__((unused)) static void OrgOssPdfreporterEngineXmlJRXmlDigester_initInternalResources(OrgOssPdfreporterEngineXmlJRXmlDigester *self);

@implementation OrgOssPdfreporterEngineXmlJRXmlDigester

- (instancetype)initWithOrgOssPdfreporterUsesOrgApacheDigesterIDigester:(id<OrgOssPdfreporterUsesOrgApacheDigesterIDigester>)digester {
  OrgOssPdfreporterEngineXmlJRXmlDigester_initWithOrgOssPdfreporterUsesOrgApacheDigesterIDigester_(self, digester);
  return self;
}

- (void)initInternalResources {
  OrgOssPdfreporterEngineXmlJRXmlDigester_initInternalResources(self);
}

- (void)addInternalEntityResourceWithNSString:(NSString *)systemId
                                 withNSString:(NSString *)resource {
  (void) [((id<JavaUtilMap>) nil_chk(internalEntityResources_)) putWithId:systemId withId:resource];
}

- (id<OrgOssPdfreporterXmlParsersIInputSource>)resolveEntityWithNSString:(NSString *)pubId
                                                            withNSString:(NSString *)systemId {
  id<OrgOssPdfreporterXmlParsersIInputSource> inputSource = nil;
  if (systemId != nil) {
    NSString *resource = [((id<JavaUtilMap>) nil_chk(internalEntityResources_)) getWithId:systemId];
    if (resource == nil) {
      @throw new_JavaLangRuntimeException_initWithNSString_(JreStrcat("$$", @"Unknown entity resource with ID: ", systemId));
    }
    JavaIoInputStream *is = OrgOssPdfreporterRepoFileResourceLoader_getInputStreamWithNSString_(resource);
    if (is != nil) {
      inputSource = [((id<OrgOssPdfreporterXmlParsersFactoryIXmlParserFactory>) nil_chk(OrgOssPdfreporterRegistryIRegistry_getIXmlParserFactory())) newInputSourceWithJavaIoInputStream:is];
    }
  }
  return inputSource;
}

- (void)endElementWithNSString:(NSString *)namespaceURI
                  withNSString:(NSString *)localName
                  withNSString:(NSString *)qName {
  lastNamespacePrefix_ = [self getNamespacePrefixWithNSString:qName];
  [((id<OrgOssPdfreporterUsesOrgApacheDigesterIDigester>) nil_chk(delegate_JRXmlDigester_)) endElementWithNSString:namespaceURI withNSString:localName withNSString:qName];
}

- (NSString *)getNamespacePrefixWithNSString:(NSString *)qName {
  NSString *prefix;
  if (qName == nil) {
    prefix = nil;
  }
  else {
    jint sepIdx = [qName indexOf:':'];
    if (sepIdx > 0) {
      prefix = [qName substring:0 endIndex:sepIdx];
    }
    else {
      prefix = nil;
    }
  }
  return prefix;
}

- (NSString *)getLastNamespacePrefix {
  return lastNamespacePrefix_;
}

- (id)pop {
  lastPopped_ = [((id<OrgOssPdfreporterUsesOrgApacheDigesterIDigester>) nil_chk(delegate_JRXmlDigester_)) pop];
  return lastPopped_;
}

- (void)clearLastPopped {
  lastPopped_ = nil;
}

- (id)lastPopped {
  return lastPopped_;
}

- (void)setDelegatorWithOrgOssPdfreporterUsesOrgApacheDigesterIDigester:(id<OrgOssPdfreporterUsesOrgApacheDigesterIDigester>)delegator {
  @throw new_OrgOssPdfreporterExceptionNotImplementedException_initWithNSString_(@"This implementation is not intended to offer this feature");
}

- (id<OrgOssPdfreporterUsesOrgApacheDigesterIDigester>)getDelegator {
  @throw new_OrgOssPdfreporterExceptionNotImplementedException_initWithNSString_(@"This implementation is not intended to offer this feature");
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithOrgOssPdfreporterUsesOrgApacheDigesterIDigester:", "JRXmlDigester", NULL, 0x1, NULL, NULL },
    { "initInternalResources", NULL, "V", 0x2, NULL, NULL },
    { "addInternalEntityResourceWithNSString:withNSString:", "addInternalEntityResource", "V", 0x1, NULL, NULL },
    { "resolveEntityWithNSString:withNSString:", "resolveEntity", "Lorg.oss.pdfreporter.xml.parsers.IInputSource;", 0x1, NULL, NULL },
    { "endElementWithNSString:withNSString:withNSString:", "endElement", "V", 0x1, "Lorg.oss.pdfreporter.xml.parsers.XMLParseException;", NULL },
    { "getNamespacePrefixWithNSString:", "getNamespacePrefix", "Ljava.lang.String;", 0x4, NULL, NULL },
    { "getLastNamespacePrefix", NULL, "Ljava.lang.String;", 0x1, NULL, NULL },
    { "pop", NULL, "Ljava.lang.Object;", 0x1, NULL, NULL },
    { "clearLastPopped", NULL, "V", 0x1, NULL, NULL },
    { "lastPopped", NULL, "Ljava.lang.Object;", 0x1, NULL, NULL },
    { "setDelegatorWithOrgOssPdfreporterUsesOrgApacheDigesterIDigester:", "setDelegator", "V", 0x1, NULL, NULL },
    { "getDelegator", NULL, "Lorg.oss.pdfreporter.uses.org.apache.digester.IDigester;", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "delegate_JRXmlDigester_", "delegate", 0x12, "Lorg.oss.pdfreporter.uses.org.apache.digester.IDigester;", NULL, NULL, .constantValue.asLong = 0 },
    { "internalEntityResources_", NULL, 0x2, "Ljava.util.Map;", NULL, "Ljava/util/Map<Ljava/lang/String;Ljava/lang/String;>;", .constantValue.asLong = 0 },
    { "lastNamespacePrefix_", NULL, 0x2, "Ljava.lang.String;", NULL, NULL, .constantValue.asLong = 0 },
    { "lastPopped_", NULL, 0x2, "Ljava.lang.Object;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _OrgOssPdfreporterEngineXmlJRXmlDigester = { 2, "JRXmlDigester", "org.oss.pdfreporter.engine.xml", NULL, 0x1, 12, methods, 4, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgOssPdfreporterEngineXmlJRXmlDigester;
}

@end

void OrgOssPdfreporterEngineXmlJRXmlDigester_initWithOrgOssPdfreporterUsesOrgApacheDigesterIDigester_(OrgOssPdfreporterEngineXmlJRXmlDigester *self, id<OrgOssPdfreporterUsesOrgApacheDigesterIDigester> digester) {
  OrgOssPdfreporterUsesOrgApacheDigesterDelegatingAbstractDigester_initWithOrgOssPdfreporterUsesOrgApacheDigesterIDigester_(self, digester);
  self->delegate_JRXmlDigester_ = digester;
  [((id<OrgOssPdfreporterUsesOrgApacheDigesterIDigester>) nil_chk(digester)) setDelegatorWithOrgOssPdfreporterUsesOrgApacheDigesterIDigester:self];
  OrgOssPdfreporterEngineXmlJRXmlDigester_initInternalResources(self);
  [self setXmlEntityResolverWithOrgOssPdfreporterXmlParsersXMLEntityResolver:self];
}

OrgOssPdfreporterEngineXmlJRXmlDigester *new_OrgOssPdfreporterEngineXmlJRXmlDigester_initWithOrgOssPdfreporterUsesOrgApacheDigesterIDigester_(id<OrgOssPdfreporterUsesOrgApacheDigesterIDigester> digester) {
  J2OBJC_NEW_IMPL(OrgOssPdfreporterEngineXmlJRXmlDigester, initWithOrgOssPdfreporterUsesOrgApacheDigesterIDigester_, digester)
}

OrgOssPdfreporterEngineXmlJRXmlDigester *create_OrgOssPdfreporterEngineXmlJRXmlDigester_initWithOrgOssPdfreporterUsesOrgApacheDigesterIDigester_(id<OrgOssPdfreporterUsesOrgApacheDigesterIDigester> digester) {
  J2OBJC_CREATE_IMPL(OrgOssPdfreporterEngineXmlJRXmlDigester, initWithOrgOssPdfreporterUsesOrgApacheDigesterIDigester_, digester)
}

void OrgOssPdfreporterEngineXmlJRXmlDigester_initInternalResources(OrgOssPdfreporterEngineXmlJRXmlDigester *self) {
  self->internalEntityResources_ = new_JavaUtilHashMap_init();
  (void) [self->internalEntityResources_ putWithId:OrgOssPdfreporterEngineXmlJRXmlConstants_JASPERREPORT_SYSTEM_ID withId:OrgOssPdfreporterEngineXmlJRXmlConstants_JASPERREPORT_DTD];
  (void) [((id<JavaUtilMap>) nil_chk(self->internalEntityResources_)) putWithId:OrgOssPdfreporterEngineXmlJRXmlConstants_JASPERPRINT_SYSTEM_ID withId:OrgOssPdfreporterEngineXmlJRXmlConstants_JASPERPRINT_DTD];
  (void) [((id<JavaUtilMap>) nil_chk(self->internalEntityResources_)) putWithId:OrgOssPdfreporterEngineXmlJRXmlConstants_JASPERTEMPLATE_SYSTEM_ID withId:OrgOssPdfreporterEngineXmlJRXmlConstants_JASPERTEMPLATE_DTD];
  (void) [((id<JavaUtilMap>) nil_chk(self->internalEntityResources_)) putWithId:OrgOssPdfreporterEngineXmlJRXmlConstants_JASPERREPORT_XSD_SYSTEM_ID withId:OrgOssPdfreporterEngineXmlJRXmlConstants_JASPERREPORT_XSD_RESOURCE];
  (void) [((id<JavaUtilMap>) nil_chk(self->internalEntityResources_)) putWithId:OrgOssPdfreporterEngineXmlJRXmlConstants_JASPERPRINT_XSD_SYSTEM_ID withId:OrgOssPdfreporterEngineXmlJRXmlConstants_JASPERPRINT_XSD_RESOURCE];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgOssPdfreporterEngineXmlJRXmlDigester)
