//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../pdfreporter-extensions/src/org/oss/pdfreporter/xml/parsers/XMLParseException.java
//

#include "J2ObjC_source.h"
#include "java/lang/Exception.h"
#include "org/oss/pdfreporter/xml/parsers/XMLParseException.h"

inline jlong OrgOssPdfreporterXmlParsersXMLParseException_get_serialVersionUID();
#define OrgOssPdfreporterXmlParsersXMLParseException_serialVersionUID 1LL
J2OBJC_STATIC_FIELD_CONSTANT(OrgOssPdfreporterXmlParsersXMLParseException, serialVersionUID, jlong)

@implementation OrgOssPdfreporterXmlParsersXMLParseException

- (instancetype)initWithNSString:(NSString *)message
                 withNSException:(NSException *)cause {
  OrgOssPdfreporterXmlParsersXMLParseException_initWithNSString_withNSException_(self, message, cause);
  return self;
}

- (instancetype)initWithNSString:(NSString *)message {
  OrgOssPdfreporterXmlParsersXMLParseException_initWithNSString_(self, message);
  return self;
}

- (instancetype)initWithNSException:(NSException *)cause {
  OrgOssPdfreporterXmlParsersXMLParseException_initWithNSException_(self, cause);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithNSString:withNSException:", "XMLParseException", NULL, 0x1, NULL, NULL },
    { "initWithNSString:", "XMLParseException", NULL, 0x1, NULL, NULL },
    { "initWithNSException:", "XMLParseException", NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "serialVersionUID", "serialVersionUID", 0x1a, "J", NULL, NULL, .constantValue.asLong = OrgOssPdfreporterXmlParsersXMLParseException_serialVersionUID },
  };
  static const J2ObjcClassInfo _OrgOssPdfreporterXmlParsersXMLParseException = { 2, "XMLParseException", "org.oss.pdfreporter.xml.parsers", NULL, 0x1, 3, methods, 1, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgOssPdfreporterXmlParsersXMLParseException;
}

@end

void OrgOssPdfreporterXmlParsersXMLParseException_initWithNSString_withNSException_(OrgOssPdfreporterXmlParsersXMLParseException *self, NSString *message, NSException *cause) {
  JavaLangException_initWithNSString_withNSException_(self, message, cause);
}

OrgOssPdfreporterXmlParsersXMLParseException *new_OrgOssPdfreporterXmlParsersXMLParseException_initWithNSString_withNSException_(NSString *message, NSException *cause) {
  J2OBJC_NEW_IMPL(OrgOssPdfreporterXmlParsersXMLParseException, initWithNSString_withNSException_, message, cause)
}

OrgOssPdfreporterXmlParsersXMLParseException *create_OrgOssPdfreporterXmlParsersXMLParseException_initWithNSString_withNSException_(NSString *message, NSException *cause) {
  J2OBJC_CREATE_IMPL(OrgOssPdfreporterXmlParsersXMLParseException, initWithNSString_withNSException_, message, cause)
}

void OrgOssPdfreporterXmlParsersXMLParseException_initWithNSString_(OrgOssPdfreporterXmlParsersXMLParseException *self, NSString *message) {
  JavaLangException_initWithNSString_(self, message);
}

OrgOssPdfreporterXmlParsersXMLParseException *new_OrgOssPdfreporterXmlParsersXMLParseException_initWithNSString_(NSString *message) {
  J2OBJC_NEW_IMPL(OrgOssPdfreporterXmlParsersXMLParseException, initWithNSString_, message)
}

OrgOssPdfreporterXmlParsersXMLParseException *create_OrgOssPdfreporterXmlParsersXMLParseException_initWithNSString_(NSString *message) {
  J2OBJC_CREATE_IMPL(OrgOssPdfreporterXmlParsersXMLParseException, initWithNSString_, message)
}

void OrgOssPdfreporterXmlParsersXMLParseException_initWithNSException_(OrgOssPdfreporterXmlParsersXMLParseException *self, NSException *cause) {
  JavaLangException_initWithNSException_(self, cause);
}

OrgOssPdfreporterXmlParsersXMLParseException *new_OrgOssPdfreporterXmlParsersXMLParseException_initWithNSException_(NSException *cause) {
  J2OBJC_NEW_IMPL(OrgOssPdfreporterXmlParsersXMLParseException, initWithNSException_, cause)
}

OrgOssPdfreporterXmlParsersXMLParseException *create_OrgOssPdfreporterXmlParsersXMLParseException_initWithNSException_(NSException *cause) {
  J2OBJC_CREATE_IMPL(OrgOssPdfreporterXmlParsersXMLParseException, initWithNSException_, cause)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgOssPdfreporterXmlParsersXMLParseException)
