//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../pdfreporter-ios/src/org/oss/pdfreporter/net/factory/NetFactory.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "org/oss/pdfreporter/net/IURL.h"
#include "org/oss/pdfreporter/net/MalformedURLException.h"
#include "org/oss/pdfreporter/net/URL.h"
#include "org/oss/pdfreporter/net/factory/NetFactory.h"
#include "org/oss/pdfreporter/registry/IRegistry.h"

@implementation OrgOssPdfreporterNetFactoryNetFactory

+ (void)registerFactory {
  OrgOssPdfreporterNetFactoryNetFactory_registerFactory();
}

- (id<OrgOssPdfreporterNetIURL>)newURLWithNSString:(NSString *)url {
  return new_OrgOssPdfreporterNetURL_initWithNSString_(url);
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgOssPdfreporterNetFactoryNetFactory_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "registerFactory", NULL, "V", 0x9, NULL, NULL },
    { "newURLWithNSString:", "newURL", "Lorg.oss.pdfreporter.net.IURL;", 0x1, "Lorg.oss.pdfreporter.net.MalformedURLException;", NULL },
    { "init", "NetFactory", NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcClassInfo _OrgOssPdfreporterNetFactoryNetFactory = { 2, "NetFactory", "org.oss.pdfreporter.net.factory", NULL, 0x1, 3, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgOssPdfreporterNetFactoryNetFactory;
}

@end

void OrgOssPdfreporterNetFactoryNetFactory_registerFactory() {
  OrgOssPdfreporterNetFactoryNetFactory_initialize();
  OrgOssPdfreporterRegistryIRegistry_register__WithOrgOssPdfreporterNetFactoryINetFactory_(new_OrgOssPdfreporterNetFactoryNetFactory_init());
}

void OrgOssPdfreporterNetFactoryNetFactory_init(OrgOssPdfreporterNetFactoryNetFactory *self) {
  NSObject_init(self);
}

OrgOssPdfreporterNetFactoryNetFactory *new_OrgOssPdfreporterNetFactoryNetFactory_init() {
  J2OBJC_NEW_IMPL(OrgOssPdfreporterNetFactoryNetFactory, init)
}

OrgOssPdfreporterNetFactoryNetFactory *create_OrgOssPdfreporterNetFactoryNetFactory_init() {
  J2OBJC_CREATE_IMPL(OrgOssPdfreporterNetFactoryNetFactory, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgOssPdfreporterNetFactoryNetFactory)
